-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 24 where id = '283fc0bf-1537-5afe-8c46-bef1e58979be'; -- hacer
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 23 where id = '341dfa9c-9daa-5cd4-8e2e-e463d9acd017'; -- ser
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 22 where id = '4e127e76-890e-5f02-a135-7273cd027a21'; -- tener
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 12 where id = 'c0da2895-a85b-5348-a537-9dc7126feca8'; -- empezar
update public.forms set unit_id = '8b9e9239-cc97-56ec-b263-606f0591c15b', position = 11 where id = '22b3a537-7a0a-58d6-853b-c5c2cb857345'; -- por
update public.forms set unit_id = 'c7cbf578-23ab-5875-9a1c-8104be80ad3e', position = 22 where id = '2ae9f8ea-1866-5e2d-8571-a5381eac1daf'; -- cosa
update public.forms set unit_id = 'c7cbf578-23ab-5875-9a1c-8104be80ad3e', position = 23 where id = '319c56ba-1a4e-5b73-a657-ccd1aac4c464'; -- cosas
update public.forms set unit_id = '5df117af-d5e0-5b71-8caa-6806c47bdff1', position = 5 where id = '4d95dc7c-64cc-560d-83ff-0c1c41bd22b7'; -- llegar
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 21 where id = 'bb58191b-40ee-5dc8-87ae-3319ef2d3d57'; -- hablar
update public.forms set unit_id = '59418fb1-6973-57d9-a75d-e4e21f004b8f', position = 21 where id = '27be1cf0-040a-5443-bae5-bc6980165f0f'; -- alguien
update public.forms set unit_id = '9ed0dbbb-2500-5957-b946-27d34bce9614', position = 13 where id = '4fdce2e8-b614-574e-a1dc-1b205a17baaa'; -- problema
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 25 where id = '976750b9-651d-588a-a81a-fa8fc5f3b60b'; -- comer
update public.forms set unit_id = 'eba40ebe-93cf-52fb-a853-9a2836300617', position = 12 where id = '34e099df-bdef-5e40-b0b3-ee2f1be25577'; -- sé
update public.forms set unit_id = 'eba40ebe-93cf-52fb-a853-9a2836300617', position = 13 where id = '9fea0593-6901-5b60-9b8f-43cb05c8a9ba'; -- sabés
update public.forms set unit_id = 'eba40ebe-93cf-52fb-a853-9a2836300617', position = 14 where id = 'e7faac52-8bbb-5081-94d8-31db8f0de086'; -- sabe
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 34 where id = '4cc0b18c-a8a9-50a2-b7c4-9caeb2576cdd'; -- si
update public.forms set unit_id = 'b60b2d1f-25dc-5ada-9b93-a0afe7bd9a37', position = 16 where id = 'b50dcf31-cb33-5ce5-b70f-f08de2f7a680'; -- conocer
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 27 where id = '18de39a8-543e-56a5-8294-a41b4e1351eb'; -- aprender
update public.forms set unit_id = '740b6205-cb92-54dc-806f-96cc347f8ee0', position = 26 where id = '08ca46a1-c284-5828-afac-f80a58aa9372'; -- vivir
update public.forms set unit_id = '3376ea65-8afe-56be-bae8-b5d06b46c9cd', position = 11 where id = 'fbc5d133-8d7d-5e32-869d-a1f28a78962b'; -- esperar
update public.forms set unit_id = '441e2e5b-f704-511a-9e55-ef9613425ce8', position = 32 where id = 'ae4f1b78-13e4-5218-a59b-499e52a073e0'; -- todo
update public.forms set unit_id = '441e2e5b-f704-511a-9e55-ef9613425ce8', position = 33 where id = '95455d34-e0b1-5c3d-afbd-7e2ac0c1b914'; -- toda
update public.forms set unit_id = 'feb8548b-0ed1-59d1-b3d8-a983690a21d1', position = 23 where id = '878eb292-1542-503f-98ba-8f3d20f24b3c'; -- persona
update public.forms set unit_id = 'ecf3c9a9-33e3-5e2e-b2b7-aa09f082c128', position = 14 where id = '41e0dac1-e480-59a8-a68e-a08fc6d2423b'; -- comida
update public.forms set unit_id = '3376ea65-8afe-56be-bae8-b5d06b46c9cd', position = 21 where id = 'e0682e82-d786-5f60-85ab-ff8f6e6ab9d5'; -- así
update public.forms set unit_id = '441e2e5b-f704-511a-9e55-ef9613425ce8', position = 34 where id = '85bf89ab-4d0e-5c7d-8598-6033f6735660'; -- vez
update public.forms set unit_id = '441e2e5b-f704-511a-9e55-ef9613425ce8', position = 35 where id = '7d56001e-9a72-578f-9640-9ee9d17b4399'; -- veces
update public.forms set unit_id = 'd8cb78a0-5a7d-5c09-9f7f-9e905e0d2e59', position = 11 where id = '1b349bc2-5895-5047-a40c-f0d4da1bd12c'; -- comprar
update public.forms set unit_id = 'b3f216c5-d105-552a-b3f1-254cee4747b1', position = 24 where id = 'd2d26d26-92a8-56c1-a429-39fc102f6803'; -- cuál
update public.forms set unit_id = 'de1b383d-ef2a-56ab-b9e0-5c76ea55a644', position = 18 where id = '03a67e5f-b2fb-5231-a3d6-bdf3f5dd0f78'; -- donde
update public.forms set unit_id = 'b3f216c5-d105-552a-b3f1-254cee4747b1', position = 25 where id = '284df7df-86d3-53ad-88db-58692ef69ed4'; -- cuáles
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 9 where id = '780591f8-2027-5373-995f-b6c0d9a75302'; -- además
update public.forms set unit_id = 'bd710c94-4059-585f-a6ad-448e21cec02f', position = 19 where id = '4cf7221a-c967-5240-9f11-eb45b789f883'; -- último
update public.forms set unit_id = 'bd710c94-4059-585f-a6ad-448e21cec02f', position = 20 where id = '25026f09-5c1f-55e6-81c0-2b815be86544'; -- última
