-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '5269d1e2-0b24-51b5-b272-6da95a4cc1b0', position = 15 where id = 'ade6d2fa-e686-535a-9245-a918870de929'; -- carne
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 18 where id = 'e65d6474-c5a7-59fd-9c24-231a52390e11'; -- audio
update public.forms set unit_id = '62bf976e-3f47-5cc9-b8bb-82f1b5c654b2', position = 16 where id = 'd3e0f2f8-310c-52f9-a336-3b8470cdca16'; -- plato
update public.forms set unit_id = '7c33a900-8b22-5a9e-a34e-7c274e6a21b0', position = 18 where id = '9b784ad0-8077-5c3b-90b9-725f1bf42049'; -- reservé
update public.forms set unit_id = '6d5e1fa5-986d-5b45-a406-035e7c99c15c', position = 9 where id = 'a2b3077c-2ebf-518a-8900-a947ee7c9c75'; -- ruta
