-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

create temporary table reorder_units (id uuid, section_id smallint, ordinal smallint, course_order smallint, old_order smallint) on commit drop;
insert into reorder_units values
  ('d8c13ac1-8ec0-5db3-adbe-39834eed0ff9'::uuid, 12, 3, 280, 279),
  ('f71fcde3-a7e0-5429-864a-cef0a28a9a3f'::uuid, 12, 5, 282, 280),
  ('da717e1e-25b4-54db-a4c6-524cdb07bcfe'::uuid, 12, 7, 284, 281),
  ('68a6baaa-9e78-5479-aa65-63d51bc89b74'::uuid, 12, 9, 286, 282),
  ('9236841b-51b6-5a51-a400-9cf40915ec4e'::uuid, 12, 11, 288, 283),
  ('c64cedd2-5987-5859-b94d-77231e8c5eaa'::uuid, 12, 13, 290, 284),
  ('94eb1988-d122-5fbd-be20-4599d41df698'::uuid, 12, 15, 292, 285),
  ('17f201ba-038f-5447-a92b-ea8274de3421'::uuid, 12, 17, 294, 286),
  ('b27a8863-2d09-52bd-992f-2a73710c019d'::uuid, 12, 19, 296, 287),
  ('f89dd37e-bd2f-5d8b-baac-6f770fe4838c'::uuid, 12, 21, 298, 288),
  ('3c841aec-551f-5e12-a246-f16e72a12923'::uuid, 12, 23, 300, 289),
  ('05427875-acf1-52fc-b7b9-15150a0edca2'::uuid, 12, 26, 303, 290),
  ('4619994d-18cb-57a3-aa86-ef5fd9551f1b'::uuid, 13, 1, 304, 291),
  ('f46f9df0-afdf-5c8c-95be-a4b002904a9d'::uuid, 13, 2, 305, 292),
  ('38d68ef5-9223-5ff2-8954-88f3a9cc0ef3'::uuid, 13, 3, 306, 293),
  ('7743587b-284d-5f25-8f96-38e8f9443429'::uuid, 13, 4, 307, 294),
  ('d7836b8d-78b8-51ae-8e41-57e6f2d5de34'::uuid, 13, 5, 308, 295),
  ('7768d3dd-52a9-55e1-be73-c2b2153fdb64'::uuid, 13, 6, 309, 296),
  ('0549fd4c-6be5-5e51-a1f6-4520eabebe83'::uuid, 13, 7, 310, 297),
  ('b11e93f9-0410-5c63-9d47-ce8b7e4ebfb9'::uuid, 13, 8, 311, 298),
  ('78c71bbd-ead2-54c0-8b92-98f45101f849'::uuid, 13, 9, 312, 299),
  ('b612f887-6567-5b36-b3d8-71b680908d0e'::uuid, 13, 10, 313, 300),
  ('ccf7b1e1-a499-5013-99b2-4830d04fca71'::uuid, 13, 11, 314, 301),
  ('edefc2b5-24ef-5037-9435-816e34d18aaa'::uuid, 13, 12, 315, 302),
  ('e5014ed4-167a-55b0-8e66-43bd2ee4e434'::uuid, 13, 13, 316, 303),
  ('74a94584-d79a-55af-920c-e6fa1c59b5ad'::uuid, 14, 1, 317, 304),
  ('d1ef9d43-816d-571d-a8ba-4ba76a09ba2d'::uuid, 14, 2, 318, 305),
  ('f925644a-c585-5773-8af3-f9a36c4cd2b0'::uuid, 14, 3, 319, 306),
  ('8391605b-e3f5-521c-811d-c849d7eef95f'::uuid, 14, 4, 320, 307),
  ('35edaab3-b8c0-58db-8415-f52edb278a7e'::uuid, 14, 5, 321, 308),
  ('1a2a791f-b759-5930-8cdd-2829e879ce31'::uuid, 14, 6, 322, 309),
  ('4023fc2a-56e8-5980-bada-adc3306da091'::uuid, 14, 7, 323, 310),
  ('5ee78c4c-97f9-5e3c-a458-2aff27520c2e'::uuid, 14, 8, 324, 311),
  ('e0efacaf-93a3-521c-850d-fda4909c6796'::uuid, 14, 9, 325, 312),
  ('24efab50-024b-519e-9029-d2d7f4a05a09'::uuid, 14, 10, 326, 313),
  ('1c04f11a-4feb-5b1d-956b-3661bab59c15'::uuid, 14, 11, 327, 314),
  ('544808fd-b59f-580e-b0be-6f789ba2a11c'::uuid, 14, 12, 328, 315),
  ('58c98ce0-5227-5f11-bf08-49d656a7808b'::uuid, 14, 13, 329, 316),
  ('e3884c35-d0b6-5d6d-9e7f-b4b1308c5981'::uuid, 15, 1, 330, 317),
  ('80d9fccd-c824-5946-8cce-04ecc42e570d'::uuid, 15, 2, 331, 318),
  ('f1fe8414-a662-5131-9e76-a258572724ea'::uuid, 15, 3, 332, 319),
  ('908f70c9-72c3-5244-b3c8-db86021008ed'::uuid, 15, 4, 333, 320),
  ('6d5e1fa5-986d-5b45-a406-035e7c99c15c'::uuid, 15, 5, 334, 321),
  ('5572cf90-36cf-55e2-824b-80f995d2d968'::uuid, 15, 6, 335, 322),
  ('cf4d6a07-a4c5-5761-9bad-5a84df508105'::uuid, 15, 7, 336, 323),
  ('a5e76c4c-fdd3-5652-89d4-4d7a8341eae7'::uuid, 15, 8, 337, 324),
  ('cc075128-b483-5ba0-a24a-485bd1dc71fa'::uuid, 15, 9, 338, 325),
  ('35da2974-7119-59d7-bdf3-d14bdf042064'::uuid, 15, 10, 339, 326),
  ('a25229c0-af37-50d8-86db-83c809276632'::uuid, 15, 11, 340, 327),
  ('f6864f2a-0faf-53cf-a8b4-9e35f6661b10'::uuid, 15, 12, 341, 328),
  ('c1be6404-2a36-51f7-8d0f-43b1a6d26250'::uuid, 15, 13, 342, 329);

-- Through a free range first: ordinals and course places are unique.
update public.units u set ordinal = 20000 + r.ordinal, course_order = 20000 + r.course_order from reorder_units r where u.id = r.id;
update public.units u set section_id = r.section_id, ordinal = r.ordinal, course_order = r.course_order from reorder_units r where u.id = r.id;

-- A placement or jump test is remembered as a course place.
update public.profiles p set placed_through = r.course_order from reorder_units r where p.placed_through = r.old_order;

