-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------






insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('378af04c-16d6-59f8-b02f-936d973ed508', '3827d4cf-2695-5300-9375-8a063e956f02', 'juega', '{"person":3,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'plays', null, '7354baf3-9248-50f2-a9bc-c31acadd98fa', 11, false, null, null, 'draft'),
  ('42ad525f-c16f-5be3-bd70-745751468500', '3827d4cf-2695-5300-9375-8a063e956f02', 'jugamos', '{"person":1,"number":"pl","tense":"pres","mood":"ind"}'::jsonb, 'we play, we played', null, '7354baf3-9248-50f2-a9bc-c31acadd98fa', 12, false, null, null, 'draft'),
  ('1d62d0d8-8749-5153-b37f-4a1ba7a556b9', '3827d4cf-2695-5300-9375-8a063e956f02', 'jugó', '{"person":3,"number":"sg","tense":"pret","mood":"ind"}'::jsonb, 'played', null, '7354baf3-9248-50f2-a9bc-c31acadd98fa', 13, false, null, null, 'draft')
on conflict do nothing;




