-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------







insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('e18de1d0-3a75-57f8-bdb6-a7f4717f404d', 'Nico', 'propn', 'Nico', null, 'neutral', false, null, 'published'),
  ('30d778f6-75ff-5af8-913a-6d54f80729bd', 'Fede', 'propn', 'Fede', null, 'neutral', false, null, 'published'),
  ('10f0a196-7666-54d8-9ef4-254756e93d15', 'Mati', 'propn', 'Mati', null, 'neutral', false, null, 'published'),
  ('0fa86d62-7119-5e9b-acc1-26508ba0330c', 'Pablo', 'propn', 'Pablo', null, 'neutral', false, null, 'published'),
  ('b6435e03-90f0-5ec6-8b7e-c1b5f5f5c6bb', 'Diego', 'propn', 'Diego', null, 'neutral', false, null, 'published'),
  ('9652b2f0-a8c6-5381-a305-6b6a29ef6d7e', 'Santi', 'propn', 'Santi', null, 'neutral', false, null, 'published'),
  ('19fca326-9cdf-5a1f-86ce-0a2d410dffe5', 'Cami', 'propn', 'Cami', null, 'neutral', false, null, 'published'),
  ('3ca1598d-60ae-50a4-86fa-b475758240c3', 'Juli', 'propn', 'Juli', null, 'neutral', false, null, 'published'),
  ('7731bd07-3511-57e9-944d-7501de7049e8', 'Mica', 'propn', 'Mica', null, 'neutral', false, null, 'published'),
  ('d86327e8-8b56-5658-ba7a-3b37eb58d64e', 'Belén', 'propn', 'Belén', null, 'neutral', false, null, 'published'),
  ('08c6cff6-86eb-5459-bee5-a93565d39f5e', 'Rocío', 'propn', 'Rocío', null, 'neutral', false, null, 'published'),
  ('b52ae618-aed3-5ae9-996e-503ffd4815bf', 'Ana', 'propn', 'Ana', null, 'neutral', false, null, 'published')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('3dfed415-c09f-5c72-84f6-47f13fe54405', 'e18de1d0-3a75-57f8-bdb6-a7f4717f404d', 'Nico', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 18, false, null, null, 'published'),
  ('06e3ee33-4221-5d61-bb23-62347baeef3c', '30d778f6-75ff-5af8-913a-6d54f80729bd', 'Fede', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 19, false, null, null, 'published'),
  ('140266d1-06f6-5ce4-9be6-eab3dbdbc772', '10f0a196-7666-54d8-9ef4-254756e93d15', 'Mati', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 20, false, null, null, 'published'),
  ('d1c572e1-6fa8-5cd9-b407-391a8871762a', '0fa86d62-7119-5e9b-acc1-26508ba0330c', 'Pablo', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 21, false, null, null, 'published'),
  ('fec44cf4-d1bd-584c-a4b4-a705207d77e4', 'b6435e03-90f0-5ec6-8b7e-c1b5f5f5c6bb', 'Diego', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 22, false, null, null, 'published'),
  ('15434277-addc-5782-9d76-432820ba64a2', '9652b2f0-a8c6-5381-a305-6b6a29ef6d7e', 'Santi', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 23, false, null, null, 'published'),
  ('4a689b58-a8f4-5574-b6b4-f78d38269097', '19fca326-9cdf-5a1f-86ce-0a2d410dffe5', 'Cami', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 24, false, null, null, 'published'),
  ('036dd23b-0baf-5adf-8b08-ab2cbdaa61fb', '3ca1598d-60ae-50a4-86fa-b475758240c3', 'Juli', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 25, false, null, null, 'published'),
  ('e04deac3-5570-5018-8202-0af9dbca4604', '7731bd07-3511-57e9-944d-7501de7049e8', 'Mica', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 26, false, null, null, 'published'),
  ('c86a9c72-5ebf-55ff-a307-e24c5c54e16e', 'd86327e8-8b56-5658-ba7a-3b37eb58d64e', 'Belén', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 27, false, null, null, 'published'),
  ('0dbf6020-7d89-5742-b893-0c9ac266c047', '08c6cff6-86eb-5459-bee5-a93565d39f5e', 'Rocío', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 28, false, null, null, 'published'),
  ('6731b9a6-2dd4-507f-99da-2342bfdd4ca2', 'b52ae618-aed3-5ae9-996e-503ffd4815bf', 'Ana', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 29, false, null, null, 'published')
on conflict do nothing;




