-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

create temporary table reorder_units (id uuid, section_id smallint, ordinal smallint, course_order smallint, old_order smallint) on commit drop;
insert into reorder_units values
  ('eba40ebe-93cf-52fb-a853-9a2836300617'::uuid, 1, 10, 10, 9),
  ('7c5e7c59-5c44-52e3-9900-449c03934359'::uuid, 1, 11, 11, 10),
  ('b900b7fe-a570-5688-8aa9-d35d025c5c42'::uuid, 1, 12, 12, 11),
  ('481ae401-6c6e-53d7-9683-853d0cbed672'::uuid, 1, 13, 13, 12),
  ('d5d88ab0-8bb3-5ef0-9e7c-8c83d78b32ae'::uuid, 1, 14, 14, 13),
  ('d3b8a1a7-a655-577c-8297-f7f1ff9d08cd'::uuid, 1, 15, 15, 14),
  ('70dda450-3825-5ea7-88fd-296775bc426c'::uuid, 1, 16, 16, 15),
  ('9a6d16d1-11b7-53bd-b0b9-676b76d00eb2'::uuid, 1, 17, 17, 16),
  ('9a649d54-c14a-56da-8701-c4783ad9a159'::uuid, 1, 18, 18, 17),
  ('d8b23128-fa60-5c82-9370-1cad2fff44fc'::uuid, 1, 19, 19, 18),
  ('b28a06e8-ef82-54f0-bbf4-5314e84a7ece'::uuid, 1, 20, 20, 19),
  ('a48206a5-01f1-5f99-a064-2112a1860df7'::uuid, 1, 22, 22, 20),
  ('57ee5db8-0033-56bd-b766-c351ed945cfb'::uuid, 1, 23, 23, 21),
  ('bc934576-e1db-5554-93e2-cec9b7738349'::uuid, 1, 24, 24, 22),
  ('f1fa7454-72a3-546d-8f72-4aab149bbbbe'::uuid, 1, 25, 25, 23),
  ('d8cb78a0-5a7d-5c09-9f7f-9e905e0d2e59'::uuid, 1, 27, 27, 24),
  ('3cc8b1a1-6314-5a4f-be82-b713ea584203'::uuid, 2, 1, 28, 25),
  ('fd0199e1-0dc9-5704-8917-1613531c1778'::uuid, 2, 2, 29, 26),
  ('71481540-7f7c-5939-9d96-ee76d80128b9'::uuid, 2, 3, 30, 27),
  ('9c3ea7c9-a129-5157-b092-804da692c36c'::uuid, 2, 4, 31, 28),
  ('e4dc651e-4fd9-5ba8-8e83-1c8a4131e09e'::uuid, 2, 5, 32, 29),
  ('6d6f0271-451e-511a-ae75-885699df6981'::uuid, 2, 6, 33, 30),
  ('edbefa4a-ecf6-5ba9-8f18-56b44e86a423'::uuid, 2, 8, 35, 31),
  ('eda0d38b-9df5-5bba-9665-c300309be0fa'::uuid, 2, 9, 36, 32),
  ('ef2cae6b-ed9c-5d4b-9d7e-7c65c58dbea5'::uuid, 2, 10, 37, 33),
  ('c5c43fc3-949b-5f6c-99b4-c6da645e7d7f'::uuid, 2, 11, 38, 34),
  ('7f39f4c5-591c-51f7-9f82-ca7f7a1cfb2b'::uuid, 2, 12, 39, 35),
  ('b95d926c-3168-53bd-88bd-c02c868d1119'::uuid, 2, 14, 41, 36),
  ('5269d1e2-0b24-51b5-b272-6da95a4cc1b0'::uuid, 2, 15, 42, 37),
  ('3c53d5f7-3d49-5265-8058-ba19fab0b788'::uuid, 2, 16, 43, 38),
  ('a2eec2e1-5a4c-5372-a1e8-7ac3076576e6'::uuid, 2, 17, 44, 39),
  ('62bf976e-3f47-5cc9-b8bb-82f1b5c654b2'::uuid, 2, 18, 45, 40),
  ('6f572b83-5cbe-528d-bcdf-bbfc32e2b19c'::uuid, 2, 19, 46, 41),
  ('feb8548b-0ed1-59d1-b3d8-a983690a21d1'::uuid, 2, 20, 47, 42),
  ('1974689a-177e-55c9-b4b1-69fba40389f0'::uuid, 2, 21, 48, 43),
  ('a47573dd-a997-5b77-acd6-3b206415f578'::uuid, 2, 22, 49, 44),
  ('7530c631-f8fc-54fb-a160-bf7d158f1f86'::uuid, 2, 23, 50, 45),
  ('9ed0dbbb-2500-5957-b946-27d34bce9614'::uuid, 2, 24, 51, 46),
  ('c7cbf578-23ab-5875-9a1c-8104be80ad3e'::uuid, 2, 25, 52, 47),
  ('61a56ded-546a-5ad6-a8ac-310375bed4ac'::uuid, 2, 26, 53, 48),
  ('2a79010a-154d-5c32-ade0-ded3031c92e1'::uuid, 2, 27, 54, 49),
  ('bf7b8307-3d3a-57b2-9e3b-06bca38b4ef1'::uuid, 3, 1, 55, 50),
  ('be613042-6935-5185-bf3a-fa4dc33eca15'::uuid, 3, 2, 56, 51),
  ('8b9e9239-cc97-56ec-b263-606f0591c15b'::uuid, 3, 3, 57, 52),
  ('740b6205-cb92-54dc-806f-96cc347f8ee0'::uuid, 3, 4, 58, 53),
  ('ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749'::uuid, 3, 5, 59, 54),
  ('b31e1b41-4887-5a80-bbf5-d83e7f8d4fac'::uuid, 3, 6, 60, 55),
  ('3376ea65-8afe-56be-bae8-b5d06b46c9cd'::uuid, 3, 7, 61, 56),
  ('714e2bff-95e1-5d03-96ef-a779c76932b7'::uuid, 3, 8, 62, 57),
  ('4db2a92e-ad85-5b0f-88e2-71629dbf00d2'::uuid, 3, 9, 63, 58),
  ('d9917aa3-1a7b-5287-9437-9c652db27797'::uuid, 3, 10, 64, 59),
  ('72bb9993-19e7-5dad-bdc7-78b4161e7045'::uuid, 3, 11, 65, 60),
  ('13fec277-30b8-5bdb-9718-e682351abfd9'::uuid, 3, 14, 68, 61),
  ('b3f216c5-d105-552a-b3f1-254cee4747b1'::uuid, 3, 15, 69, 62),
  ('5f7fde3f-e53e-535b-a6d1-271ba38c2576'::uuid, 3, 16, 70, 63),
  ('c15b7bfe-bc72-5bf8-a990-5ba1799a2d79'::uuid, 3, 17, 71, 64),
  ('b5b78e79-835c-570f-ad79-3070ec337571'::uuid, 3, 18, 72, 65),
  ('441e2e5b-f704-511a-9e55-ef9613425ce8'::uuid, 3, 19, 73, 66),
  ('86e40753-5eaa-5ab6-b540-6a6f01c756b5'::uuid, 3, 20, 74, 67),
  ('2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b'::uuid, 3, 21, 75, 68),
  ('1638cb53-0a6f-5b5b-a432-fa433a73461e'::uuid, 3, 22, 76, 69),
  ('fa7ef0ed-4de1-5b37-9c23-1d5747ae531d'::uuid, 3, 23, 77, 70),
  ('2c5ceb94-a924-5797-9279-29476c698177'::uuid, 3, 24, 78, 71),
  ('bd710c94-4059-585f-a6ad-448e21cec02f'::uuid, 3, 25, 79, 72),
  ('b10158d0-15cf-5719-a422-9a15ca8305ff'::uuid, 3, 26, 80, 73),
  ('43405ea2-1cec-5d90-bb61-d884ee8359bb'::uuid, 4, 1, 81, 74),
  ('5df117af-d5e0-5b71-8caa-6806c47bdff1'::uuid, 4, 3, 83, 75),
  ('2fa4826d-6276-5a6f-b7a5-e3c2e6dc4f2d'::uuid, 4, 5, 85, 76),
  ('6575b91f-226c-5859-990c-345608df8e59'::uuid, 4, 6, 86, 77),
  ('b60b2d1f-25dc-5ada-9b93-a0afe7bd9a37'::uuid, 4, 7, 87, 78),
  ('de1b383d-ef2a-56ab-b9e0-5c76ea55a644'::uuid, 4, 8, 88, 79),
  ('e89d1870-c4d1-5692-923d-5e357ae8218e'::uuid, 4, 9, 89, 80),
  ('470a7647-d7f6-51fe-aa77-1f96cda7ef58'::uuid, 4, 10, 90, 81),
  ('c2f6a80b-fb62-5345-93bf-172376f29688'::uuid, 4, 11, 91, 82),
  ('f42f6608-6d16-5d0a-bd3f-896cd5fb4d07'::uuid, 4, 12, 92, 83),
  ('59418fb1-6973-57d9-a75d-e4e21f004b8f'::uuid, 4, 13, 93, 84),
  ('fd0afb5a-c86b-5339-b28f-31f5431f400a'::uuid, 4, 14, 94, 85),
  ('fa694c27-06c1-5cf3-b5c7-d369f495abbf'::uuid, 4, 15, 95, 86),
  ('14b391bd-5db8-50a4-a988-428361e7752a'::uuid, 4, 16, 96, 87),
  ('8a2211a4-bc2b-5df6-bfd3-ed761ce08c9a'::uuid, 4, 17, 97, 88),
  ('06235159-d29d-5425-954f-4a61a73fe1f4'::uuid, 4, 18, 98, 89),
  ('9230420b-8a48-5c4b-b9d9-b7dc3c12bb5d'::uuid, 4, 19, 99, 90),
  ('77e7e28f-74ef-5a8f-b15f-5a5589d48684'::uuid, 4, 20, 100, 91),
  ('e21ddcb1-102b-5c87-a018-55c861cdbe47'::uuid, 4, 21, 101, 181),
  ('c72176ae-a8de-5a47-9b37-cf9bdf84de08'::uuid, 4, 22, 102, 92),
  ('51c29d65-4514-5131-bc0a-f7a48158b1db'::uuid, 4, 23, 103, 93),
  ('7c33a900-8b22-5a9e-a34e-7c274e6a21b0'::uuid, 4, 24, 104, 94),
  ('76cdfd4e-984e-51cf-b109-bac7fe371aa2'::uuid, 4, 25, 105, 95),
  ('4147926b-4f4c-5a4e-83c2-d3a82772d8e7'::uuid, 4, 26, 106, 96),
  ('89b3ea96-dbbd-5f0a-8651-0308bd27297d'::uuid, 5, 1, 107, 97),
  ('07ff3e13-7b95-55ab-aab7-ac48151e0d8c'::uuid, 5, 2, 108, 98),
  ('8f8a4c97-4077-5352-b040-a22de57f1b7e'::uuid, 5, 3, 109, 99),
  ('dae6ceff-5881-5f5c-a218-3a6317889caf'::uuid, 5, 4, 110, 100),
  ('38114afb-c035-5ae5-956f-723c4f408a0d'::uuid, 5, 5, 111, 101),
  ('018363b6-528d-5464-8f6a-575ede7fb4d4'::uuid, 5, 6, 112, 102),
  ('520a3c73-f830-5ea8-bb7f-36b6b5a53614'::uuid, 5, 7, 113, 103),
  ('a6cc868d-fbe9-5af4-94d5-1396172806b6'::uuid, 5, 8, 114, 104),
  ('3daf878e-35b0-55b7-8541-2ed16c89f822'::uuid, 5, 9, 115, 105),
  ('7354baf3-9248-50f2-a9bc-c31acadd98fa'::uuid, 5, 10, 116, 106),
  ('102a20da-507c-5cab-8d54-b9dc250aebb6'::uuid, 5, 11, 117, 107),
  ('78c71bbd-ead2-54c0-8b92-98f45101f849'::uuid, 5, 12, 118, 108),
  ('28d6c921-dae2-50d2-b6a0-a5e2423428a6'::uuid, 5, 13, 119, 110),
  ('42aaa1de-ab7b-5276-9032-91bff95ed818'::uuid, 5, 14, 120, 111),
  ('ccf7b1e1-a499-5013-99b2-4830d04fca71'::uuid, 5, 15, 121, 112),
  ('02841028-7fa9-5c47-9159-c4b47cc15cc1'::uuid, 5, 16, 122, 113),
  ('f901adf3-4ac4-5208-8cac-9261ab754144'::uuid, 5, 17, 123, 114),
  ('08e5edec-37ff-59c8-942b-b0fcd4fe251b'::uuid, 5, 18, 124, 115),
  ('364e1a73-f26c-5d78-9757-4d096939ebda'::uuid, 5, 19, 125, 116),
  ('9c4215a1-3276-5ea1-9982-970e15e17072'::uuid, 5, 20, 126, 117),
  ('3f5edc68-b41a-525a-8c80-1dd31a54500b'::uuid, 5, 21, 127, 118),
  ('a6c406c0-0103-5fcc-9871-5e1bc85a3833'::uuid, 5, 22, 128, 119),
  ('da8af0c4-83d8-570d-a76d-ba9f8a8d4161'::uuid, 5, 23, 129, 120),
  ('2902c53a-0143-5823-b423-fd9fe3dc2295'::uuid, 6, 1, 130, 121),
  ('6d5e1fa5-986d-5b45-a406-035e7c99c15c'::uuid, 6, 2, 131, 123),
  ('ad17a937-2fe2-519e-9f42-86f123c7e38c'::uuid, 6, 3, 132, 124),
  ('f2432d21-cbd5-5f7f-aec5-c958b3d7f626'::uuid, 6, 4, 133, 125),
  ('e4a7439f-a626-5e82-abaf-06bc10e30be8'::uuid, 6, 5, 134, 126),
  ('ab5b06cb-0463-5884-9c6f-bc21a5b345d8'::uuid, 6, 6, 135, 127),
  ('754cc69f-e7cf-5e64-ba22-2679bc1f609e'::uuid, 6, 7, 136, 206),
  ('4e77d43e-13ea-5b40-9c1e-dafbe4fd7210'::uuid, 6, 8, 137, 207),
  ('d738540e-3203-5d07-9f0f-01184e8346b0'::uuid, 6, 9, 138, 128),
  ('b2e41f0e-04f0-5a3b-94eb-850cd2d57575'::uuid, 6, 10, 139, 129),
  ('dc485e04-124e-516d-9061-98a2d00f4d57'::uuid, 6, 11, 140, 130),
  ('1bb1664d-4c74-5dfd-9001-ae7f0fd897f8'::uuid, 6, 12, 141, 131),
  ('35edaab3-b8c0-58db-8415-f52edb278a7e'::uuid, 6, 13, 142, 132),
  ('827ff70d-4671-51f6-a0aa-745cfebd058a'::uuid, 6, 14, 143, 133),
  ('c7b4cc13-41a1-57bf-b8f9-9c5a2ef4fb1b'::uuid, 6, 15, 144, 134),
  ('796fb7f5-7211-54d8-83dc-d15338978f46'::uuid, 6, 16, 145, 135),
  ('afdaff40-37c8-56af-ae39-78f1ed48e97e'::uuid, 6, 17, 146, 136),
  ('c0772c39-c5d2-5576-a853-6b67b734fca4'::uuid, 6, 18, 147, 137),
  ('53eebe4b-3a77-563a-84b1-b0ae2a42641c'::uuid, 6, 19, 148, 254),
  ('de1cac02-1435-56ef-9682-17ea2bc59bc4'::uuid, 6, 20, 149, 255),
  ('30394d47-559d-52eb-9c24-d6a8bbaeba36'::uuid, 6, 21, 150, 270),
  ('59c95af3-6785-5037-9294-f36861623e46'::uuid, 6, 22, 151, 271),
  ('e7976a3a-80b3-505d-abc8-858bd6a92a90'::uuid, 6, 23, 152, 138),
  ('3ea35fe7-87c2-5bc5-a138-ed2124298174'::uuid, 6, 24, 153, 139),
  ('3714140a-6ac1-56cd-a67b-a1c55a28970b'::uuid, 6, 25, 154, 140),
  ('a921ed27-35b4-5222-9699-d8dd343c1f79'::uuid, 7, 1, 155, 141),
  ('533e4252-0503-516b-9b3f-fcc7fad29ce1'::uuid, 7, 2, 156, 142),
  ('7768d3dd-52a9-55e1-be73-c2b2153fdb64'::uuid, 7, 3, 157, 143),
  ('e38a0b51-167e-583b-a179-5eafde3573f0'::uuid, 7, 4, 158, 144),
  ('776b15fe-c6a5-5aae-8876-404d392e0546'::uuid, 7, 5, 159, 145),
  ('c7ff7e62-3fed-5f39-9dbd-9ed081d41b0c'::uuid, 7, 6, 160, 146),
  ('d585de30-5927-5cbf-a88a-fc998547f793'::uuid, 7, 7, 161, 147),
  ('d674935a-006a-5328-9d83-767165ba5c5a'::uuid, 7, 8, 162, 148),
  ('3aec2726-7aa4-581b-ab9a-b36725c94e5c'::uuid, 7, 9, 163, 149),
  ('a973933b-ccb4-5f7d-9210-9a063ab4ed00'::uuid, 7, 10, 164, 197),
  ('ed66a36e-5a88-56f2-a2c7-3fdf72291b4e'::uuid, 7, 11, 165, 198),
  ('770b6d5f-bd8c-5c17-a05f-4721faaa1706'::uuid, 7, 12, 166, 150),
  ('672335a3-bca5-50a9-a61e-0d2d70bcd3c2'::uuid, 7, 13, 167, 151),
  ('48134c2e-dbea-5e66-9343-0b82457b9fc1'::uuid, 7, 14, 168, 152),
  ('22f748c4-e86a-57f2-8dfc-09a4885d1d24'::uuid, 7, 15, 169, 153),
  ('35da2974-7119-59d7-bdf3-d14bdf042064'::uuid, 7, 16, 170, 154),
  ('06821d8b-7d2f-5276-b374-2844bb3b99d6'::uuid, 7, 17, 171, 155),
  ('3dd370c2-01fe-54ba-95fc-3c5ef1637eb0'::uuid, 7, 18, 172, 156),
  ('5ec6a727-4a91-5545-9e35-7f858d66ced1'::uuid, 7, 19, 173, 158),
  ('1a2ffa4b-843c-5a51-a395-8402da85268f'::uuid, 7, 20, 174, 159),
  ('2dc6362b-360e-5e66-9d76-2c5e8662af80'::uuid, 7, 21, 175, 160),
  ('7a4e0aad-1065-50e6-bfec-a76b27e0ed9a'::uuid, 7, 22, 176, 161),
  ('6ec21cf5-83ce-55f4-a07c-355a8fb995bb'::uuid, 7, 23, 177, 162),
  ('fa24b60d-3716-5754-bf36-9f5a6843d7bb'::uuid, 7, 24, 178, 204),
  ('a56af3ac-cade-5ff7-bdce-38285c0c74e8'::uuid, 7, 25, 179, 205),
  ('5572cf90-36cf-55e2-824b-80f995d2d968'::uuid, 7, 26, 180, 163),
  ('da7656d3-0e9b-597b-ac1d-493e481b96f5'::uuid, 7, 27, 181, 164),
  ('74698b58-c87a-5870-a6dd-a6652b6da393'::uuid, 8, 1, 182, 165),
  ('26521f59-c2c1-5009-ac6b-a7a2e20a4244'::uuid, 8, 2, 183, 166),
  ('186b6b78-c334-5c53-9675-d7e5ca16b5b4'::uuid, 8, 3, 184, 167),
  ('1c051416-1a0d-564f-bb98-d523f047c49e'::uuid, 8, 4, 185, 168),
  ('5f6c9abe-859a-5d19-853a-7dc6bcce9c99'::uuid, 8, 5, 186, 169),
  ('54074d45-5916-5f81-b9e2-24977fe7b3b0'::uuid, 8, 6, 187, 170),
  ('f93505a1-733d-5810-85e8-c9d6ead98847'::uuid, 8, 7, 188, 171),
  ('8c4c452e-c6f6-5f26-a9a5-ded2342f7c9f'::uuid, 8, 8, 189, 172),
  ('5f67ad55-d966-5850-bf7c-244e5934bef7'::uuid, 8, 9, 190, 173),
  ('52c51646-b698-5749-ae7b-d554ab2e0240'::uuid, 8, 10, 191, 174),
  ('a52f663a-3fe2-5627-a250-4d1da0344831'::uuid, 8, 11, 192, 175),
  ('063d369c-847e-57b8-8451-b9c4049a1d9e'::uuid, 8, 12, 193, 176),
  ('d7a7375d-a258-5d7a-ae1c-44811ac8b58d'::uuid, 8, 13, 194, 177),
  ('ea336760-e828-5137-b3c0-b527db54dc8f'::uuid, 8, 14, 195, 178),
  ('36b953db-b59d-5c37-8572-47afd0081c48'::uuid, 8, 15, 196, 179),
  ('166d8cfb-d95b-581c-aaa6-c1689dc3d072'::uuid, 8, 16, 197, 180),
  ('644dde8f-bffc-57c9-b92e-ec8b078e378c'::uuid, 8, 17, 198, 182),
  ('39867eb4-c78d-5533-9fa6-0c4b2813b9c0'::uuid, 8, 18, 199, 183),
  ('41ef8c3c-f27f-547c-8272-9823215b809f'::uuid, 8, 19, 200, 184),
  ('c0b981e8-bc40-5a7f-a5cd-1aeb1aeedf2f'::uuid, 8, 20, 201, 185),
  ('7709eac2-d5bb-5169-aee7-0ed05c8b866e'::uuid, 8, 21, 202, 186),
  ('20b6357e-6e5d-58e3-814d-c7acd27bedc2'::uuid, 8, 22, 203, 187),
  ('465d788e-db67-5a57-8f4e-96306374e29c'::uuid, 9, 1, 204, 188),
  ('4090ef74-4ded-5132-9a43-cb791fd75c1f'::uuid, 9, 2, 205, 189),
  ('ce343377-a0c2-5201-9ff4-824789e73e89'::uuid, 9, 3, 206, 190),
  ('22657b95-75bd-59a7-a1f7-c21e5df3a6a5'::uuid, 9, 4, 207, 191),
  ('41b8c894-067c-540c-88b8-1a334f63f9e2'::uuid, 9, 5, 208, 192),
  ('7713400b-1007-558d-b717-ac7b02078eed'::uuid, 9, 6, 209, 193),
  ('f71fcde3-a7e0-5429-864a-cef0a28a9a3f'::uuid, 9, 7, 210, 194),
  ('e46f81c7-cdca-5d51-8738-55a0efa5a020'::uuid, 9, 8, 211, 195),
  ('54b42859-ce39-5f29-baa3-7a9aaff0d480'::uuid, 9, 9, 212, 196),
  ('72e14160-96c0-535c-9819-8ab194bd82cc'::uuid, 9, 10, 213, 199),
  ('97d7588e-37ef-5171-9640-6d51b0ac06ba'::uuid, 9, 11, 214, 200),
  ('2fb39a77-4405-52e0-83ee-a83f56d744ad'::uuid, 9, 12, 215, 201),
  ('4093ca08-4709-5a01-b09b-4fd1624d96cf'::uuid, 9, 13, 216, 202),
  ('949c47b5-e244-52bc-9153-03f632f3e5b8'::uuid, 9, 14, 217, 203),
  ('b27a8863-2d09-52bd-992f-2a73710c019d'::uuid, 9, 15, 218, 301),
  ('6aa47fcd-c4fb-5d93-9c82-3c5580df654a'::uuid, 9, 16, 219, 302),
  ('7f76ec46-2ddd-507d-8073-89a5df445d05'::uuid, 9, 17, 220, 273),
  ('654d7d9b-03de-5cfe-a0f2-0124a144bfcf'::uuid, 9, 18, 221, 274),
  ('aa46af4e-1c1b-50ae-b8c1-03167cabaecc'::uuid, 9, 19, 222, 208),
  ('ce25b1d0-ee42-5039-a068-263c69e918ce'::uuid, 9, 20, 223, 209),
  ('b2645ccd-6674-5c14-b607-432b9778545a'::uuid, 9, 21, 224, 210),
  ('ad8fbd77-4b75-55d5-9322-1d952fd8511c'::uuid, 9, 22, 225, 211),
  ('ae52684a-c28b-5318-92e0-5d1cc5ac5cf1'::uuid, 10, 1, 226, 213),
  ('cf3f5063-9758-597c-a509-2476bd48db2d'::uuid, 10, 2, 227, 214),
  ('6dc81d68-66ed-5adc-a6d9-ebdfac00662e'::uuid, 10, 3, 228, 215),
  ('e27cb9dd-52ff-5eed-8b6b-7f5680e6ae7f'::uuid, 10, 4, 229, 216),
  ('c640ea33-8098-56b9-85a3-15f539f2ece2'::uuid, 10, 5, 230, 217),
  ('24068540-4ffd-5c2c-86cb-1c89c0f669d6'::uuid, 10, 6, 231, 218),
  ('2fd57a10-eb7b-5c55-9f86-fd2716e2ed87'::uuid, 10, 7, 232, 219),
  ('98bdf26a-6fb0-57ec-80b0-092e57969285'::uuid, 10, 8, 233, 220),
  ('d7488f2f-ab30-530b-a0f2-9b26a8cb04ad'::uuid, 10, 9, 234, 221),
  ('0549fd4c-6be5-5e51-a1f6-4520eabebe83'::uuid, 10, 10, 235, 222),
  ('6a58e148-25f1-55f5-9568-c47c2c011c1e'::uuid, 10, 11, 236, 223),
  ('5fa3a1dc-bfbe-5b52-a8fb-880e0f0b7173'::uuid, 10, 12, 237, 224),
  ('35957a48-3965-592b-a5e7-2adfd23edfc0'::uuid, 10, 13, 238, 225),
  ('a5ca9719-6dfc-5ebe-8ce3-339422b185b5'::uuid, 10, 14, 239, 226),
  ('577ff67b-76f7-513b-adca-5871bbb950dc'::uuid, 10, 15, 240, 227),
  ('20eecfc9-6b84-54ae-aedc-1c389863baf9'::uuid, 10, 16, 241, 229),
  ('36036d7c-a216-5b60-a76c-a59bf988487b'::uuid, 10, 17, 242, 230),
  ('d7e9f660-01d8-5d0f-9136-9a85a20fc33b'::uuid, 10, 18, 243, 231),
  ('4cba4d7d-a414-57c7-9ed9-cbf8046345e2'::uuid, 10, 19, 244, 232),
  ('17f201ba-038f-5447-a92b-ea8274de3421'::uuid, 10, 20, 245, 233),
  ('a3c55aeb-a257-5eb2-ac90-fc258b138c7e'::uuid, 10, 21, 246, 234),
  ('4092e026-b5b7-5725-9f9e-564fc956c0e4'::uuid, 10, 22, 247, 235),
  ('7da0178d-42ee-5e98-aece-77ffbb45dd2d'::uuid, 10, 23, 248, 236),
  ('59b48665-2d47-587e-b406-84d2800c4161'::uuid, 11, 1, 249, 238),
  ('68cbb710-d119-5f34-a613-de8835c78c69'::uuid, 11, 2, 250, 239),
  ('21206ba6-6522-5849-be52-419e7d6d1007'::uuid, 11, 3, 251, 240),
  ('345642d1-7c5d-58fc-936d-78082196d9c0'::uuid, 11, 4, 252, 241),
  ('dd303fe0-52c5-5e61-97ae-1903616e625c'::uuid, 11, 5, 253, 242),
  ('558006ff-a18d-5fc9-ae98-edf66c5a28dc'::uuid, 11, 6, 254, 243),
  ('ea7df981-3c2b-53d4-96e1-cee2e5d5bd8e'::uuid, 11, 7, 255, 244),
  ('e31d82b3-e9e2-52bc-bd88-e52c7b53a764'::uuid, 11, 8, 256, 245),
  ('e3ba7db9-0794-5f78-95a6-dbd6a3e616be'::uuid, 11, 9, 257, 246),
  ('b3d7d4fe-8ba0-58f9-8d0e-38b9aaf3707f'::uuid, 11, 10, 258, 247),
  ('68c86280-614b-5223-b263-aed0f05b7b3c'::uuid, 11, 11, 259, 248),
  ('79cfb639-7996-5ed9-85ae-f73c0cf69e58'::uuid, 11, 12, 260, 249),
  ('aaafb4dd-18af-5b10-be4f-33a46f2cba0e'::uuid, 11, 13, 261, 250),
  ('d2d1e75f-f8c3-5507-9e3a-6019ac0c40a0'::uuid, 11, 14, 262, 251),
  ('9cd92c11-142e-5820-ac05-2ba0eb3f623c'::uuid, 11, 15, 263, 252),
  ('eedc812b-9def-5602-bd94-b8fc7ba8e7b6'::uuid, 11, 16, 264, 253),
  ('4a9c7846-0bb3-5a60-94df-2f6897d2a8dc'::uuid, 11, 17, 265, 256),
  ('4356c8d2-a33c-5a38-8b20-f4ac90387e6f'::uuid, 11, 18, 266, 257),
  ('c9686bb1-fe4a-58d4-b91f-601bade129fa'::uuid, 11, 19, 267, 259),
  ('1c8ca38f-494c-5a2e-bfa5-7e72e5d84a3e'::uuid, 11, 20, 268, 260),
  ('fc31544c-c615-5722-9494-5a728b6cf9be'::uuid, 12, 1, 269, 261),
  ('8ec0010d-66b0-5b69-aadb-eca273e4ae43'::uuid, 12, 2, 270, 262),
  ('731a6e56-3586-5647-a6ab-12df3dec98b6'::uuid, 12, 3, 271, 263),
  ('504b4319-d4ab-5b42-870b-fea27ef57652'::uuid, 12, 4, 272, 264),
  ('c1f2d5a6-e52b-5745-80dc-1ef79ac0846a'::uuid, 12, 5, 273, 265),
  ('0323848f-596e-579a-a7dd-1904e93c1f32'::uuid, 12, 6, 274, 266),
  ('73fd97d5-bdd1-55a6-889b-4ba0e1f184ca'::uuid, 12, 7, 275, 267),
  ('109ff419-4504-54fc-a4e6-0f7e45175049'::uuid, 12, 8, 276, 268),
  ('54b1d14e-7e6a-5640-a4f9-881b68a6d24f'::uuid, 12, 9, 277, 269),
  ('bcdc9d4e-84a9-5981-aa9d-14009abf363a'::uuid, 12, 10, 278, 272),
  ('c5abd659-9dd6-54e9-9e4f-6e906e375953'::uuid, 12, 11, 279, 275),
  ('74e55bc5-1757-5c97-bd67-5353fb4b592e'::uuid, 12, 12, 280, 276),
  ('80bd27a8-6356-5caa-9a38-661a03999602'::uuid, 12, 13, 281, 277),
  ('6c74bbe5-52cb-545d-bcf5-384fc0d1138b'::uuid, 12, 14, 282, 278),
  ('0e125e12-ab8c-5bfd-8a5d-6ae28790e249'::uuid, 12, 15, 283, 279),
  ('e0efacaf-93a3-521c-850d-fda4909c6796'::uuid, 12, 16, 284, 280),
  ('9f441bef-17a2-535a-a539-79a16389ad10'::uuid, 12, 17, 285, 281),
  ('4aaf79fa-f71f-5712-8a98-5facae7b4221'::uuid, 12, 18, 286, 282),
  ('cc075128-b483-5ba0-a24a-485bd1dc71fa'::uuid, 12, 19, 287, 283),
  ('08db04c7-6430-585e-8d87-f26f0376c7ad'::uuid, 12, 20, 288, 284),
  ('8a547039-7fc7-5382-9c3a-9b48a4102289'::uuid, 13, 1, 289, 285),
  ('06d1371f-27e8-5be1-a3df-a530cc9eefe3'::uuid, 13, 2, 290, 286),
  ('d8c13ac1-8ec0-5db3-adbe-39834eed0ff9'::uuid, 13, 3, 291, 287),
  ('c03bcd83-1ed7-5fb6-a4e9-dae2cd690f4b'::uuid, 13, 4, 292, 288),
  ('8615c579-1ee7-516d-8329-85243ee4db53'::uuid, 13, 5, 293, 289),
  ('68a6baaa-9e78-5479-aa65-63d51bc89b74'::uuid, 13, 6, 294, 290),
  ('38987042-d239-57ac-9bcf-58be792a8609'::uuid, 13, 7, 295, 291),
  ('e3884c35-d0b6-5d6d-9e7f-b4b1308c5981'::uuid, 13, 8, 296, 292),
  ('a9fb512f-6297-573c-8d34-be942749040d'::uuid, 13, 9, 297, 293),
  ('80d9fccd-c824-5946-8cce-04ecc42e570d'::uuid, 13, 10, 298, 294),
  ('112b1b4f-7388-538e-9734-dab36a241ad2'::uuid, 13, 11, 299, 295),
  ('9236841b-51b6-5a51-a400-9cf40915ec4e'::uuid, 13, 12, 300, 296),
  ('1e64d895-153a-5af6-b41e-45c6b9da78d4'::uuid, 13, 13, 301, 297),
  ('c64cedd2-5987-5859-b94d-77231e8c5eaa'::uuid, 13, 14, 302, 298),
  ('685c49ba-32f9-5e23-acab-d8552fdf4a20'::uuid, 13, 15, 303, 299),
  ('8fd78797-231c-5920-8d41-337bed37a7a9'::uuid, 13, 16, 304, 300),
  ('f89dd37e-bd2f-5d8b-baac-6f770fe4838c'::uuid, 13, 17, 305, 303),
  ('4f79112a-7e16-5786-a09f-c3f47eec42c1'::uuid, 13, 18, 306, 304),
  ('06acaaed-73cd-553d-a457-b534da4c99d0'::uuid, 13, 19, 307, 305),
  ('976c0600-48a2-5a5a-9ddb-85af02f42f69'::uuid, 13, 20, 308, 306),
  ('05427875-acf1-52fc-b7b9-15150a0edca2'::uuid, 13, 21, 309, 307),
  ('4619994d-18cb-57a3-aa86-ef5fd9551f1b'::uuid, 14, 1, 310, 308),
  ('00142c01-014f-53a8-b11d-1cf2bf832643'::uuid, 14, 2, 311, 309),
  ('f46f9df0-afdf-5c8c-95be-a4b002904a9d'::uuid, 14, 3, 312, 310),
  ('f02fa743-710e-5e6c-880b-e826a6c0056a'::uuid, 14, 4, 313, 311),
  ('38d68ef5-9223-5ff2-8954-88f3a9cc0ef3'::uuid, 14, 5, 314, 312),
  ('498e2179-7921-5c4c-8aa0-add0a77bf455'::uuid, 14, 6, 315, 314),
  ('d7836b8d-78b8-51ae-8e41-57e6f2d5de34'::uuid, 14, 7, 316, 315),
  ('e4860d3e-3ee3-5fc4-8b35-41209dd58a5e'::uuid, 14, 8, 317, 317),
  ('b612f887-6567-5b36-b3d8-71b680908d0e'::uuid, 14, 9, 318, 318),
  ('85347a66-3161-5a8d-9251-44225d44ad33'::uuid, 14, 10, 319, 319),
  ('013dc4ab-e838-53ac-ac0a-48d708431761'::uuid, 14, 11, 320, 320),
  ('c18ed3f6-ae4d-50fd-b360-6d7e7d73144c'::uuid, 14, 12, 321, 321),
  ('74a94584-d79a-55af-920c-e6fa1c59b5ad'::uuid, 14, 13, 322, 323),
  ('5c5f55d2-b389-5e93-94b9-3eb2897e1055'::uuid, 14, 14, 323, 324),
  ('d1ef9d43-816d-571d-a8ba-4ba76a09ba2d'::uuid, 14, 15, 324, 325),
  ('f925644a-c585-5773-8af3-f9a36c4cd2b0'::uuid, 14, 16, 325, 327),
  ('52f4c57b-461b-5689-bc83-625e8445b0b2'::uuid, 14, 17, 326, 328),
  ('8096e043-1d54-5521-ac96-7cdb39c6e872'::uuid, 14, 18, 327, 329),
  ('1a2a791f-b759-5930-8cdd-2829e879ce31'::uuid, 14, 19, 328, 330),
  ('28506229-594f-503e-80d4-5a3a1085320a'::uuid, 14, 20, 329, 331),
  ('4023fc2a-56e8-5980-bada-adc3306da091'::uuid, 15, 1, 330, 332),
  ('e3d036c1-9bf7-582a-8fdc-04202411acae'::uuid, 15, 2, 331, 333),
  ('aca6a7bd-05eb-5bcb-a0c0-02cd6ba77040'::uuid, 15, 3, 332, 334),
  ('24efab50-024b-519e-9029-d2d7f4a05a09'::uuid, 15, 4, 333, 335),
  ('31b7857e-57f3-5f7b-bcef-b36286ed3425'::uuid, 15, 5, 334, 336),
  ('1c04f11a-4feb-5b1d-956b-3661bab59c15'::uuid, 15, 6, 335, 337),
  ('d750cc27-0380-5a63-ae57-c94ac17315e5'::uuid, 15, 7, 336, 338),
  ('7957b305-bc76-56e8-b615-86768419c16d'::uuid, 15, 8, 337, 339),
  ('a36e5278-67e4-5dc0-b0ec-7e8440a51419'::uuid, 15, 9, 338, 340),
  ('58c98ce0-5227-5f11-bf08-49d656a7808b'::uuid, 15, 10, 339, 341),
  ('f1fe8414-a662-5131-9e76-a258572724ea'::uuid, 15, 11, 340, 342),
  ('d8bc6075-554e-5b94-9a5b-df5e1686741a'::uuid, 15, 12, 341, 343),
  ('512c0d0a-584d-5403-9bcf-d9c74d8ceb43'::uuid, 15, 13, 342, 344),
  ('cf4d6a07-a4c5-5761-9bad-5a84df508105'::uuid, 15, 14, 343, 345),
  ('0dacd2e3-2a45-5ad7-a13d-42f6b718c484'::uuid, 15, 15, 344, 346),
  ('7213df53-3f20-5649-8b69-0dacbe10f0d7'::uuid, 15, 16, 345, 347),
  ('a25229c0-af37-50d8-86db-83c809276632'::uuid, 15, 17, 346, 348),
  ('132415fc-1b04-527c-a000-1361223954c5'::uuid, 15, 18, 347, 349),
  ('5ebbe531-b8e4-58e6-9eb8-b9340f28458c'::uuid, 15, 19, 348, 350),
  ('6da6ead7-b546-54e5-b84f-a16a56ef3f2a'::uuid, 15, 20, 349, 351),
  ('c1be6404-2a36-51f7-8d0f-43b1a6d26250'::uuid, 15, 21, 350, 352);

-- Through a free range first: ordinals and course places are unique. The course
-- place is the free ordinal too: a unit changing section may land on an ordinal
-- another unit of its old section is also headed for.
update public.units u set ordinal = 20000 + r.course_order, course_order = 20000 + r.course_order from reorder_units r where u.id = r.id;
update public.units u set section_id = r.section_id, ordinal = r.ordinal, course_order = r.course_order from reorder_units r where u.id = r.id;

-- A placement or jump test is remembered as a course place.
update public.profiles p set placed_through = r.course_order from reorder_units r where p.placed_through = r.old_order;

-- Words taught earlier now.
update public.forms set unit_id = '62bf976e-3f47-5cc9-b8bb-82f1b5c654b2', position = 14 where id = '8c5437be-7d42-5707-aaad-0f3dda0d290f'; -- mesa
update public.forms set unit_id = '1f792bd1-c22b-5919-b21f-f22c96ecef14', position = 11 where id = 'b6f85b91-478a-579e-815c-08d5cbf32074'; -- muy
update public.forms set unit_id = '6d6f0271-451e-511a-ae75-885699df6981', position = 14 where id = '18d35451-6a07-5b36-a307-eb1148588098'; -- buena
update public.forms set unit_id = '6d6f0271-451e-511a-ae75-885699df6981', position = 15 where id = '95814ad2-fe55-57d9-89bb-524c29e92a5b'; -- buenos
update public.forms set unit_id = 'd738540e-3203-5d07-9f0f-01184e8346b0', position = 7 where id = 'b34301ac-e2c6-5334-bd1a-69073a323daa'; -- me acuerdo
update public.forms set unit_id = 'd738540e-3203-5d07-9f0f-01184e8346b0', position = 8 where id = '24411c20-1bac-5087-bae4-274936f27bb7'; -- te acordás
update public.forms set unit_id = 'd738540e-3203-5d07-9f0f-01184e8346b0', position = 9 where id = '183c55db-684e-5278-87d3-ef397bceb006'; -- acuerdo
update public.forms set unit_id = 'd738540e-3203-5d07-9f0f-01184e8346b0', position = 10 where id = '302ef971-e867-5b5c-b142-45e6304ca5fc'; -- acordás
update public.forms set unit_id = '5df117af-d5e0-5b71-8caa-6806c47bdff1', position = 18 where id = '9151df2a-a4c4-5215-9db6-616ca8b106bb'; -- llevar
update public.forms set unit_id = '9c3ea7c9-a129-5157-b092-804da692c36c', position = 14 where id = 'eaf62dca-5644-5581-812c-20f475a65a32'; -- cargador
update public.forms set unit_id = '9c3ea7c9-a129-5157-b092-804da692c36c', position = 15 where id = 'cd7cf048-69ff-5584-aac8-a2182ed521b9'; -- cargadores
update public.forms set unit_id = '6d6f0271-451e-511a-ae75-885699df6981', position = 12 where id = '84e01c84-d379-5aa4-b892-d09f0101d1a0'; -- malo
update public.forms set unit_id = '6d6f0271-451e-511a-ae75-885699df6981', position = 13 where id = '1af9aebe-bae2-5b69-b3e7-6ecb7a49d64b'; -- mala
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 7 where id = '4334beea-3861-53fb-840f-f87b41a29c55'; -- se comprometieron
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 8 where id = '4fbb76f0-4ede-57e1-b465-15b243be7f8c'; -- comprometieron
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 14 where id = '5d6cc3ff-4a82-53be-8395-947c999d1cc1'; -- nene
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 15 where id = 'f9d82ba2-1e9c-536f-be7c-a8e2cbed3ab3'; -- nena
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 9 where id = '40bd2d0c-7dee-5ed9-b0b9-01d6a04e140e'; -- anillo
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 10 where id = '7f075239-3ab6-59f1-84a9-34bf1e7fc482'; -- luna de miel
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 12 where id = '02956c89-741f-56c7-af3d-d2225c82fda0'; -- padrino
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 13 where id = '514ef728-f5cb-5362-b9e5-73754ebca556'; -- madrina
update public.forms set unit_id = '35da2974-7119-59d7-bdf3-d14bdf042064', position = 11 where id = '4ece7690-123a-55ee-b4f5-24cd160ad599'; -- por civil
update public.forms set unit_id = '89b3ea96-dbbd-5f0a-8651-0308bd27297d', position = 14 where id = '0e2d3462-0979-5991-917d-de0593d4891e'; -- un montón
update public.forms set unit_id = 'a2eec2e1-5a4c-5372-a1e8-7ac3076576e6', position = 12 where id = '57d50f8b-2aef-5172-9a9d-917d6485e802'; -- frío
update public.forms set unit_id = 'a2eec2e1-5a4c-5372-a1e8-7ac3076576e6', position = 13 where id = '91c4a6a0-62af-505e-a964-de29194779b1'; -- fría
update public.forms set unit_id = '754cc69f-e7cf-5e64-ba22-2679bc1f609e', position = 8 where id = '1e1e02d5-e6f2-5667-87b4-3e66d422a2ca'; -- me parece
update public.forms set unit_id = '754cc69f-e7cf-5e64-ba22-2679bc1f609e', position = 9 where id = '14b46a07-cea1-5ef5-b976-b7b672f86d5c'; -- te parece
update public.forms set unit_id = '754cc69f-e7cf-5e64-ba22-2679bc1f609e', position = 10 where id = 'd4ab13fd-e4f2-58d8-9f40-371c305e7dbf'; -- parece
update public.forms set unit_id = 'e21ddcb1-102b-5c87-a018-55c861cdbe47', position = 5 where id = '9e65cc89-fa82-5a4e-be1d-d6fb74ccf98d'; -- ni idea
update public.forms set unit_id = 'e21ddcb1-102b-5c87-a018-55c861cdbe47', position = 6 where id = '7a4b15e9-ee77-5133-a59c-437fc163093a'; -- idea
update public.forms set unit_id = '8b9e9239-cc97-56ec-b263-606f0591c15b', position = 14 where id = '79fd484a-d703-5752-bf1b-24c30768bf33'; -- lugar
update public.forms set unit_id = 'fd0afb5a-c86b-5339-b28f-31f5431f400a', position = 12 where id = '7adc6dd4-a88c-5b5e-8aa8-2a70e0dfaa3b'; -- tanto
update public.forms set unit_id = '30394d47-559d-52eb-9c24-d6a8bbaeba36', position = 10 where id = '98efa0e8-848f-532e-897e-ba93eea8bcd6'; -- estacionar
update public.forms set unit_id = '30394d47-559d-52eb-9c24-d6a8bbaeba36', position = 11 where id = 'ea0fcf7f-fc9a-544e-a343-910f9681e38a'; -- estacioné
update public.forms set unit_id = 'f42f6608-6d16-5d0a-bd3f-896cd5fb4d07', position = 19 where id = '51b896e6-d898-5a2e-92d5-2d909bbf9bdc'; -- leí
update public.forms set unit_id = 'f42f6608-6d16-5d0a-bd3f-896cd5fb4d07', position = 20 where id = '7c06be01-4eaf-5210-b58a-0bad3d33d784'; -- leíste
update public.forms set unit_id = '2fb39a77-4405-52e0-83ee-a83f56d744ad', position = 3 where id = 'f91e8e95-450f-5677-9699-f4117ef05d51'; -- radio
update public.forms set unit_id = '2fb39a77-4405-52e0-83ee-a83f56d744ad', position = 4 where id = 'aab8d1ff-b445-5e10-855b-1d8e0e903272'; -- redes
update public.forms set unit_id = '2fb39a77-4405-52e0-83ee-a83f56d744ad', position = 5 where id = 'cc338f40-55f6-54ff-950a-e2550810a801'; -- mentira
update public.forms set unit_id = '8b9e9239-cc97-56ec-b263-606f0591c15b', position = 12 where id = 'f9c0caa3-7606-5efb-85c2-34ece7c1aa61'; -- queda
update public.forms set unit_id = '8b9e9239-cc97-56ec-b263-606f0591c15b', position = 13 where id = '6032c36f-3ec7-5c9f-a50c-c58f9243dc66'; -- quedan
update public.forms set unit_id = '5df117af-d5e0-5b71-8caa-6806c47bdff1', position = 20 where id = 'aefd6c07-fb77-5c5e-ae9e-30fe58c30dac'; -- llevá
update public.forms set unit_id = '5df117af-d5e0-5b71-8caa-6806c47bdff1', position = 19 where id = 'ef2b5fe8-1c05-5f5f-bb87-77466fb59db5'; -- llevo
update public.forms set unit_id = 'da7656d3-0e9b-597b-ac1d-493e481b96f5', position = 16 where id = 'eefa33ec-1f1f-549a-bce8-7f676baca272'; -- pava
update public.forms set unit_id = '7f76ec46-2ddd-507d-8073-89a5df445d05', position = 9 where id = 'd5c961c9-04c7-5bd4-a4cb-1ee28db0ffbb'; -- cobraron
update public.forms set unit_id = '89b3ea96-dbbd-5f0a-8651-0308bd27297d', position = 15 where id = '1fa57de0-0baa-57b6-b0be-6a3405d9aed5'; -- uy
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 4 where id = '9cc5e8a3-58d7-5c38-9983-f8d99c143b44'; -- acabamos de
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 5 where id = '054d9b1a-ca34-59d0-a6fd-608cb5527db6'; -- acaban de
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 9 where id = 'b1da9592-c0e8-59a3-88dd-1057cded109b'; -- solemos
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 10 where id = 'c5b6bf0d-150d-5cbe-91c0-3c4f0fa96ac0'; -- suelen
update public.forms set unit_id = '30394d47-559d-52eb-9c24-d6a8bbaeba36', position = 12 where id = '64eacd10-56a4-5db1-930f-30b8603738b6'; -- fumar
update public.forms set unit_id = '7a4e0aad-1065-50e6-bfec-a76b27e0ed9a', position = 11 where id = '7ec41db4-f03c-5b2a-be38-a858966e7c23'; -- verdad
update public.forms set unit_id = 'e89d1870-c4d1-5692-923d-5e357ae8218e', position = 15 where id = '11b803d1-b113-5f22-bec8-cf6bb2138420'; -- hace cuánto
update public.forms set unit_id = 'e89d1870-c4d1-5692-923d-5e357ae8218e', position = 16 where id = 'e97d5208-f449-5970-955a-522c208b80d6'; -- hace mucho
update public.forms set unit_id = 'b27a8863-2d09-52bd-992f-2a73710c019d', position = 7 where id = 'd1c90756-0e01-58bd-b83a-225bbc5ff843'; -- sigue
update public.forms set unit_id = '53eebe4b-3a77-563a-84b1-b0ae2a42641c', position = 12 where id = '3fdadca8-b6af-5083-9c60-d73ef93d9639'; -- dejé
update public.forms set unit_id = '53eebe4b-3a77-563a-84b1-b0ae2a42641c', position = 13 where id = 'b33fb42a-1e52-53f8-972a-2ea8210b0a35'; -- dejaste
update public.forms set unit_id = 'e89d1870-c4d1-5692-923d-5e357ae8218e', position = 17 where id = '36123aa8-158f-55a7-91f9-421c8a1ddfd4'; -- hace poco
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 12 where id = '707d1312-772e-5026-9249-df86c9f78c60'; -- volví a
update public.forms set unit_id = '17f201ba-038f-5447-a92b-ea8274de3421', position = 13 where id = 'b6dd15f8-3f1d-54da-9530-f0ac8d07bfda'; -- vuelvo a
update public.forms set unit_id = '6ec21cf5-83ce-55f4-a07c-355a8fb995bb', position = 7 where id = '017e7626-e308-5fc5-87d5-49cfb4bef41e'; -- me importa
update public.forms set unit_id = '6ec21cf5-83ce-55f4-a07c-355a8fb995bb', position = 8 where id = 'c1b797d8-3bd7-5775-878f-484495dbda20'; -- importa
update public.forms set unit_id = '13fec277-30b8-5bdb-9718-e682351abfd9', position = 21 where id = '609a55b9-4e9d-5a72-8520-ce17e937dd86'; -- color
update public.forms set unit_id = '13fec277-30b8-5bdb-9718-e682351abfd9', position = 22 where id = '6b2dbdc0-407e-5c39-adde-98352fd5f7a0'; -- colores
update public.forms set unit_id = '30394d47-559d-52eb-9c24-d6a8bbaeba36', position = 13 where id = '4dba679f-4d7e-5b66-954a-424e4910ea88'; -- mascota
update public.forms set unit_id = '30394d47-559d-52eb-9c24-d6a8bbaeba36', position = 14 where id = '806a7bc8-23ef-58ad-aeff-460417c9901d'; -- mascotas
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 10 where id = '71f70c37-d339-5c9f-9960-50b79d15d28e'; -- chiste
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 11 where id = '2c9616ee-1b05-5dc7-9114-0675d09a8cbf'; -- chistes
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 12 where id = 'e3d0dbea-2113-5689-b172-43942d0a457e'; -- gracioso
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 13 where id = '79055de5-1da8-5979-b910-b7c7689e4c89'; -- graciosa
update public.forms set unit_id = 'cc075128-b483-5ba0-a24a-485bd1dc71fa', position = 3 where id = '354704f8-a0ee-5375-a680-b7e51fabecd0'; -- tomar el pelo
update public.forms set unit_id = 'cc075128-b483-5ba0-a24a-485bd1dc71fa', position = 4 where id = '13819e77-49be-5c28-80f1-a19b6a0fbe0a'; -- tomando el pelo
update public.forms set unit_id = 'cc075128-b483-5ba0-a24a-485bd1dc71fa', position = 5 where id = '359d50d7-4cb6-50c2-bf33-ffabd59fc99d'; -- jodiendo
update public.forms set unit_id = 'cc075128-b483-5ba0-a24a-485bd1dc71fa', position = 6 where id = '447ee8f3-40b8-59c7-82c7-d19647cd7869'; -- broma
update public.forms set unit_id = 'bd710c94-4059-585f-a6ad-448e21cec02f', position = 21 where id = '11c68893-1f9c-59f0-8a4e-93a7c5832f97'; -- fecha
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 14 where id = 'b86dd058-33df-5f5b-9690-61c8f10c7d82'; -- me reí
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 16 where id = '5cf6d64f-ef27-5bc0-82d1-30e51b04df43'; -- nos reímos
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 15 where id = '2574fd76-b18d-50a9-baab-6922c0e0d52b'; -- reí
update public.forms set unit_id = '07ff3e13-7b95-55ab-aab7-ac48151e0d8c', position = 17 where id = 'b80e8e7c-a533-5221-a3c2-bf7a04308105'; -- reímos
