-- Re-review, last content step: copied or replaced practice lines leave now that new ones exist, and textbook groups shrink
-- (the everyday form is drilled instead). A group never drops below 3 sentences here.

update public.sentences set status = 'retired', updated_at = now() where id = '07c37b27-3f26-5ac3-9743-1cadd9cd07e4' and status = 'published'; -- practica-quien-es shrink encantada: Encantada, señora, yo soy Ana, una vecina de Mati.
update public.sentences set status = 'retired', updated_at = now() where id = 'd9cdb1a9-3b3d-5338-a227-ab1f238af1a6' and status = 'published'; -- practica-quien-es shrink encantada: —Mucho gusto, soy Fede. —Encantada, yo soy Cami.
update public.sentences set status = 'retired', updated_at = now() where id = 'a283b674-e645-5231-8be4-c7c45afed82e' and status = 'published'; -- practica-quien-es shrink encantada: —Encantada, Nico. —Igualmente, Juli.
update public.sentences set status = 'retired', updated_at = now() where id = 'bbdd9aff-bf0b-50ff-9724-bf219cef2da1' and status = 'published'; -- practica-quien-es shrink encantada: Hola, encantada, soy de Montevideo.
update public.sentences set status = 'retired', updated_at = now() where id = '5bcbf7ae-52b3-5d78-8f24-d9ec1ea22fd2' and status = 'published'; -- practica-quien-es shrink encantada: Encantada, ¿y vos cómo te llamás?
update public.sentences set status = 'retired', updated_at = now() where id = 'd0955d13-d784-5b57-9f9f-c77599e860c2' and status = 'published'; -- practica-quien-es shrink encantada: Encantada, me llamo Belén.
update public.sentences set status = 'retired', updated_at = now() where id = '544c0e85-0325-58dc-a783-b2db988e873e' and status = 'published'; -- altos-y-morochos shrink casados: Somos casados y tenemos un perro.
update public.sentences set status = 'retired', updated_at = now() where id = '4d999d59-8a83-5971-bfaa-b4ac31f88760' and status = 'published'; -- practica-por-aca: Ahí está el tren.
update public.sentences set status = 'retired', updated_at = now() where id = '20f7a1de-23af-5384-b606-83bba0c7ef2f' and status = 'published'; -- practica-por-aca: ¿Hay tren a La Plata?
update public.sentences set status = 'retired', updated_at = now() where id = '36c2dfd8-42cc-5718-a3d9-6ae97fb68371' and status = 'published'; -- practica-nos-gusta: La casa está cerrada y no tengo llave.
update public.sentences set status = 'retired', updated_at = now() where id = '93f33da5-0bff-5723-9c46-56d420f8f276' and status = 'published'; -- practica-nos-gusta: ¿Qué frutas te gustan?
update public.sentences set status = 'retired', updated_at = now() where id = '8c4ee7b4-a6ec-512f-96aa-e2d2c3a3f12e' and status = 'published'; -- practica-nos-gusta: Me gustan las medialunas.
update public.sentences set status = 'retired', updated_at = now() where id = 'a2db0386-554e-5a3f-9018-99f5b61f998a' and status = 'published'; -- practica-nos-gusta: ¿Quién te ayuda?
update public.sentences set status = 'retired', updated_at = now() where id = '7570fe12-5e79-54bf-bf38-54a087c28c41' and status = 'published'; -- practica-nos-gusta: Perdón, estoy apurado.
update public.sentences set status = 'retired', updated_at = now() where id = '9fd3421e-f21a-5733-bd29-2495cfddf3bf' and status = 'published'; -- practica-nos-gusta: ¿Qué necesitás?
update public.sentences set status = 'retired', updated_at = now() where id = 'e4aa9b7d-4194-5014-a75e-d482e2c626d0' and status = 'published'; -- practica-nos-gusta: ¿Estás apurado?
update public.sentences set status = 'retired', updated_at = now() where id = 'f209a332-c0f2-5ca9-baea-0197eb03f9f1' and status = 'published'; -- es-enfermera: ¿Sos periodista?
update public.sentences set status = 'retired', updated_at = now() where id = '9d6be1aa-2ffa-58c8-be41-45e4b95eed1c' and status = 'published'; -- es-enfermera: ¿Sos ingeniero?
update public.sentences set status = 'retired', updated_at = now() where id = '701757fd-71f1-5500-8ee4-1164d073d080' and status = 'published'; -- es-enfermera: ¿Sos cocinera?
update public.sentences set status = 'retired', updated_at = now() where id = '326e0ccb-7cf8-5442-8f3e-89059a32b4af' and status = 'published'; -- es-enfermera: ¿Sos programadora?
update public.sentences set status = 'retired', updated_at = now() where id = 'c25ba46a-fe9f-50e5-a1d1-b2238e0191e4' and status = 'published'; -- es-enfermera: Soy enfermero.
update public.sentences set status = 'retired', updated_at = now() where id = '3ecee2b6-cfc3-5bfe-80bd-2180665f9469' and status = 'published'; -- es-enfermera: Soy vendedor.
update public.sentences set status = 'retired', updated_at = now() where id = '2afcd3ea-7603-5edf-99fc-00f25dd9808a' and status = 'published'; -- es-enfermera: Soy psicólogo.
update public.sentences set status = 'retired', updated_at = now() where id = 'f7e24d74-380e-5886-b8c8-5fbc3915fb15' and status = 'published'; -- practica-el-vecino: ¿Compartimos un taxi al centro?
update public.sentences set status = 'retired', updated_at = now() where id = '85649cd7-758b-5751-afae-30a89f3391ac' and status = 'published'; -- practica-el-vecino: ¿Compartimos una pizza?
update public.sentences set status = 'retired', updated_at = now() where id = '2de113a8-935b-5323-8064-2f2f996271c6' and status = 'published'; -- practica-el-vecino: ¿Leés el diario?
update public.sentences set status = 'retired', updated_at = now() where id = '71bf3762-25e2-506f-bf94-a56561a4130e' and status = 'published'; -- practica-el-vecino: ¿Qué quieren tomar?
update public.sentences set status = 'retired', updated_at = now() where id = '04b5054d-a50d-5bfd-b691-141808b2c948' and status = 'published'; -- tengo-una-reserva: La cerveza no está incluida.
update public.sentences set status = 'retired', updated_at = now() where id = '7dcca9fb-a75c-536b-a61f-deb29fa399f6' and status = 'published'; -- tengo-una-reserva: La gaseosa está incluida, pero la cerveza se paga.
update public.sentences set status = 'retired', updated_at = now() where id = '054bbd66-b34c-570c-bb9e-e9376540680b' and status = 'published'; -- practica-a-la-vuelta: ¿Preferís café o té?
update public.sentences set status = 'retired', updated_at = now() where id = '5c6ec9db-0969-5043-b206-019420c56cf2' and status = 'published'; -- practica-a-la-vuelta: ¿Qué preferís, pizza o empanadas?
update public.sentences set status = 'retired', updated_at = now() where id = 'cec99187-dc9a-5e0c-9046-914f574726c2' and status = 'published'; -- practica-a-la-vuelta: Vuelvo en cinco minutos.
update public.sentences set status = 'retired', updated_at = now() where id = '2106d4f8-c696-57c0-8f70-b46cba372af8' and status = 'published'; -- practica-a-la-vuelta: Vivo enfrente.
update public.sentences set status = 'retired', updated_at = now() where id = '48e7eb63-5326-5eb4-bc09-2b4bbc021ad1' and status = 'published'; -- practica-a-la-vuelta: La farmacia está en la vereda de enfrente.
update public.sentences set status = 'retired', updated_at = now() where id = '03f0baf2-dea5-5a94-9765-4667540aad76' and status = 'published'; -- practica-a-la-vuelta: Nos vemos al mediodía.
update public.sentences set status = 'retired', updated_at = now() where id = '857bb535-e81d-5048-b37b-e0001122b2aa' and status = 'published'; -- practica-a-la-vuelta: ¿Hoy podés salir?
update public.sentences set status = 'retired', updated_at = now() where id = '51d3342a-6e7c-52a9-8943-7313ae02ccb3' and status = 'published'; -- el-cumple: —¿La invitada es tu prima? —No, es mi vecina.
update public.sentences set status = 'retired', updated_at = now() where id = '87cd75d2-ba2d-5efa-81fc-05a8080a0bcd' and status = 'published'; -- el-cumple: ¿Tu invitada quiere algo para tomar?
update public.sentences set status = 'retired', updated_at = now() where id = '10a2e522-b36f-5d72-ac8b-12a3a9954d09' and status = 'published'; -- el-cumple: —¿Quién es tu invitado? —Es mi primo.
update public.sentences set status = 'retired', updated_at = now() where id = '62ed3b7a-990d-59b9-a635-3eb0340548a7' and status = 'published'; -- te-llame: Recibí tu audio, pero no entendí nada.
update public.sentences set status = 'retired', updated_at = now() where id = 'c1caf4df-ee91-5f83-af21-90bfe96051f4' and status = 'published'; -- te-llame: Recibí tu mensaje.
update public.sentences set status = 'retired', updated_at = now() where id = '4803f7a6-837d-5c50-abc9-4c1980b9b078' and status = 'published'; -- te-llame shrink recibí: Recibí la foto, ¡está lindísima!
update public.sentences set status = 'retired', updated_at = now() where id = '7d836c06-f2ad-530e-8fbd-4052a64c8822' and status = 'published'; -- te-llame shrink recibiste: ¿Recibiste el mensaje que te mandé?
update public.sentences set status = 'retired', updated_at = now() where id = 'd437efe6-9ba4-5855-b2fd-0fc0ffd72071' and status = 'published'; -- practica-las-vacaciones: Recibí un mensaje de Sofi.
update public.sentences set status = 'retired', updated_at = now() where id = 'ef3eedc4-389d-5ced-aa56-d74e8aa873a5' and status = 'published'; -- practica-las-vacaciones: —¿Recibiste las fotos? —Sí, las recibí.
update public.sentences set status = 'retired', updated_at = now() where id = '29a77e99-8871-56bd-b41b-8c4f3a1d6e7b' and status = 'published'; -- cuando-era-chico shrink escuelas: Mi colegio era más lindo que las escuelas del centro.
update public.sentences set status = 'retired', updated_at = now() where id = 'c5edb2d3-1bab-598c-8b4d-e71bc8028db3' and status = 'published'; -- cuando-era-chico shrink escuelas: Mi abuela era profesora en dos escuelas del barrio.
update public.sentences set status = 'retired', updated_at = now() where id = '5e5c364b-16c8-57a5-a3ed-a0dd2c9362a3' and status = 'published'; -- sono-el-timbre: Caminaba con Pablo cuando sonó mi celu.
update public.sentences set status = 'retired', updated_at = now() where id = '785628ee-79f4-5e5f-b860-1f990338db42' and status = 'published'; -- sono-el-timbre: Caminaba por la plaza cuando vi a Santi.
update public.sentences set status = 'retired', updated_at = now() where id = 'e9867edb-61e3-5440-b522-d135f4994196' and status = 'published'; -- sono-el-timbre shrink caminaba: Ana caminaba despacio porque estaba cansada.
update public.sentences set status = 'retired', updated_at = now() where id = '125d9769-bbef-569c-95b1-c5b7cc1c97ec' and status = 'published'; -- el-partido: Ahora gano mejor y puedo viajar más.
update public.sentences set status = 'retired', updated_at = now() where id = '5bdbe32b-468d-5140-ae94-546cb1822e0b' and status = 'published'; -- tipo-ocho shrink puertas: Abren las puertas tipo nueve, ¿nos encontramos antes?
update public.sentences set status = 'retired', updated_at = now() where id = '7d3960de-386e-5c1e-9fec-c3b7f947f818' and status = 'published'; -- tipo-ocho shrink puertas: El boliche tiene dos puertas, te espero en la roja.
update public.sentences set status = 'retired', updated_at = now() where id = '66c4a21a-d7cb-5301-b447-85ed1de88816' and status = 'published'; -- tipo-ocho shrink puertas: En el recital abren las puertas tipo siete.
update public.sentences set status = 'retired', updated_at = now() where id = '44004661-4339-5a63-8fdf-a45f5d2255a0' and status = 'published'; -- la-semana-que-viene shrink pronto: Pronto vamos a tener que buscar otro departamento.
update public.sentences set status = 'retired', updated_at = now() where id = '10d1d7b9-2ca7-51d9-90b8-7e27544bbf5b' and status = 'published'; -- la-semana-que-viene shrink pronto: Seguro que pronto encontrás un depto más barato.
update public.sentences set status = 'retired', updated_at = now() where id = '5bf4e315-8456-52e3-99cf-acdd15774340' and status = 'published'; -- la-semana-que-viene shrink pronto: El médico dijo que pronto voy a estar mejor.
update public.sentences set status = 'retired', updated_at = now() where id = 'b26c6328-b9f4-565a-8824-d81d676586b2' and status = 'published'; -- la-semana-que-viene shrink pronto: Pronto mis viejos se van a vivir al sur.
update public.sentences set status = 'retired', updated_at = now() where id = '53137f9b-933a-5f24-a6ed-05226fe874a0' and status = 'published'; -- la-semana-que-viene shrink pronto: ¿Tu hermana vuelve pronto de Mendoza?
update public.sentences set status = 'retired', updated_at = now() where id = 'c060cfd3-acff-5444-bc8f-9f023600c37c' and status = 'published'; -- la-semana-que-viene shrink pronto: Pronto voy a tener laburo nuevo.
update public.sentences set status = 'retired', updated_at = now() where id = '263b10ad-37f9-57cb-bae3-83dacb0f2ede' and status = 'published'; -- la-semana-que-viene shrink pronto: Espero volver pronto a Córdoba.
update public.sentences set status = 'retired', updated_at = now() where id = '3af4f070-8c3f-51c9-bfda-7cff439cbcab' and status = 'published'; -- me-haces-un-favor: ¿Me hacés el favor de abrir la puerta?
update public.sentences set status = 'retired', updated_at = now() where id = 'd60d0251-0d03-5392-945a-8e568a35d3ba' and status = 'published'; -- a-la-mesa: Chicos, hagan la cama antes de salir.
update public.sentences set status = 'retired', updated_at = now() where id = '378d0249-eb35-54a8-9f3a-7f989169120c' and status = 'published'; -- el-tramite shrink formulario: Ya completé el formulario, ¿ahora hago la cola?
update public.sentences set status = 'retired', updated_at = now() where id = '85a05b1f-306a-5deb-a62c-4bf56399e57d' and status = 'published'; -- el-tramite shrink formulario: Mandame el formulario por mail, por favor.
update public.sentences set status = 'retired', updated_at = now() where id = 'c5c9359d-68ed-5fb2-9919-6792aac4b56b' and status = 'published'; -- el-tramite shrink formulario: Para el pasaporte hay un formulario nuevo.
update public.sentences set status = 'retired', updated_at = now() where id = '33055340-9540-5e7d-93b4-23ae006d7cb7' and status = 'published'; -- el-tramite shrink formulario: ¿Dónde hay que completar el formulario?
update public.sentences set status = 'retired', updated_at = now() where id = '5df17020-9573-5991-ac9c-7c10b478dc77' and status = 'published'; -- el-tramite shrink formulario: Tenés que completar este formulario.
update public.sentences set status = 'retired', updated_at = now() where id = '8e26143d-19b9-5b66-a6db-a86de4086a72' and status = 'published'; -- el-tramite shrink pasaporte: ¿Vas a viajar con el DNI o con el pasaporte?
update public.sentences set status = 'retired', updated_at = now() where id = '29f91099-b0ff-5022-918b-108eb831d9da' and status = 'published'; -- el-tramite shrink pasaporte: Tengo que sacar turno para el pasaporte.
update public.sentences set status = 'retired', updated_at = now() where id = '05cf3f19-7daa-5736-8da5-8d93485edbcb' and status = 'published'; -- el-tramite shrink pasaporte: Necesito el pasaporte para viajar.
update public.sentences set status = 'retired', updated_at = now() where id = '648874d8-52a1-56a7-8a99-fd155b61e6c1' and status = 'published'; -- se-aceptan-tarjetas: Acá se permite estacionar solo los domingos.
update public.sentences set status = 'retired', updated_at = now() where id = '1ed1234b-8e0d-59d6-a5dd-33752ccb1c47' and status = 'published'; -- se-aceptan-tarjetas: En la pileta no se permite comer.
update public.sentences set status = 'retired', updated_at = now() where id = '93fafbac-97ee-5ece-9dcf-19e29b11d7a2' and status = 'published'; -- se-aceptan-tarjetas shrink se prohíbe: Mirá el cartel: se prohíbe entrar con mascotas.
update public.sentences set status = 'retired', updated_at = now() where id = '8b3c18ee-2a40-5f94-be1e-1f6404978114' and status = 'published'; -- se-aceptan-tarjetas shrink se permite: En la puerta dice: no se permite estacionar bicis.
update public.sentences set status = 'retired', updated_at = now() where id = '3f409997-1b8e-50d3-9605-82bd7b68d61d' and status = 'published'; -- se-aceptan-tarjetas shrink recompensa: Con esa recompensa, todo el barrio busca al gato.
update public.sentences set status = 'retired', updated_at = now() where id = 'b1d35de3-bf11-5363-916a-d8baf8aaa9c1' and status = 'published'; -- se-aceptan-tarjetas shrink recompensa: La dueña del gato me dio la recompensa.
update public.sentences set status = 'retired', updated_at = now() where id = '4ee1c766-39f5-543c-befd-a14a780d2ace' and status = 'published'; -- cien-gramos-de-jamon: ¿La zanahoria está cocida?
update public.sentences set status = 'retired', updated_at = now() where id = 'ec2bb3d0-6c8d-5e11-bcea-b6d41d167108' and status = 'published'; -- practica-la-feria: Cuando fui a Córdoba, llovió todos los días.
update public.sentences set status = 'retired', updated_at = now() where id = 'eeafae47-2ab3-503c-b630-c0eee03c222e' and status = 'published'; -- practica-la-feria: Fui a Mendoza de vacaciones con mi novia.
update public.sentences set status = 'retired', updated_at = now() where id = 'f803dec2-2679-5cb0-b47b-bb5f87ac057c' and status = 'published'; -- el-celu: ¿Te quedaste sin plata en la SUBE?
update public.sentences set status = 'retired', updated_at = now() where id = 'ec1af3d7-df1d-5644-8b56-930ba6742ee7' and status = 'published'; -- el-celu: Me quedé sin plata en la SUBE.
update public.sentences set status = 'retired', updated_at = now() where id = '18ee0f41-c75a-56c7-aaab-5b757ca1cfd3' and status = 'published'; -- te-lo-devuelvo shrink cargadores: ¿Me devolvés los cargadores antes del viaje?
update public.sentences set status = 'retired', updated_at = now() where id = 'c419fc7f-5e2c-5d26-9d84-74e8f80176ee' and status = 'published'; -- te-lo-devuelvo shrink cargadores: Te devuelvo los cargadores mañana, ¿dale?
update public.sentences set status = 'retired', updated_at = now() where id = '99e270c2-0a02-5a82-a3c1-440441227334' and status = 'published'; -- me-contrataron shrink cliente: El cliente de la mesa cinco pidió otro café.
update public.sentences set status = 'retired', updated_at = now() where id = 'b1088961-214e-5ee6-a2f6-bc55dde432ec' and status = 'published'; -- me-contrataron shrink clientes: Me contrataron para buscar clientes en Uruguay.
update public.sentences set status = 'retired', updated_at = now() where id = '9195abb2-8395-5359-bcc6-ae0a78735e46' and status = 'published'; -- me-contrataron shrink clientes: ¿Les mandaste el mail a los clientes?
update public.sentences set status = 'retired', updated_at = now() where id = '60a39cfe-63ca-5a91-a799-0380775837cc' and status = 'published'; -- me-contrataron shrink clientes: Hablo con clientes todo el día.
update public.sentences set status = 'retired', updated_at = now() where id = 'f241c2e4-9537-5b81-9186-b54fe750d556' and status = 'published'; -- me-contrataron shrink clientes: Perdimos dos clientes este mes.
update public.sentences set status = 'retired', updated_at = now() where id = 'd7f8deb2-1743-58c3-91ec-c6c92a29997f' and status = 'published'; -- se-caso shrink se comprometieron: Se comprometieron el sábado y el casamiento es en marzo.
update public.sentences set status = 'retired', updated_at = now() where id = '4094b209-aa79-5717-8342-104e9548851f' and status = 'published'; -- se-caso shrink se comprometieron: Se comprometieron en Navidad, con anillo y todo.
update public.sentences set status = 'retired', updated_at = now() where id = '958f7203-8d69-588b-8a6b-46674fb61c1b' and status = 'published'; -- se-caso shrink se comprometieron: ¿Se comprometieron y no me contaste nada?
update public.sentences set status = 'retired', updated_at = now() where id = '64492dbc-245e-5c8f-852e-9adb7afba55f' and status = 'published'; -- se-caso shrink se comprometieron: ¡Nico y Belén se comprometieron!
update public.sentences set status = 'retired', updated_at = now() where id = 'e7339864-de47-53aa-a7d2-656c16dd1016' and status = 'published'; -- se-caso shrink se comprometieron: ¡Se comprometieron en Bariloche!
update public.sentences set status = 'retired', updated_at = now() where id = '60cea573-16bf-5092-be2f-6a0b03c1f5e7' and status = 'published'; -- se-caso shrink se comprometieron: Se comprometieron en la playa.
update public.sentences set status = 'retired', updated_at = now() where id = 'cf8d6c1f-a133-5129-8c7e-f9cb940e2773' and status = 'published'; -- donde-estara: ¿Juli? Estará laburando.
update public.sentences set status = 'retired', updated_at = now() where id = '5ba47a1c-5f85-5e1e-abf3-fb074b6db37c' and status = 'published'; -- donde-estara: Estará cansado.
update public.sentences set status = 'retired', updated_at = now() where id = '0c17af4b-e4e1-5de2-bea3-df8b6f066108' and status = 'published'; -- donde-estara: Estará en el laburo.
update public.sentences set status = 'retired', updated_at = now() where id = '662e0a4a-d3f3-5d32-a029-acdddf7d75b3' and status = 'published'; -- donde-estara: Lucía no me habla desde ayer, estará enojada.
update public.sentences set status = 'retired', updated_at = now() where id = 'b6083faa-78e3-5f1a-8fdf-d7b529a95014' and status = 'published'; -- donde-estara: Mi celu estará en la cocina.
update public.sentences set status = 'retired', updated_at = now() where id = 'b47cd386-2491-5154-92e3-99cdedd59668' and status = 'published'; -- donde-estara: Nico todavía no llegó, estará en el bondi.
update public.sentences set status = 'retired', updated_at = now() where id = 'a54d3768-8413-5323-8882-0e3af0ad6a06' and status = 'published'; -- donde-estara: Santi hoy no viene, estará enfermo.
update public.sentences set status = 'retired', updated_at = now() where id = '21208a13-ba00-50fa-ad70-166937cf2a80' and status = 'published'; -- donde-estara: Fede no me llama, tendrá el celu sin batería.
update public.sentences set status = 'retired', updated_at = now() where id = 'edf154b9-58cc-580c-a01d-e5f1a21ce20e' and status = 'published'; -- donde-estara: Fede tendrá las llaves.
update public.sentences set status = 'retired', updated_at = now() where id = '9228e89f-3b83-552a-83c0-7e19bae71cf2' and status = 'published'; -- donde-estara: Rocío tendrá mucho laburo hoy.
update public.sentences set status = 'retired', updated_at = now() where id = 'b419711a-7871-542e-86c8-1038652cc9d7' and status = 'published'; -- donde-estara: Tendrá fiebre.
update public.sentences set status = 'retired', updated_at = now() where id = 'f4104cf0-c2db-5376-8432-1b45c9efb9a0' and status = 'published'; -- donde-estara: Tendrá tipo cuarenta años.
update public.sentences set status = 'retired', updated_at = now() where id = 'f5abb726-d682-5402-a051-4e870806698d' and status = 'published'; -- donde-estara: Por cómo habla, será porteño.
update public.sentences set status = 'retired', updated_at = now() where id = '914a38b4-8c61-5fcb-924d-95234236d1a3' and status = 'published'; -- donde-estara: Será caro, ¿no?
update public.sentences set status = 'retired', updated_at = now() where id = '664d8369-84f5-54ae-86a2-6f60dabca357' and status = 'published'; -- donde-estara: Será el viento.
update public.sentences set status = 'retired', updated_at = now() where id = 'dfa58cb8-b68f-5d7f-afaa-a265ad16cb4f' and status = 'published'; -- donde-estara: Es viernes, habrá muchos pibes en el boliche.
update public.sentences set status = 'retired', updated_at = now() where id = '40f57c4e-504b-56a7-93bc-7966b155f902' and status = 'published'; -- donde-estara: Habrá leche en la heladera.
update public.sentences set status = 'retired', updated_at = now() where id = '761c1161-3595-56ee-93a4-1a8a76167c10' and status = 'published'; -- donde-estara: Habrá una farmacia cerca.
update public.sentences set status = 'retired', updated_at = now() where id = '39574860-7bfa-51ef-93ff-625bb83d8b3a' and status = 'published'; -- donde-estara: El bondi vendrá lleno a esta hora.
update public.sentences set status = 'retired', updated_at = now() where id = '2976c588-c12b-5a63-a727-073c605afc19' and status = 'published'; -- donde-estara: Esos dos serán hermanos, tienen el mismo apellido.
update public.sentences set status = 'retired', updated_at = now() where id = 'd375f465-92a4-5aab-9529-f5a67551f533' and status = 'published'; -- donde-estara: Serán las diez.
update public.sentences set status = 'retired', updated_at = now() where id = 'f9376114-436d-57bb-902b-d67b4b082323' and status = 'published'; -- donde-estara: Serán las ocho, ¿no?
update public.sentences set status = 'retired', updated_at = now() where id = 'bf22ab80-95a5-535c-9468-c5ebee181737' and status = 'published'; -- donde-estara: ¿Y los pibes? Estarán en la cancha.
update public.sentences set status = 'retired', updated_at = now() where id = 'be5cfedb-839d-56d5-b8f4-5c07dd15f337' and status = 'published'; -- donde-estara: La verdulería está cerrada, estarán de vacaciones.
update public.sentences set status = 'retired', updated_at = now() where id = 'f4422302-5c85-5ec9-804f-62cf00c5f65f' and status = 'published'; -- donde-estara: Lucía y su novio se pelearon, estarán tristes.
update public.sentences set status = 'retired', updated_at = now() where id = '270911e5-34a2-54c8-8f16-4460861b899c' and status = 'published'; -- me-siento-mal shrink pastilla: Me duele la muela. ¿Tenés una pastilla?
update public.sentences set status = 'retired', updated_at = now() where id = '41b131c9-c877-547f-b27e-44ecaddb3b5e' and status = 'published'; -- me-siento-mal shrink pastilla: Tomá la pastilla con agua, no con mate.
update public.sentences set status = 'retired', updated_at = now() where id = '2b4ebc9d-b4a8-5b6d-83b0-860dfec1d396' and status = 'published'; -- me-siento-mal shrink pastilla: ¿Tenés una pastilla para la cabeza?
update public.sentences set status = 'retired', updated_at = now() where id = 'e63aefd8-9987-588b-80f7-d166821104d7' and status = 'published'; -- me-siento-mal shrink pastilla: Tomá una pastilla cada ocho horas.
update public.sentences set status = 'retired', updated_at = now() where id = '25939c88-3905-5d62-95f1-9e3670200986' and status = 'published'; -- me-siento-mal shrink pastilla: Esta pastilla es re amarga.
update public.sentences set status = 'retired', updated_at = now() where id = 'd58abf4f-48bc-53f2-99ad-5b1986985e84' and status = 'published'; -- me-siento-mal shrink pastillas: ¿Me comprás las pastillas si vas a la farmacia?
update public.sentences set status = 'retired', updated_at = now() where id = '53f8a54f-5769-54e2-be89-771258774385' and status = 'published'; -- me-siento-mal shrink pastillas: Para estas pastillas necesitás receta.
update public.sentences set status = 'retired', updated_at = now() where id = '814ae2a6-c230-5628-8617-6c9005b0fd43' and status = 'published'; -- me-siento-mal shrink pastillas: Compré pastillas en la farmacia.
update public.sentences set status = 'retired', updated_at = now() where id = 'af357b9a-d355-55fd-b671-59fd40e9d127' and status = 'published'; -- me-siento-mal shrink pastillas: Las pastillas están en el baño.
update public.sentences set status = 'retired', updated_at = now() where id = '60c8972e-6c58-59d3-b841-8cd17ebc0b30' and status = 'published'; -- me-siento-mal shrink pastillas: ¿Dónde están las pastillas?
update public.sentences set status = 'retired', updated_at = now() where id = '5f5c928b-7e6b-527a-aead-726e407fa273' and status = 'published'; -- es-medio-vago shrink macanudo: Es serio, pero cuando lo conocés es macanudo.
update public.sentences set status = 'retired', updated_at = now() where id = '23412b19-5df7-514c-80cd-f8a107f4bfea' and status = 'published'; -- es-medio-vago shrink macanuda: Tu abuela es macanuda; nos hizo ñoquis a todos.
update public.sentences set status = 'retired', updated_at = now() where id = '1c667d95-1499-5352-86a6-c1a138a4334a' and status = 'published'; -- que-te-vaya-bien: ¡Buen día!
update public.sentences set status = 'retired', updated_at = now() where id = '5c7bad49-b54f-519b-8318-8910c63aa259' and status = 'published'; -- practica-cuando-vuelvas: No me esperes, llego tarde.
update public.sentences set status = 'retired', updated_at = now() where id = '8919f34a-c825-5e1d-8ae4-de49d2a4fab2' and status = 'published'; -- practica-cuando-vuelvas: ¿Qué querés que hagamos?
update public.sentences set status = 'retired', updated_at = now() where id = 'b07ab527-2878-5ccc-82ad-4715fc69620d' and status = 'published'; -- practica-cuando-vuelvas: Hagamos un asado el sábado.
update public.sentences set status = 'retired', updated_at = now() where id = 'f309dc9a-ee0b-5f0b-abc7-d6b478e6525c' and status = 'published'; -- practica-cuando-vuelvas: Vení cuando quieras.
update public.sentences set status = 'retired', updated_at = now() where id = '3fe8c7c8-8196-535d-9e1c-c2ac2d9dc759' and status = 'published'; -- practica-cuando-vuelvas: ¡Que te diviertas!
update public.sentences set status = 'retired', updated_at = now() where id = 'dbb460c8-a78a-5eba-9bf3-7cc9fa5c266f' and status = 'published'; -- practica-cuando-vuelvas: Mi abuela quiere que la ayudes con el celular.
update public.sentences set status = 'retired', updated_at = now() where id = '7fad447b-3696-5d4c-b4b7-abe29393b5cd' and status = 'published'; -- practica-cuando-vuelvas: Avisame cuando vuelvas.
update public.sentences set status = 'retired', updated_at = now() where id = '95d73da3-05f4-5a23-b583-7fbf7b48ce91' and status = 'published'; -- practica-cuando-vuelvas: Esperá hasta que llegue Juan.
update public.sentences set status = 'retired', updated_at = now() where id = 'a2652766-a2e6-5793-aa2d-bbe890b38017' and status = 'published'; -- practica-te-aconsejo: No le cuentes a nadie.
update public.sentences set status = 'retired', updated_at = now() where id = '58c85770-a51c-5fc1-b185-2c20851320ce' and status = 'published'; -- practica-te-aconsejo: Mejor no le cuentes a tu jefe.
update public.sentences set status = 'retired', updated_at = now() where id = 'fc387d2c-b64b-5eb1-87ee-78ac330f7639' and status = 'published'; -- practica-te-aconsejo: No dejes la puerta abierta.
update public.sentences set status = 'retired', updated_at = now() where id = '3199b2e8-349b-5bb9-90e6-a52ae53a9f69' and status = 'published'; -- practica-te-aconsejo: No te vayas todavía.
update public.sentences set status = 'retired', updated_at = now() where id = '7736dcf2-29c6-5c97-aedc-682239ac5e41' and status = 'published'; -- practica-te-aconsejo: No lleves mucha plata.
update public.sentences set status = 'retired', updated_at = now() where id = 'c4bb081a-32cf-5fc9-8360-951b9c761dff' and status = 'published'; -- practica-te-aconsejo: No seas así.
update public.sentences set status = 'retired', updated_at = now() where id = '8d242032-852c-5290-be2b-ce4c9fc2e07e' and status = 'published'; -- practica-te-aconsejo: No creo que sean de acá.
update public.sentences set status = 'retired', updated_at = now() where id = '245a183c-aff4-5a8a-a758-2eddd3b8de32' and status = 'published'; -- practica-te-aconsejo: Puede ser que tengas razón.
update public.sentences set status = 'retired', updated_at = now() where id = '91af7ba1-5027-5030-8e6f-a342622cf943' and status = 'published'; -- practica-te-aconsejo: No dejes el celular en la mesa.
update public.sentences set status = 'retired', updated_at = now() where id = '81a81909-f561-50a3-9027-28eb99a746e0' and status = 'published'; -- practica-es-un-afano: Me preocupa el examen.
update public.sentences set status = 'retired', updated_at = now() where id = '342f80f1-bfbd-57b3-9a52-deddea183bcf' and status = 'published'; -- practica-es-un-afano: ¡Qué lástima que vivas tan lejos!
update public.sentences set status = 'retired', updated_at = now() where id = '1bc2f50d-180f-5e92-9ddd-61872fe54cb8' and status = 'published'; -- practica-es-un-afano: Perdón, no me di cuenta.
update public.sentences set status = 'retired', updated_at = now() where id = 'e5a7310f-8040-5b4f-82ca-9a51318c81b9' and status = 'published'; -- practica-es-un-afano: ¡Qué bueno que estemos de vacaciones!
update public.sentences set status = 'retired', updated_at = now() where id = '877b14df-4065-53a1-8fbb-520f7a7f9f28' and status = 'published'; -- practica-es-un-afano: Repetime qué te dijo el médico.
update public.sentences set status = 'retired', updated_at = now() where id = '894575f0-5a2e-51c5-83f4-e9ee4a8d9cf4' and status = 'published'; -- practica-es-un-afano: Recién me di cuenta.
update public.sentences set status = 'retired', updated_at = now() where id = '0b428432-18b6-54c9-bd5c-4bd3d16ba3a4' and status = 'published'; -- practica-es-un-afano shrink conocí: ¿Sabés dónde la conocí? En el subte.
update public.sentences set status = 'retired', updated_at = now() where id = '51ddc2d4-ac3e-5623-8d39-c7dd8c344fc8' and status = 'published'; -- practica-es-un-afano shrink conocí: Cuando la conocí, vivía en Córdoba.
update public.sentences set status = 'retired', updated_at = now() where id = '906ff119-6ea4-52c9-85f8-3f790aeebfb8' and status = 'published'; -- practica-es-un-afano shrink conocí: Conocí Montevideo el verano pasado.
update public.sentences set status = 'retired', updated_at = now() where id = '590b90fd-256d-5bff-89af-4777bb36b2c5' and status = 'published'; -- practica-es-un-afano shrink conocí: A Diego lo conocí en un asado.
update public.sentences set status = 'retired', updated_at = now() where id = '15ce8820-d0ad-5b2a-b21b-c1f164a31f9d' and status = 'published'; -- practica-es-un-afano shrink me enojé: Me enojé porque llegaste tarde otra vez.
update public.sentences set status = 'retired', updated_at = now() where id = '55b58bb0-39c7-5307-af9a-632d2986c9db' and status = 'published'; -- practica-es-un-afano shrink me enojé: Me enojé con el encargado por el ruido.
update public.sentences set status = 'retired', updated_at = now() where id = '4dd0439a-8941-5a32-9b36-b2a9eedf4f68' and status = 'published'; -- practica-es-un-afano shrink me enojé: Me enojé tanto que me fui del bar.
update public.sentences set status = 'retired', updated_at = now() where id = '24f7602a-79ea-5779-9bfc-aa878cc62bbc' and status = 'published'; -- practica-es-un-afano shrink me enojé: Cuando vi la cuenta, me enojé.
update public.sentences set status = 'retired', updated_at = now() where id = 'eae59f0c-ab7d-5a25-87ee-af22700131b1' and status = 'published'; -- cuidate shrink dormiste: —¿Dormiste bien? —No, me duele la cabeza.
update public.sentences set status = 'retired', updated_at = now() where id = '0c33df47-66bd-5b5a-9940-2a7cd824e471' and status = 'published'; -- cuidate shrink dormiste: —¿Dormiste bien? —Sí, re bien.
update public.sentences set status = 'retired', updated_at = now() where id = 'd5f51c2f-23fd-5aab-a9c6-aeeed81adc8f' and status = 'published'; -- cuidate shrink dormiste: Hola, ¿dormiste algo?
update public.sentences set status = 'retired', updated_at = now() where id = 'd53972d0-125f-57f4-8e21-ccad2d26989f' and status = 'published'; -- como-no-dona-rosa shrink con permiso: Con permiso, vecino, paso con el perro.
update public.sentences set status = 'retired', updated_at = now() where id = 'ad7e2452-f012-5167-87a3-a9088e950ac4' and status = 'published'; -- como-no-dona-rosa shrink con permiso: Con permiso, querida, ¿me dejás pasar?
update public.sentences set status = 'retired', updated_at = now() where id = 'fa89f929-9dda-5337-9d6b-a4fc4ee34a53' and status = 'published'; -- como-no-dona-rosa shrink con permiso: Entró sin decir con permiso.
update public.sentences set status = 'retired', updated_at = now() where id = 'ae1d969a-65fa-5aad-a2fe-4f45a862aad4' and status = 'published'; -- practica-si-ganara: ¿Belén no tenía clase hoy?
update public.sentences set status = 'retired', updated_at = now() where id = 'c33db60b-3e60-5ab1-885b-a00ada3ccfc9' and status = 'published'; -- practica-si-ganara: De chico tenía un perro.
update public.sentences set status = 'retired', updated_at = now() where id = 'f7421daf-5016-5470-8c60-5465a3ed0306' and status = 'published'; -- practica-si-ganara: Mi abuelo tenía una panadería en el barrio.
update public.sentences set status = 'retired', updated_at = now() where id = '6eef0183-80fd-5575-9288-e91cddc3589b' and status = 'published'; -- practica-si-ganara: Hoy preferiría no salir.
update public.sentences set status = 'retired', updated_at = now() where id = '56d54cea-cf56-57d6-8e4a-3341c110f171' and status = 'published'; -- practica-si-ganara: ¿No tendrías que estar laburando?
update public.sentences set status = 'retired', updated_at = now() where id = 'ee6338b0-3cf1-58b0-be18-eff2be2cf52d' and status = 'published'; -- practica-si-ganara: Si no fuera tan caro, iríamos más al teatro.
update public.sentences set status = 'retired', updated_at = now() where id = '41178205-f95d-5a01-bb1d-f54b79e12870' and status = 'published'; -- practica-si-ganara: Si el equipo ganara el domingo, iríamos a festejar.
update public.sentences set status = 'retired', updated_at = now() where id = '37d42e86-3bf0-58c0-b39b-5aa23ed5f324' and status = 'published'; -- practica-si-ganara: Si viviera sola, tendría un perro.
update public.sentences set status = 'retired', updated_at = now() where id = '65553c50-532c-5a87-9f3c-f617bb5c4a35' and status = 'published'; -- practica-si-ganara: En tu lugar, no diría nada.
update public.sentences set status = 'retired', updated_at = now() where id = 'deeb045b-e195-509a-8efc-e2f6d3ef44ef' and status = 'published'; -- practica-si-ganara: Yo en tu lugar, iría a la guardia.
update public.sentences set status = 'retired', updated_at = now() where id = 'd311f2bf-ce39-5c55-b772-780b95f2caf4' and status = 'published'; -- en-cuotas: Tengo veinte dólares.
update public.sentences set status = 'retired', updated_at = now() where id = 'a7505890-cf85-58d8-95ff-67d7acd680a4' and status = 'published'; -- en-cuotas: Son cincuenta dólares.
update public.sentences set status = 'retired', updated_at = now() where id = '8c5e3365-2020-5859-81e5-5251c468773e' and status = 'published'; -- en-cuotas: Gasté poco.
update public.sentences set status = 'retired', updated_at = now() where id = 'ebf034ef-6d90-5b3a-953e-b7a63a8bafbe' and status = 'published'; -- en-cuotas: Gasté un montón.
update public.sentences set status = 'retired', updated_at = now() where id = '54b581a1-f283-5fa6-867d-ca5f3b002a2c' and status = 'published'; -- en-cuotas: Tengo que ahorrar.
update public.sentences set status = 'retired', updated_at = now() where id = '6cb5970b-458f-51b6-ae86-fba7d9aaee97' and status = 'published'; -- en-cuotas: Gasto mucho en café.
update public.sentences set status = 'retired', updated_at = now() where id = '522bccbe-44de-5d2f-abef-ef6e3ea8e84f' and status = 'published'; -- me-contaron: La noticia de la radio no era cierta.
update public.sentences set status = 'retired', updated_at = now() where id = '8f0b4411-a407-5efb-8639-f3cd51c2668c' and status = 'published'; -- me-contaron: ¿Será cierta la noticia?
update public.sentences set status = 'retired', updated_at = now() where id = '08960773-dea4-5075-9d99-c52c080fba94' and status = 'published'; -- practica-a-medias: Ayer manejé hasta Rosario.
update public.sentences set status = 'retired', updated_at = now() where id = '60b19a7b-9309-5816-8249-1a1a785a7784' and status = 'published'; -- practica-a-medias: Manejé toda la noche.
update public.sentences set status = 'retired', updated_at = now() where id = 'f3a63e1e-9a79-558f-8af3-885c9b382f83' and status = 'published'; -- practica-a-medias: Me debés cinco mil pesos.
update public.sentences set status = 'retired', updated_at = now() where id = '2c69952d-d82d-5141-a82e-ae46a5afd51e' and status = 'published'; -- practica-a-medias: ¿Te alcanza con diez mil?
update public.sentences set status = 'retired', updated_at = now() where id = '1aa15dad-1d5d-5ea5-942a-a7880291d5c9' and status = 'published'; -- practica-a-medias: La nafta está re cara.
update public.sentences set status = 'retired', updated_at = now() where id = 'de78f988-710f-50ca-8dc4-2381d5f2c199' and status = 'published'; -- practica-a-medias: Hoy cobré el sueldo.
update public.sentences set status = 'retired', updated_at = now() where id = '4ab0607d-372d-5d4e-87ed-75021510612e' and status = 'published'; -- practica-a-medias: Me contaron que te mudaste.
update public.sentences set status = 'retired', updated_at = now() where id = '7f254927-67ba-51cc-aa19-6e5e7cec1698' and status = 'published'; -- practica-a-medias: ¿Vamos a medias?
update public.sentences set status = 'retired', updated_at = now() where id = 'ac314420-7569-5730-b30d-fe9fdc34d85a' and status = 'published'; -- practica-a-medias: Si no te alcanza, avisame.
update public.sentences set status = 'retired', updated_at = now() where id = 'd46e2c01-f60b-5148-8575-81a7c90efa96' and status = 'published'; -- practica-a-medias: Cargá nafta antes de salir.
update public.sentences set status = 'retired', updated_at = now() where id = '4d4c8812-ad5d-5246-8ae0-50dacb6e96dd' and status = 'published'; -- cada-vez-mas shrink ya no: Ya no nos juntamos los viernes, qué lástima.
update public.sentences set status = 'retired', updated_at = now() where id = '7dc211d5-3dc5-5411-95d5-ba2315074de0' and status = 'published'; -- cada-vez-mas shrink ya no: Desde que me mudé, ya no veo a mis viejos.
update public.sentences set status = 'retired', updated_at = now() where id = 'b2e4730a-af35-56ae-9122-36a7a68f88fc' and status = 'published'; -- cada-vez-mas shrink ya no: Antes jugaba al fútbol, ahora ya no juego.
update public.sentences set status = 'retired', updated_at = now() where id = 'ed395808-b92a-5c1e-90f4-857727a6e44e' and status = 'published'; -- cada-vez-mas shrink ya no: Me crié acá, pero ya no conozco a nadie.
update public.sentences set status = 'retired', updated_at = now() where id = '558b7b62-46a2-57e0-b683-12390b526d20' and status = 'published'; -- cada-vez-mas shrink ya no: Antes tomaba mate amargo, ahora ya no.
update public.sentences set status = 'retired', updated_at = now() where id = 'e06f4c40-9573-5e33-b480-ea4b6ee4d4ba' and status = 'published'; -- cada-vez-mas shrink ya no: Antes éramos vecinos, ahora ya no.
update public.sentences set status = 'retired', updated_at = now() where id = 'fc23fb32-eded-5266-9781-7f8b2502d8dd' and status = 'published'; -- cada-vez-mas shrink ya no: La casa donde me crié ya no está.
update public.sentences set status = 'retired', updated_at = now() where id = '2ff80139-3c7a-5fed-b94e-4323c93ed469' and status = 'published'; -- cada-vez-mas shrink ya no: Antes era barato, ahora ya no.
update public.sentences set status = 'retired', updated_at = now() where id = '06603933-db55-5818-b3e1-a03d1b7f06ac' and status = 'published'; -- cada-vez-mas shrink crecí: Donde yo crecí antes había una plaza, ahora hay edificios.
update public.sentences set status = 'retired', updated_at = now() where id = '8bd68a18-9fc7-562f-a824-f6c56fbbed70' and status = 'published'; -- cada-vez-mas shrink crecí: Crecí en esta calle, antes no había tránsito.
update public.sentences set status = 'retired', updated_at = now() where id = 'f220e081-7985-5cf3-8a53-0011643af1dd' and status = 'published'; -- cada-vez-mas shrink crecí: Mis viejos son de Mendoza, pero crecí acá.
update public.sentences set status = 'retired', updated_at = now() where id = 'cc721d3c-7887-5bc9-bfba-d3471973aeeb' and status = 'published'; -- cada-vez-mas shrink crecí: Crecí en Belgrano, ahora vivo lejos.
update public.sentences set status = 'retired', updated_at = now() where id = '24c2a61a-0e59-53f2-9aac-32cad8a92283' and status = 'published'; -- cada-vez-mas shrink crecí: Crecí acá; antes era tranquilo.
update public.sentences set status = 'retired', updated_at = now() where id = '968d401f-78f3-5979-8352-e7a1877e1cde' and status = 'published'; -- todo-aumenta shrink cobraron: En el taxi me cobraron un montón por dos cuadras.
update public.sentences set status = 'retired', updated_at = now() where id = '0e3cae9d-3b7d-5fb9-bf3e-9a3fc84f21fb' and status = 'published'; -- todo-aumenta shrink cobraron: ¿Te cobraron el mes que estuviste sin wifi?
update public.sentences set status = 'retired', updated_at = now() where id = '2c61ccf6-0107-5229-a4c3-62c777f229f4' and status = 'published'; -- todo-aumenta shrink cobraron: En el bar nos cobraron hasta el agua.
update public.sentences set status = 'retired', updated_at = now() where id = '7ac85e0a-59a5-5b93-bca5-a76da213accf' and status = 'published'; -- todo-aumenta shrink cobraron: —¿Cuánto te cobraron? —Uy, un montón.
update public.sentences set status = 'retired', updated_at = now() where id = '8c01c1d1-b3c3-55d4-9353-19bb6b4b5e66' and status = 'published'; -- todo-aumenta shrink cobraron: Me cobraron cuatro mil pesos el café.
update public.sentences set status = 'retired', updated_at = now() where id = '043dfe28-ebe1-5753-a600-faa4826b6b71' and status = 'published'; -- todo-aumenta shrink cobraron: ¿Cuánto les cobraron por la mudanza?
update public.sentences set status = 'retired', updated_at = now() where id = 'e88e94aa-30c6-5f59-a6c8-b1f2ad747482' and status = 'published'; -- todo-aumenta shrink cobraron: No anda el wifi y me cobraron igual.
update public.sentences set status = 'retired', updated_at = now() where id = '803d8a78-2c71-5a13-99ca-3866848e9fba' and status = 'published'; -- practica-me-dijo: No es tonto, es distraído.
update public.sentences set status = 'retired', updated_at = now() where id = 'f4513f57-5adf-5fb2-95d0-5572459b53ba' and status = 'published'; -- practica-me-dijo: ¿No me podías llamar?
update public.sentences set status = 'retired', updated_at = now() where id = '4fd35c1f-3da5-5972-9806-2147c6400142' and status = 'published'; -- practica-me-dijo: De chico, ¿podías salir solo?
update public.sentences set status = 'retired', updated_at = now() where id = '257026d1-856b-5f84-b054-99f60d32a2fd' and status = 'published'; -- practica-me-dijo: ¿Quién te explicó eso?
update public.sentences set status = 'retired', updated_at = now() where id = '683a4af2-d263-50e4-8811-9174320d7901' and status = 'published'; -- se-me-quemo: Se me acabó la batería.
update public.sentences set status = 'retired', updated_at = now() where id = '4a11af66-5956-533b-b6ab-9723b2595de0' and status = 'published'; -- se-me-quemo: Se me acabó la nafta en la General Paz.
update public.sentences set status = 'retired', updated_at = now() where id = 'd236d9c2-7bcf-5f83-b2ae-ee231a61c0a6' and status = 'published'; -- para-que-entres: Levantá la persiana, por favor.
update public.sentences set status = 'retired', updated_at = now() where id = '55e73af2-6af6-5a16-9ec6-3e5520d78e99' and status = 'published'; -- para-que-entres: Levantá las persianas del living.
update public.sentences set status = 'retired', updated_at = now() where id = 'af2bbce3-0ee8-5016-bbf7-3b2fc16afb03' and status = 'published'; -- para-que-entres: Levantá las persianas, no veo nada.
update public.sentences set status = 'retired', updated_at = now() where id = '185bc548-9cb4-598c-a409-19ad3c7454a0' and status = 'published'; -- para-que-entres: Levantá la persiana despacio, que hace ruido.
update public.sentences set status = 'retired', updated_at = now() where id = '8173dd58-4e68-5f05-a3ca-8bfd8e29cf49' and status = 'published'; -- el-cajero shrink comprobante: Pasame el alias y después te mando el comprobante.
update public.sentences set status = 'retired', updated_at = now() where id = '5f55aec5-5b2c-5bda-83c4-aebc8a62e6c7' and status = 'published'; -- el-cajero shrink comprobante: Pagué con Mercado Pago, ¿te mando el comprobante?
update public.sentences set status = 'retired', updated_at = now() where id = 'e6e9b0eb-2487-5f4d-a33e-f00e9bc9f27b' and status = 'published'; -- el-cajero shrink comprobante: El comprobante de Mercado Pago dice otro nombre.
update public.sentences set status = 'retired', updated_at = now() where id = 'c9015e86-dd5e-570f-852a-3b2c5b284134' and status = 'published'; -- el-cajero shrink comprobante: Sin comprobante no te puedo dar la entrada.
update public.sentences set status = 'retired', updated_at = now() where id = '8da14642-e07e-5789-bfea-129f40b56bc5' and status = 'published'; -- el-cajero shrink comprobante: ¿Tenés el comprobante de la transferencia?
update public.sentences set status = 'retired', updated_at = now() where id = '7698bccf-f215-5cb4-b283-6d0b0cdebd1f' and status = 'published'; -- el-cajero shrink comprobante: El dueño siempre me pide el comprobante.
update public.sentences set status = 'retired', updated_at = now() where id = 'f11b324f-ad2a-5b41-8dc2-c31d8d02a45b' and status = 'published'; -- el-cajero shrink comprobante: Si no te llegó, te mando el comprobante.
update public.sentences set status = 'retired', updated_at = now() where id = '9c0510e1-8034-564e-98d1-119b85f1e55b' and status = 'published'; -- el-cajero shrink comprobante: Guardame el comprobante, por las dudas.
update public.sentences set status = 'retired', updated_at = now() where id = '56970e19-38a3-5d1c-a78a-ec11f45aa2f7' and status = 'published'; -- acabo-de shrink acabo de: No me llames ahora, acabo de entrar a una reunión.
update public.sentences set status = 'retired', updated_at = now() where id = 'd5b95b43-91fd-58a4-8568-54b1fd4e4307' and status = 'published'; -- acabo-de shrink acabo de: —¿Ya comiste? —Sí, acabo de comer una empanada.
update public.sentences set status = 'retired', updated_at = now() where id = '9929d2f0-ee79-528c-b1e6-120171190ae3' and status = 'published'; -- acabo-de shrink acabo de: —¿Recién llegaste? —Sí, acabo de entrar.
update public.sentences set status = 'retired', updated_at = now() where id = '623b5d5c-bc1e-5271-9a0c-33d604f58cbf' and status = 'published'; -- acabo-de shrink acabo de: Acabo de comprar las medialunas.
update public.sentences set status = 'retired', updated_at = now() where id = 'd6efa820-2e05-55ab-91ad-483bab0b5486' and status = 'published'; -- acabo-de shrink acabo de: Che, acabo de llegar a casa.
update public.sentences set status = 'retired', updated_at = now() where id = '607378e6-c430-5dcd-8237-05d6ed67dfa7' and status = 'published'; -- acabo-de shrink acabás de: Generalmente no comés postre, ¿y acabás de pedir dos?
update public.sentences set status = 'retired', updated_at = now() where id = '5e95851b-f42a-5f3f-a85e-e0904abfc465' and status = 'published'; -- acabo-de shrink acabás de: ¿Acabás de conocer a Diego y ya estás enamorada?
update public.sentences set status = 'retired', updated_at = now() where id = '3e38fd07-0f44-53b6-83fc-445b91a8274e' and status = 'published'; -- acabo-de shrink acabás de: Acabás de terminar la tarea, descansá un rato.
update public.sentences set status = 'retired', updated_at = now() where id = '25347cdf-09fe-585e-9ae4-d1109db7c4db' and status = 'published'; -- acabo-de shrink acaba de: Mi jefa acaba de llegar; generalmente llega más tarde.
update public.sentences set status = 'retired', updated_at = now() where id = 'b9cef4fd-65c6-5523-894f-55257df3cb10' and status = 'published'; -- acabo-de shrink acaba de: —¿Y el encargado? —Recién lo vi, acaba de subir.
update public.sentences set status = 'retired', updated_at = now() where id = '9f368292-b7ef-5494-8a9e-a38df564bcf2' and status = 'published'; -- acabo-de shrink acaba de: Mi novio acaba de conocer a mis viejos.
update public.sentences set status = 'retired', updated_at = now() where id = '05e55945-ce9a-5598-b141-c8212ffa7c08' and status = 'published'; -- acabo-de shrink acaba de: Mi hermana acaba de llamar.
update public.sentences set status = 'retired', updated_at = now() where id = '9f60f799-ccac-5d93-813b-c57120183396' and status = 'published'; -- acabo-de shrink acaba de: —¿Y Santi? —Acaba de salir.
update public.sentences set status = 'retired', updated_at = now() where id = 'd31f5e31-3297-5ec3-9f86-febaf4ae3245' and status = 'published'; -- acabo-de shrink acabamos de: Acabamos de hablar con el dueño del depto.
update public.sentences set status = 'retired', updated_at = now() where id = 'ac95c3af-6f52-5156-8715-65d7ad046b7d' and status = 'published'; -- acabo-de shrink acabamos de: No, gracias, acabamos de tomar un café.
update public.sentences set status = 'retired', updated_at = now() where id = '54a68947-c7df-5c37-ba59-da01352bc0b1' and status = 'published'; -- acabo-de shrink acabamos de: Acabamos de terminar la mudanza.
update public.sentences set status = 'retired', updated_at = now() where id = 'd09cc54a-ad22-5ebf-a9af-2cf954105d01' and status = 'published'; -- acabo-de shrink acabamos de: Acabamos de pedir una pizza.
update public.sentences set status = 'retired', updated_at = now() where id = '37a15dad-41bb-51c6-97f0-a8a32d5bce50' and status = 'published'; -- acabo-de shrink acaban de: Generalmente abren a las nueve, pero hoy acaban de abrir.
update public.sentences set status = 'retired', updated_at = now() where id = '41f1f3ea-48d8-5ce2-93d2-91526dff6f5d' and status = 'published'; -- acabo-de shrink acaban de: Acaban de salir, recién los vi en la esquina.
update public.sentences set status = 'retired', updated_at = now() where id = 'b31c4ec3-48f1-5583-acac-02e97cd2bc76' and status = 'published'; -- acabo-de shrink acaban de: Acaban de traer las medialunas, ¿querés una?
update public.sentences set status = 'retired', updated_at = now() where id = 'ca12bc45-f9d0-5d5c-bb1a-bf4c4c98d4a9' and status = 'published'; -- acabo-de shrink suelo: —¿Vas a la oficina? —No, suelo laburar desde casa.
update public.sentences set status = 'retired', updated_at = now() where id = 'b47374ed-e2d6-5ab9-a18b-974a57fcaa5f' and status = 'published'; -- acabo-de shrink suelo: —¿Qué hacés los sábados? —Suelo jugar al fútbol.
update public.sentences set status = 'retired', updated_at = now() where id = '9671f4ea-b2d2-5429-a446-9b9cb336416a' and status = 'published'; -- acabo-de shrink suelo: En invierno suelo tomar café con leche.
update public.sentences set status = 'retired', updated_at = now() where id = 'e310a269-1499-5fca-9c92-8f7226d2071e' and status = 'published'; -- acabo-de shrink solés: —¿Solés manejar al centro? —No, voy en subte.
update public.sentences set status = 'retired', updated_at = now() where id = '10b0f18f-cec4-53e6-905b-bf8579993ad9' and status = 'published'; -- acabo-de shrink solés: ¿Dónde solés comer con tus amigos?
update public.sentences set status = 'retired', updated_at = now() where id = 'a63583d5-9414-5b2e-8c26-d501b256828d' and status = 'published'; -- acabo-de shrink solés: ¿Solés ir a la facu en bondi?
update public.sentences set status = 'retired', updated_at = now() where id = '000d6daa-a541-549d-97f3-22d9bfccba91' and status = 'published'; -- acabo-de shrink suele: Mi vieja suele llamar los domingos después de comer.
update public.sentences set status = 'retired', updated_at = now() where id = '00e9733d-4768-51b8-8622-e97142861feb' and status = 'published'; -- acabo-de shrink suele: Ella suele pedir la milanesa con papas fritas.
update public.sentences set status = 'retired', updated_at = now() where id = '0828b184-f357-5582-9c61-982b40e41f42' and status = 'published'; -- acabo-de shrink suele: Mi abuela suele cocinar los domingos.
update public.sentences set status = 'retired', updated_at = now() where id = '014c0157-4c7a-5b3c-8997-fb8d57383929' and status = 'published'; -- acabo-de shrink suele: ¿Santi suele laburar los sábados?
update public.sentences set status = 'retired', updated_at = now() where id = '30e293a8-ea4a-58ae-a633-fd3e3c4ea265' and status = 'published'; -- acabo-de shrink solemos: Solemos llegar temprano, pero hoy llegamos tarde.
update public.sentences set status = 'retired', updated_at = now() where id = '2c52bb50-bc6d-5f84-aa70-9da4ec2c5512' and status = 'published'; -- acabo-de shrink solemos: —¿Adónde van los sábados? —Solemos ir al cine.
update public.sentences set status = 'retired', updated_at = now() where id = '620f3aa2-de36-51c2-a937-94978c920e7a' and status = 'published'; -- acabo-de shrink solemos: Los domingos solemos hacer asado.
update public.sentences set status = 'retired', updated_at = now() where id = '830be79d-eb5d-55cc-bf92-3b6d52458253' and status = 'published'; -- acabo-de shrink solemos: Con Juan solemos jugar al fútbol.
update public.sentences set status = 'retired', updated_at = now() where id = '450584ba-2dce-5d75-a315-559cb3bb2e09' and status = 'published'; -- acabo-de shrink suelen: En diciembre, los precios suelen subir un montón.
update public.sentences set status = 'retired', updated_at = now() where id = '52680e0d-9f39-584d-8584-364bf4407ef5' and status = 'published'; -- acabo-de shrink suelen: ¿Qué suelen hacer ustedes en vacaciones?
update public.sentences set status = 'retired', updated_at = now() where id = 'eabb36c4-a282-5508-aaef-561a2ea1e8ef' and status = 'published'; -- acabo-de shrink suelen: Los vecinos suelen hacer ruido de noche.
update public.sentences set status = 'retired', updated_at = now() where id = '74424b01-a522-5d87-a7b6-14bac6bc46f0' and status = 'published'; -- acabo-de shrink suelen: Mis hermanos suelen venir para Navidad.
update public.sentences set status = 'retired', updated_at = now() where id = '1f337ba7-f169-5043-9fc3-c04be9a9929b' and status = 'published'; -- acabo-de shrink suelen: Mis abuelos suelen venir los domingos.
update public.sentences set status = 'retired', updated_at = now() where id = '9e59daaf-89a3-5780-ba51-3a834aa2be0a' and status = 'published'; -- acabo-de shrink suelen: Mis viejos suelen dormir la siesta.
update public.sentences set status = 'retired', updated_at = now() where id = '736b37a0-809f-5ea3-8e22-a89d8c398d42' and status = 'published'; -- aunque-llueva shrink de todos modos: Juan no puede, pero de todos modos nos juntamos.
update public.sentences set status = 'retired', updated_at = now() where id = '4af45cbc-f11d-5f3d-9e79-c576b607de8b' and status = 'published'; -- aunque-llueva shrink de todos modos: Aunque llueva, el asado se hace de todos modos.
update public.sentences set status = 'retired', updated_at = now() where id = '20b506cc-47fb-5670-921a-b26c21498f93' and status = 'published'; -- aunque-llueva shrink de todos modos: De todos modos, mañana te confirmo el horario.
update public.sentences set status = 'retired', updated_at = now() where id = '834d7cd7-4e4d-59ea-99f9-e73e7e33d438' and status = 'published'; -- aunque-llueva shrink de todos modos: ¿De todos modos tengo que firmar el contrato?
update public.sentences set status = 'retired', updated_at = now() where id = '017bf058-93d0-5c03-90ea-3f1c00b3a27d' and status = 'published'; -- aunque-llueva shrink de todos modos: Estaba cansado, pero salí de todos modos.
update public.sentences set status = 'retired', updated_at = now() where id = 'fc45838f-e3fa-589e-9ab2-0b44e46a3c2c' and status = 'published'; -- aunque-llueva shrink de todos modos: No tengo ganas, pero voy de todos modos.
update public.sentences set status = 'retired', updated_at = now() where id = '2f362055-72ec-5ec6-a064-558a322f5f44' and status = 'published'; -- aunque-llueva shrink de todos modos: Es caro, pero lo compro de todos modos.
update public.sentences set status = 'retired', updated_at = now() where id = '1e3a470e-a48a-515c-b422-0656553da4cb' and status = 'published'; -- aunque-llueva shrink de todos modos: Llueve, pero vamos de todos modos.
update public.sentences set status = 'retired', updated_at = now() where id = '38f81b62-4316-5a77-b750-7b36713ee650' and status = 'published'; -- aunque-llueva shrink de todos modos: De todos modos, te llamo mañana.
update public.sentences set status = 'retired', updated_at = now() where id = '53d05a65-1ad1-50ff-8367-0041ca9bc665' and status = 'published'; -- llevo-dos-anos shrink llevás: Si llevás un rato esperando, andá a tomar un café.
update public.sentences set status = 'retired', updated_at = now() where id = '57b576d0-f913-59e5-b8ec-12584407c2d6' and status = 'published'; -- llevo-dos-anos shrink llevás: Llevás una hora hablando con Cami.
update public.sentences set status = 'retired', updated_at = now() where id = 'f08b9b75-5415-5f9b-9778-edd807054326' and status = 'published'; -- llevo-dos-anos shrink llevás: ¿Cuánto llevás estudiando inglés?
update public.sentences set status = 'retired', updated_at = now() where id = '1d93f7fc-7bb0-5921-89a5-1c34f977be55' and status = 'published'; -- llevo-dos-anos shrink llevás: Llevás tres días sin dormir.
update public.sentences set status = 'retired', updated_at = now() where id = '8f685a48-eeee-5d5b-8862-143a6bf69927' and status = 'published'; -- llevo-dos-anos shrink lleva: Mi abuela lleva cincuenta años viviendo en el mismo barrio.
update public.sentences set status = 'retired', updated_at = now() where id = '207e3aee-d50d-52ab-b53b-7dd258185c3e' and status = 'published'; -- llevo-dos-anos shrink lleva: Ana lleva dos años estudiando inglés en la facu.
update public.sentences set status = 'retired', updated_at = now() where id = 'cd033a27-fd2c-522f-a7af-bdcbe3f552ee' and status = 'published'; -- llevo-dos-anos shrink lleva: ¿Cuánto tiempo lleva tu hermana en Córdoba?
update public.sentences set status = 'retired', updated_at = now() where id = '6d0d3da6-cfbe-5b3c-a051-81fc599c418d' and status = 'published'; -- llevo-dos-anos shrink lleva: Rocío lleva dos horas esperando.
update public.sentences set status = 'retired', updated_at = now() where id = '3f88383b-7153-542b-9cae-2d53ad02d740' and status = 'published'; -- llevo-un-ano-aprendiendo shrink llevan: ¿Cuánto llevan viviendo en Buenos Aires?
update public.sentences set status = 'retired', updated_at = now() where id = '7955b9f9-a969-51a3-b5c4-8614d770fdf5' and status = 'published'; -- practica-aunque-sea: Seguimos sin luz.
update public.sentences set status = 'retired', updated_at = now() where id = 'd0252132-6d30-5502-abc8-c82dc29e8f6e' and status = 'published'; -- practica-aunque-sea: Juan y yo seguimos hablando todos los días.
update public.sentences set status = 'retired', updated_at = now() where id = '1c89b900-db5e-5cb2-b03d-8c029c3ae147' and status = 'published'; -- practica-aunque-sea shrink llevás: ¿Cuántos años llevás viviendo en Buenos Aires?
update public.sentences set status = 'retired', updated_at = now() where id = '90b3faee-01ff-5bc9-9128-b621e5b1e0ee' and status = 'published'; -- practica-aunque-sea shrink llevás: —¿Cuánto llevás en la empresa? —Casi dos años.
update public.sentences set status = 'retired', updated_at = now() where id = '9d354270-0e57-5660-b689-b97ab7160e68' and status = 'published'; -- practica-aunque-sea shrink llevás: Llevás días tratando de hablar con él.
update public.sentences set status = 'retired', updated_at = now() where id = '600cca9d-4f65-55ec-87bf-7016bd152014' and status = 'published'; -- practica-aunque-sea shrink llevás: Llevás toda la semana con esa tos.
update public.sentences set status = 'retired', updated_at = now() where id = '71de27c9-84d7-5482-b56a-22e5ae70844a' and status = 'published'; -- practica-migraciones: ¿Cómo estuvo el vuelo?
update public.sentences set status = 'retired', updated_at = now() where id = 'bd7dba5c-fb1e-50bc-85c5-8bd20f2afff9' and status = 'published'; -- practica-migraciones: El vuelo está demorado.
update public.sentences set status = 'retired', updated_at = now() where id = '112ede38-589e-51f5-8bda-e4aa947f3528' and status = 'published'; -- practica-migraciones: La ventaja es que queda cerca.
update public.sentences set status = 'retired', updated_at = now() where id = '3c0814e3-8d2a-5dba-9926-32279cb337b6' and status = 'published'; -- practica-migraciones: Fue mala suerte, nada más.
update public.sentences set status = 'retired', updated_at = now() where id = 'a48778d6-3826-5f7e-aebe-2aa1fe0f7743' and status = 'published'; -- practica-migraciones: La verdad, no sé.
update public.sentences set status = 'retired', updated_at = now() where id = 'ad49fdce-24f2-549e-bbb5-8487f47d1007' and status = 'published'; -- practica-migraciones: Ese horario no me conviene.
update public.sentences set status = 'retired', updated_at = now() where id = '9862b89e-6d42-5586-972c-9c9d391337bf' and status = 'published'; -- practica-migraciones: Si hubiéramos salido antes, no hubiéramos perdido el vuelo.
update public.sentences set status = 'retired', updated_at = now() where id = 'd3251cfd-851b-5de1-b50c-b8c2622fd2f6' and status = 'published'; -- practica-migraciones shrink demoró: Juan tardó una hora en llegar, pero el trámite no demoró nada.
update public.sentences set status = 'retired', updated_at = now() where id = '4d4e6950-c88e-5079-818d-9d1cef099c02' and status = 'published'; -- practica-migraciones shrink demoró: El trámite demoró tanto que perdí el vuelo.
update public.sentences set status = 'retired', updated_at = now() where id = '41f7b644-fa11-5149-b194-45609d6c65fa' and status = 'published'; -- practica-migraciones shrink demoró: Juli demoró media hora en el baño.
update public.sentences set status = 'retired', updated_at = now() where id = 'ab0ea1ae-43a8-54fb-8e79-3a83cd92bda0' and status = 'published'; -- practica-migraciones shrink demoró: La residencia demoró seis meses.
update public.sentences set status = 'retired', updated_at = now() where id = '3e4d9eac-fb67-5b12-bd75-3d59b16aabce' and status = 'published'; -- practica-migraciones shrink demoró: Por lo menos no demoró tanto.
update public.sentences set status = 'retired', updated_at = now() where id = '980d1400-3113-58fa-95dd-1c9a10753e4e' and status = 'published'; -- practica-migraciones shrink demoró: ¿Cuánto demoró el pasaporte?
update public.sentences set status = 'retired', updated_at = now() where id = '53796df6-8acf-5902-8c88-249ffb3e9b54' and status = 'published'; -- practica-migraciones shrink demoró: El trámite demoró una hora.
update public.sentences set status = 'retired', updated_at = now() where id = 'e6c463b0-6d7e-5507-a290-985d4085aa36' and status = 'published'; -- me-pone-nervioso-que shrink cancelar: No me gusta cancelar planes a último momento.
update public.sentences set status = 'retired', updated_at = now() where id = '0b5c9f2c-301f-58ba-8ecc-a1aa410813da' and status = 'published'; -- me-pone-nervioso-que shrink cancelar: Me enoja tener que cancelar el viaje.
update public.sentences set status = 'retired', updated_at = now() where id = '35c01b99-78a1-59f6-aedf-f4ed45d5fc3c' and status = 'published'; -- me-pone-nervioso-que shrink canceló: Canceló la juntada porque estaba de mal humor.
update public.sentences set status = 'retired', updated_at = now() where id = 'bf7591ff-c5b5-57e9-9f93-a6222ecd2a1a' and status = 'published'; -- me-pone-nervioso-que shrink canceló: ¿Sabés por qué canceló el turno?
update public.sentences set status = 'retired', updated_at = now() where id = '42e67866-9545-5c35-abcb-befe811d714d' and status = 'published'; -- me-pone-nervioso-que shrink cancele: Me alegra que el profe cancele la clase del lunes.
update public.sentences set status = 'retired', updated_at = now() where id = '8c6c932e-a0d2-5076-9c3e-c98201245fc6' and status = 'published'; -- me-pone-nervioso-que shrink cancele: Me da bronca que cancele siempre a último momento.
update public.sentences set status = 'retired', updated_at = now() where id = '2dafe410-d70e-51a9-b797-5bb59fc35172' and status = 'published'; -- deberias: ¿Debería comprar la campera azul?
update public.sentences set status = 'retired', updated_at = now() where id = '25c994e6-337d-5e2f-8948-e5641c4f7cb1' and status = 'published'; -- deberias: ¿Qué debería hacer?
update public.sentences set status = 'retired', updated_at = now() where id = '0ee95d1d-9585-5355-9923-5eada7cb2115' and status = 'published'; -- deberias shrink deberías: Deberías descansar; yo que vos, me quedaría en casa.
update public.sentences set status = 'retired', updated_at = now() where id = '6024de79-6e7a-5b1b-9f15-aa7f9600115f' and status = 'published'; -- deberias shrink deberías: Si te duele la cabeza, deberías tomar algo.
update public.sentences set status = 'retired', updated_at = now() where id = '025e1010-76a0-5fca-b0b1-5f9b36e02e11' and status = 'published'; -- deberias shrink deberías: Deberías hablar con tu jefe.
update public.sentences set status = 'retired', updated_at = now() where id = 'a91971e8-756c-59c0-a349-037e89eb5fd4' and status = 'published'; -- deberias shrink deberías: Deberías descansar un poco.
update public.sentences set status = 'retired', updated_at = now() where id = '011550ba-624e-5bc6-9add-31978f208d02' and status = 'published'; -- deberias shrink deberías: Deberías llamar a tu mamá.
update public.sentences set status = 'retired', updated_at = now() where id = '8f773ddf-61cd-5233-a640-7696095cdacc' and status = 'published'; -- deberias shrink deberías: No deberías laburar tanto.
update public.sentences set status = 'retired', updated_at = now() where id = 'a9e6685e-2562-53ad-9646-328373bb438d' and status = 'published'; -- deberias shrink debería: Me duele la muela, debería pedir un turno.
update public.sentences set status = 'retired', updated_at = now() where id = '938377a9-1c7a-5179-a8c7-0c8a89d46e20' and status = 'published'; -- practica-alguien-que-sepa: ¿Conocés a alguien que arregle bicis?
update public.sentences set status = 'retired', updated_at = now() where id = '7516d447-4de5-5a05-a65b-5ab387720d4e' and status = 'published'; -- practica-alguien-que-sepa: La lluvia me pone triste.
update public.sentences set status = 'retired', updated_at = now() where id = '387b4b6e-642f-54a1-be35-457e51e558ff' and status = 'published'; -- practica-alguien-que-sepa: Estaría bueno ir a la playa.
update public.sentences set status = 'retired', updated_at = now() where id = '40869465-d040-5ae1-84af-c1a46513c414' and status = 'published'; -- practica-alguien-que-sepa: Estaría bueno que vengas.
update public.sentences set status = 'retired', updated_at = now() where id = 'eff9d7cd-6f2d-5a46-82ac-b68539ccf218' and status = 'published'; -- practica-alguien-que-sepa: Estoy quemado con el laburo.
update public.sentences set status = 'retired', updated_at = now() where id = '07cddb20-bc8f-5fd4-84f7-bd2b61ddf6ab' and status = 'published'; -- practica-alguien-que-sepa: ¿Hacés terapia?
update public.sentences set status = 'retired', updated_at = now() where id = 'aa81f10b-536c-5b1a-a055-b8929fadec5d' and status = 'published'; -- practica-alguien-que-sepa: Fede canceló a último momento.
update public.sentences set status = 'retired', updated_at = now() where id = '3122365b-0539-58dd-b762-f7980a716d31' and status = 'published'; -- dijo-que-vendria shrink vendría: Pablo dijo que vendría a las ocho, pero llegó tarde.
update public.sentences set status = 'retired', updated_at = now() where id = '798e5289-4e18-51f8-b81e-a2ef238923fa' and status = 'published'; -- dijo-que-vendria shrink vendría: Ana dijo que vendría y al final no vino.
update public.sentences set status = 'retired', updated_at = now() where id = '781985e9-f584-5ec8-befe-54d310425c89' and status = 'published'; -- dijo-que-vendria shrink vendría: El plomero dijo que vendría a las diez.
update public.sentences set status = 'retired', updated_at = now() where id = '27ca33ef-53d8-5a56-a6e2-e26d78f96cfc' and status = 'published'; -- dijo-que-vendria shrink vendrías: Te estaba esperando porque dijiste que vendrías.
update public.sentences set status = 'retired', updated_at = now() where id = '0412cf86-c6f4-5e89-a301-41a856747fe3' and status = 'published'; -- dijo-que-vendria shrink vendrías: Juli dijo que vendrías con Mati.
update public.sentences set status = 'retired', updated_at = now() where id = '908b71c1-ed26-5cf8-8696-1eed674adcc0' and status = 'published'; -- dijo-que-vendria shrink llamaría: Sofi dijo que me llamaría y no llamó.
update public.sentences set status = 'retired', updated_at = now() where id = 'd4458fde-8ca8-5014-a001-e0e912e9cf47' and status = 'published'; -- dijo-que-vendria shrink llamaría: Mi jefe dijo que llamaría el lunes.
update public.sentences set status = 'retired', updated_at = now() where id = 'dab430fd-c4a6-5287-a64d-70477f66f32d' and status = 'published'; -- dijo-que-vendria shrink llamaría: Diego dijo que llamaría hoy.
update public.sentences set status = 'retired', updated_at = now() where id = '29e27b52-2783-5f84-8b50-59c3009a81e0' and status = 'published'; -- dijo-que-pasaria shrink pasaría: El encargado me aseguró que pasaría mañana.
update public.sentences set status = 'retired', updated_at = now() where id = 'af17da82-3fd8-5ac8-bbad-01608546898e' and status = 'published'; -- dijo-que-pasaria shrink traería: Dijo que traería torta y trajo pan.
update public.sentences set status = 'retired', updated_at = now() where id = 'd34ce223-4774-5278-bf45-5bb0d015ce73' and status = 'published'; -- dijo-que-pasaria shrink devolvería: Mi hermano dijo que me devolvería el auto hoy.
update public.sentences set status = 'retired', updated_at = now() where id = 'f32abc71-048a-5e23-bff8-5703aa560324' and status = 'published'; -- dijo-que-pasaria shrink pondría: ¿Quién dijo que pondría el agua para el mate?
update public.sentences set status = 'retired', updated_at = now() where id = '4ca21602-2445-5aa2-a821-dea004e08a35' and status = 'published'; -- dijo-que-pasaria shrink arreglaría: Dijo que arreglaría la puerta, pero sigue rota.
update public.sentences set status = 'retired', updated_at = now() where id = '76eff4dc-eb7b-5463-abeb-d9922c02cf59' and status = 'published'; -- practica-se-aceptan-tarjetas: Fede dijo que pondría la música.
update public.sentences set status = 'retired', updated_at = now() where id = '018f4d3f-7651-56a0-b107-a152687ea979' and status = 'published'; -- practica-se-aceptan-tarjetas: Juan me aseguró que pondría el cartel hoy.
update public.sentences set status = 'retired', updated_at = now() where id = '1e338723-ef77-5876-acf0-0ad337d17f85' and status = 'published'; -- practica-se-aceptan-tarjetas shrink devolvería: Lucía dijo que devolvería el libro, y ya pasó un mes.
update public.sentences set status = 'retired', updated_at = now() where id = '1a223a94-7fb3-5b43-9274-a62170bea222' and status = 'published'; -- practica-se-aceptan-tarjetas shrink devolvería: Mi hermano me juró que me devolvería el cargador.
update public.sentences set status = 'retired', updated_at = now() where id = '0c2f34b8-7604-5673-b61f-ece95139a531' and status = 'published'; -- practica-se-aceptan-tarjetas shrink devolvería: Mati prometió que me devolvería la plata.
update public.sentences set status = 'retired', updated_at = now() where id = 'b9abd405-0069-5daf-8180-d9a59b026cbc' and status = 'published'; -- practica-se-aceptan-tarjetas shrink pasaría: Ya son las diez y todavía lo estoy esperando. Me juró que pasaría.
update public.sentences set status = 'retired', updated_at = now() where id = '371e33e8-7200-5fc0-a03a-eff4118937d7' and status = 'published'; -- practica-se-aceptan-tarjetas shrink pasaría: Creí que pasaría el sábado, pero nunca vino.
update public.sentences set status = 'retired', updated_at = now() where id = 'ffb7e8ac-acc6-5758-8b7c-e26c112a0ec9' and status = 'published'; -- practica-se-aceptan-tarjetas shrink vendría: Lucía prometió que vendría y canceló a último momento.
update public.sentences set status = 'retired', updated_at = now() where id = '3936d274-856e-5345-b861-03849f6eefa5' and status = 'published'; -- practica-se-aceptan-tarjetas shrink vendría: Mi hermana vendría a vivir acá si tuviera laburo.
update public.sentences set status = 'retired', updated_at = now() where id = 'ec8b93ec-1f04-5ce7-8a54-b2e4576bdd7a' and status = 'published'; -- practica-se-aceptan-tarjetas shrink vendría: ¿Y Nico? Dijo que vendría más tarde.
update public.sentences set status = 'retired', updated_at = now() where id = '562847a1-8860-54c2-8e3f-dc0b838a9d81' and status = 'published'; -- practica-se-aceptan-tarjetas shrink vendría: Yo vendría, pero laburo el sábado.
update public.sentences set status = 'retired', updated_at = now() where id = '2d3225e0-1f2e-57db-89ca-abd9fb6c3f05' and status = 'published'; -- practica-no-lo-aguanto: ¿Cómo hacés para llegar a fin de mes?
update public.sentences set status = 'retired', updated_at = now() where id = 'd4e99c2f-6865-5e06-888b-6ae1a83ca529' and status = 'published'; -- practica-no-lo-aguanto: Cuesta llegar a fin de mes.
update public.sentences set status = 'retired', updated_at = now() where id = 'b921535d-79e0-579c-abf6-ac6bb901a7ed' and status = 'published'; -- practica-no-lo-aguanto: ¿Viste las tarifas de este mes?
update public.sentences set status = 'retired', updated_at = now() where id = '008768fe-2f39-5d5d-b267-a8df3a62e4a2' and status = 'published'; -- practica-no-lo-aguanto: ¿Cuánto sale el boleto?
update public.sentences set status = 'retired', updated_at = now() where id = '4267e3cd-377e-5bef-b924-616b2fee314a' and status = 'published'; -- practica-no-lo-aguanto: Estoy a punto de salir.
update public.sentences set status = 'retired', updated_at = now() where id = 'c5896678-a499-5c17-9f4c-d3894bbbdb71' and status = 'published'; -- practica-no-lo-aguanto: ¿Andás estudiando para el examen?
update public.sentences set status = 'retired', updated_at = now() where id = 'd598ae0a-5f48-5a26-85ad-e9debb2da74d' and status = 'published'; -- practica-no-lo-aguanto: ¿Qué andás haciendo?
update public.sentences set status = 'retired', updated_at = now() where id = '99eb0c06-c005-5dc8-946b-a2a885ba0f65' and status = 'published'; -- practica-no-lo-aguanto: Estamos por llegar.
update public.sentences set status = 'retired', updated_at = now() where id = 'd76f5fa3-068f-540a-b6ec-612f5d4ed264' and status = 'published'; -- ni-ahi: ¿Estás loco? Ese depto es carísimo.
update public.sentences set status = 'retired', updated_at = now() where id = '02609c3f-0ade-5669-ad9e-31f3c8eb0ecf' and status = 'published'; -- ni-ahi: ¿Mil dólares? ¿Estás loco?
update public.sentences set status = 'retired', updated_at = now() where id = '7cd874c7-8adf-5cd2-b12e-ab3c546344f5' and status = 'published'; -- ni-ahi: ¿Salir con esta lluvia? ¿Estás loco?
update public.sentences set status = 'retired', updated_at = now() where id = '5c7f5f4b-9757-564d-97a5-e7049482a737' and status = 'published'; -- practica-como-no: ¿Qué te encargó Juan?
update public.sentences set status = 'retired', updated_at = now() where id = 'c5a1f8ea-a1bf-5beb-98af-c90d65f5b10d' and status = 'published'; -- practica-como-no: ¿Les dijiste que trajeran vasos?
update public.sentences set status = 'retired', updated_at = now() where id = '90403fce-8654-589d-9090-c0dce8c701f1' and status = 'published'; -- practica-como-no: Portate bien, que viene la abuela.
update public.sentences set status = 'retired', updated_at = now() where id = '2a58ec48-cb2b-515c-99dd-98ec822aa123' and status = 'published'; -- cualquier-cosa-avisame shrink estimado: Estimado vecino, el ascensor no anda desde el lunes.
update public.sentences set status = 'retired', updated_at = now() where id = '39d2163c-ce3e-569b-b89b-89adf81b0089' and status = 'published'; -- cualquier-cosa-avisame shrink estimado: Estimado Raúl: te escribo por el puesto de vendedor.
update public.sentences set status = 'retired', updated_at = now() where id = 'f5b266eb-e9ae-5868-ba2b-53c81acd73c6' and status = 'published'; -- resulta-que: Resulta que Belén se mudó a Córdoba en enero.
update public.sentences set status = 'retired', updated_at = now() where id = 'c19f9855-569f-59e5-b021-92591291fdfb' and status = 'published'; -- resulta-que: Nadie se enteró.
update public.sentences set status = 'retired', updated_at = now() where id = '3396b9f9-7f40-5280-b8f6-5382243a3fc2' and status = 'published'; -- resulta-que: Total, nadie se enteró.
update public.sentences set status = 'retired', updated_at = now() where id = '14be14c8-75a0-5629-af74-794e983c9e99' and status = 'published'; -- para-colmo: ¿Te despidieron? ¿Por qué?
update public.sentences set status = 'retired', updated_at = now() where id = '239fdcb5-29c2-5b1f-ab30-1d5975f3ef8f' and status = 'published'; -- para-colmo: Martín está tranquilo, aunque lo despidieron el lunes.
update public.sentences set status = 'retired', updated_at = now() where id = 'a2504f60-90e1-545f-8825-5b41e5fe1b90' and status = 'published'; -- para-colmo: Me despidieron ayer.
update public.sentences set status = 'retired', updated_at = now() where id = 'dae00498-86ae-5e85-baa0-ca26dc1ffd10' and status = 'published'; -- para-colmo: Por lo visto, nadie se enteró.
update public.sentences set status = 'retired', updated_at = now() where id = 'e3b76c1c-986f-5d9d-a2e3-6f192c896dd7' and status = 'published'; -- me-la-jugue: Me la jugué y me mudé a Córdoba.
update public.sentences set status = 'retired', updated_at = now() where id = '096cc6cb-4aa2-5478-b880-fe62813a005e' and status = 'published'; -- me-la-jugue: ¿Mudarme a Córdoba? No la veo.
update public.sentences set status = 'retired', updated_at = now() where id = '5bce288c-7c38-5c0f-a142-09b7dca0ad48' and status = 'published'; -- practica-me-la-jugue: Para colmo, me quedé sin batería.
update public.sentences set status = 'retired', updated_at = now() where id = '556413b6-0274-5678-8241-d1ffa4778061' and status = 'published'; -- practica-me-la-jugue: Se cortó la luz de golpe.
update public.sentences set status = 'retired', updated_at = now() where id = '76a80628-844b-5c18-8631-f606ff77ccbf' and status = 'published'; -- practica-me-la-jugue: Por lo visto, Diego se mudó a Córdoba.
update public.sentences set status = 'retired', updated_at = now() where id = '5d5937c4-2edf-5654-a785-acfeb0b59711' and status = 'published'; -- practica-me-pudri: —¿Cómo andás? —Bien, no me quejo.
update public.sentences set status = 'retired', updated_at = now() where id = 'd6535203-af89-5d9b-965b-a2fb4ba1b13a' and status = 'published'; -- practica-me-pudri: Me pudrí de esperar.
update public.sentences set status = 'retired', updated_at = now() where id = '01b731a7-4628-5eba-989e-8cd41c867c32' and status = 'published'; -- practica-me-pudri: Posta, me pudrí de pagar tanto alquiler.
update public.sentences set status = 'retired', updated_at = now() where id = '0b3908cf-372a-58d7-90b1-fa23292e8af6' and status = 'published'; -- practica-me-pudri: Me harté de este laburo.
update public.sentences set status = 'retired', updated_at = now() where id = '915d353e-bdef-5103-b425-a6c15392876d' and status = 'published'; -- hay-paro shrink cercano: Con el paro, el taxi más cercano tarda una hora.
update public.sentences set status = 'retired', updated_at = now() where id = 'bda9b624-b881-580d-95ec-1981e5bb6bac' and status = 'published'; -- hay-paro shrink cercana: ¿La estación más cercana funciona con el paro?
update public.sentences set status = 'retired', updated_at = now() where id = 'cbf9bd19-dede-51e0-b97b-c2887707c5e8' and status = 'published'; -- practica-el-cuarto-oscuro: Mi viejo está en el gremio.
update public.sentences set status = 'retired', updated_at = now() where id = '6dd28288-d3f2-5b29-ba14-154790800ffe' and status = 'published'; -- practica-el-cuarto-oscuro: Hay una ley nueva.
update public.sentences set status = 'retired', updated_at = now() where id = '092e2a57-a86f-57f6-9bf4-86afe317a540' and status = 'published'; -- practica-el-cuarto-oscuro: Hubo un accidente.
update public.sentences set status = 'retired', updated_at = now() where id = 'ea63ce16-b393-5034-bc8a-3bc77c6ab3a1' and status = 'published'; -- practica-el-cuarto-oscuro: Hay desvíos por la marcha.
update public.sentences set status = 'retired', updated_at = now() where id = '0f6e23c4-e3c9-5c36-ab88-b539ad72b66e' and status = 'published'; -- practica-el-cuarto-oscuro: El gremio anunció un paro.
update public.sentences set status = 'retired', updated_at = now() where id = 'c38e543b-bfe8-5668-8df9-178ce306f42e' and status = 'published'; -- practica-el-cuarto-oscuro: Todos fueron rescatados.
update public.sentences set status = 'retired', updated_at = now() where id = '9eff1f19-6b49-5772-b60b-8f33ecd9f380' and status = 'published'; -- practica-el-cuarto-oscuro: Los chicos fueron rescatados.
update public.sentences set status = 'retired', updated_at = now() where id = '47bdf2b3-ea4d-5ee7-96ec-861cd0182dc3' and status = 'published'; -- practica-la-parrillada: ¿Bailás conmigo?
update public.sentences set status = 'retired', updated_at = now() where id = 'c9250124-e7b6-5e47-981e-521dc1f4606f' and status = 'published'; -- practica-la-parrillada: ¿Bailás tango?
update public.sentences set status = 'retired', updated_at = now() where id = '5d7786a1-8431-5743-afa3-8d79922c5e58' and status = 'published'; -- practica-la-parrillada: ¿Rock nacional o cumbia?
update public.sentences set status = 'retired', updated_at = now() where id = '5374d03a-5173-500d-b6fc-437fa18fc30a' and status = 'published'; -- practica-la-parrillada: ¿Te gusta el rock nacional?
update public.sentences set status = 'retired', updated_at = now() where id = 'c8cd5dcd-1d51-582d-860d-99ce793b5118' and status = 'published'; -- practica-la-parrillada: ¡Qué buen cantante!
update public.sentences set status = 'retired', updated_at = now() where id = '1739f6c7-091b-5683-bf56-18308fd2e14d' and status = 'published'; -- practica-la-parrillada: ¿Qué tocás?
update public.sentences set status = 'retired', updated_at = now() where id = '612a2047-a4cd-525e-800e-e41695b8a17d' and status = 'published'; -- practica-la-parrillada: ¿Tocás en una banda?
update public.sentences set status = 'retired', updated_at = now() where id = '474257a3-cb60-57f4-baa9-fc136eb69f66' and status = 'published'; -- practica-la-parrillada: ¿Tocás la guitarra?
update public.sentences set status = 'retired', updated_at = now() where id = 'aa5fdbfc-1a11-54c0-b206-fb6963932f67' and status = 'published'; -- practica-la-parrillada: La milonga está llena.
update public.sentences set status = 'retired', updated_at = now() where id = 'd5027320-ab91-5a62-9a43-a789264a5901' and status = 'published'; -- practica-la-parrillada: ¿Vamos a la milonga?
update public.sentences set status = 'retired', updated_at = now() where id = '75e7b9e2-ce2f-58ac-ad3b-d2a54f1468f4' and status = 'published'; -- no-es-que-no-me-guste shrink rechazar: No sé cómo rechazar la invitación de Mica.
update public.sentences set status = 'retired', updated_at = now() where id = 'b697d3a6-9e84-5b85-8cab-6f236ad47bc0' and status = 'published'; -- no-es-que-no-me-guste shrink rechacé: Ya rechacé dos invitaciones, no puedo otra vez.
update public.sentences set status = 'retired', updated_at = now() where id = '7414049c-c82a-5cd9-9da6-f69061cc46b4' and status = 'published'; -- no-es-que-no-me-guste shrink rechacé: No rechacé la invitación, dije que capaz voy.
update public.sentences set status = 'retired', updated_at = now() where id = 'c15dfc4d-4014-50fe-908a-b97628b8edc2' and status = 'published'; -- practica-me-hubiera-gustado: ¡Qué linda invitación!
update public.sentences set status = 'retired', updated_at = now() where id = '6a59e451-8bda-5bac-997e-3331aa200a2d' and status = 'published'; -- practica-me-hubiera-gustado: Dale, la próxima.
update public.sentences set status = 'retired', updated_at = now() where id = '3c892ff2-ec12-5be4-82e1-9110d79fb4d5' and status = 'published'; -- practica-me-hubiera-gustado: Me da miedo quedar mal.
update public.sentences set status = 'retired', updated_at = now() where id = '1e49e960-3308-5970-8aa4-3ed112abe47f' and status = 'published'; -- practica-me-hubiera-gustado: No quiero quedar mal.
update public.sentences set status = 'retired', updated_at = now() where id = '6acec11b-4b80-5cb0-928d-46a62fe1cb44' and status = 'published'; -- practica-me-hubiera-gustado: Fue un error.
update public.sentences set status = 'retired', updated_at = now() where id = '9f86c383-44a3-540a-b302-49f581273532' and status = 'published'; -- practica-me-hubiera-gustado: ¡Te lo perdiste!
update public.sentences set status = 'retired', updated_at = now() where id = '4f1c23c4-7e81-5389-a6c9-7e83733d7502' and status = 'published'; -- practica-me-hubiera-gustado: Me hubiera gustado ir.
update public.sentences set status = 'retired', updated_at = now() where id = '7f10f93b-518c-5bd3-a53f-5ad013795b02' and status = 'published'; -- practica-me-hubiera-gustado: No es que no me interese.
update public.sentences set status = 'retired', updated_at = now() where id = 'bec551bd-8180-5153-93d9-cd8dd97e73c4' and status = 'published'; -- practica-me-hubiera-gustado: No puedo, tengo un compromiso con mi familia.
update public.sentences set status = 'retired', updated_at = now() where id = '1426fd2c-0ca3-5264-aa32-29c15869efcd' and status = 'published'; -- practica-me-hubiera-gustado: Perdón, tengo otro compromiso.
update public.sentences set status = 'retired', updated_at = now() where id = '393616e1-13b0-5482-bba2-b4cd3439ed3c' and status = 'published'; -- practica-me-hubiera-gustado: Tengo un compromiso.
update public.sentences set status = 'retired', updated_at = now() where id = 'ec9a2477-d0c3-5fe3-a173-4b2aa1d49fd0' and status = 'published'; -- lo-que-pasa-es-que: ¿Sabés lo de Sofi?
update public.sentences set status = 'retired', updated_at = now() where id = 'fc27ba9c-03ec-51ec-b67c-a6bef4c42380' and status = 'published'; -- lo-que-pasa-es-que: ¿Te enteraste de lo de Nico?
update public.sentences set status = 'retired', updated_at = now() where id = 'c4dc24a7-c427-5c3b-898f-d2b5f9d3ef5e' and status = 'published'; -- lo-que-pasa-es-que: Lo de Belén es re raro.
update public.sentences set status = 'retired', updated_at = now() where id = 'abe29c35-3998-5596-b726-273ce1dd3823' and status = 'published'; -- practica-cada-loco-con-su-tema: Comemos lo que sea.
update public.sentences set status = 'retired', updated_at = now() where id = '0ffbb003-0b44-5ed8-9535-99f73bdeb8fa' and status = 'published'; -- practica-cada-loco-con-su-tema: En el fondo, tenés razón.
update public.sentences set status = 'retired', updated_at = now() where id = 'affd2b13-41c0-5b6d-843f-b8ae1ecf52f2' and status = 'published'; -- practica-cada-loco-con-su-tema: Lo que quiero decir es que necesito tiempo.
update public.sentences set status = 'retired', updated_at = now() where id = 'cd3b2b56-6e9f-51dc-b952-0b9e056c3512' and status = 'published'; -- practica-cada-loco-con-su-tema: Lo que quiero decir es que no puedo.
update public.sentences set status = 'retired', updated_at = now() where id = 'e196cadd-66c6-58c8-90c6-b75dade45ef4' and status = 'published'; -- practica-cada-loco-con-su-tema: La música es lo tuyo.
update public.sentences set status = 'retired', updated_at = now() where id = '34d5c7df-38e3-533a-bda9-5157bf0ddc46' and status = 'published'; -- cuanto-antes-lleguemos shrink tanto mejor: ¿Empieza a las siete? Tanto mejor, llegamos temprano a casa.
update public.sentences set status = 'retired', updated_at = now() where id = 'd253b5d5-9f39-5e35-9f30-1478ecc93c1f' and status = 'published'; -- cuanto-antes-lleguemos shrink tanto mejor: Si podemos evitar la hora pico, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '9a73a52d-90d0-53c1-9c2d-fe6c2f212575' and status = 'published'; -- cuanto-antes-lleguemos shrink tanto mejor: Si podemos ir a pie, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '13f26807-168c-5619-b40b-04ad6d1a1fd3' and status = 'published'; -- cuanto-antes-lleguemos shrink tanto mejor: Si llegamos antes, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = 'dfd44f51-4287-5fe0-80f5-11a3a53505fb' and status = 'published'; -- cuanto-antes-lleguemos shrink tanto mejor: ¿Está abierto? Tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '60c90011-9393-5ea1-a088-d77acea385e1' and status = 'published'; -- practica-me-mori-de-risa: Nunca te reís.
update public.sentences set status = 'retired', updated_at = now() where id = '541e4a73-b136-5eff-85f3-d4198d446107' and status = 'published'; -- practica-me-mori-de-risa: Vos te reís de todo.
update public.sentences set status = 'retired', updated_at = now() where id = '143a7027-476c-54fa-8822-b20ee893b562' and status = 'published'; -- practica-me-mori-de-risa: ¿Lloraste con la película?
update public.sentences set status = 'retired', updated_at = now() where id = '36f0975e-cece-5e04-9b74-84653f031369' and status = 'published'; -- practica-me-mori-de-risa: ¡Qué linda sonrisa!
update public.sentences set status = 'retired', updated_at = now() where id = '21053d2e-8b6a-57f2-9870-dd30d29e8761' and status = 'published'; -- practica-me-mori-de-risa: Me encanta la comedia.
update public.sentences set status = 'retired', updated_at = now() where id = '41b26b2b-3355-5c18-9c7a-ec9f429760fa' and status = 'published'; -- practica-me-mori-de-risa: Salgo antes de la hora pico.
update public.sentences set status = 'retired', updated_at = now() where id = '71bed803-d8d2-55db-8c93-3e5fe4ca737c' and status = 'published'; -- practica-me-mori-de-risa: Cuanto antes lleguemos, mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '974d91e3-9410-5b48-96c3-335daadcd366' and status = 'published'; -- practica-me-mori-de-risa: ¿Es gratis? ¡Tanto mejor!
update public.sentences set status = 'retired', updated_at = now() where id = '2b1aec0e-03d1-51b8-9dcd-b205fe65d395' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: ¿Estás manija y querés salir ya? Tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '5f0f4db9-b39a-5ba4-aa29-4e18ab8bb357' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: Si además de rico es barato, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '92a081c8-f3ff-50a3-be40-e5f6822b3774' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: Si la película te hace reír, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '2cbdc4c7-8867-5359-8cac-7f17d90c351a' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: Si me hacés la gamba, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '42fa1849-3a9e-565c-91c1-ab57b57ab98a' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: ¿Nadie en la pileta? ¡Tanto mejor!
update public.sentences set status = 'retired', updated_at = now() where id = '09a735a4-7497-5339-bda3-3f9c50cce907' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: No hay fila hoy, tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '2785112e-c1c9-5193-a3dd-f734e8d84e61' and status = 'published'; -- practica-me-mori-de-risa shrink tanto mejor: ¿Es una comedia? Tanto mejor.
update public.sentences set status = 'retired', updated_at = now() where id = '2491424e-9f2d-55cb-8310-57ef74f6fb0e' and status = 'published'; -- practica-me-hace-ruido: Algo no me cierra.
update public.sentences set status = 'retired', updated_at = now() where id = 'd4aaacd0-414c-573b-82fc-2b0bd122a544' and status = 'published'; -- practica-me-hace-ruido: Lo que dijo no me cierra.
update public.sentences set status = 'retired', updated_at = now() where id = '6892d097-99f9-5e6a-8d70-4ba06da5acec' and status = 'published'; -- se-instalaron-en-la-boca shrink conservaron: Mis abuelos conservaron los muebles que trajeron de Europa.
update public.sentences set status = 'retired', updated_at = now() where id = 'b9b1facf-acf2-5ae8-9702-f069828d89d5' and status = 'published'; -- se-instalaron-en-la-boca shrink conservaron: Conservaron la tradición de los ravioles del domingo.
update public.sentences set status = 'retired', updated_at = now() where id = '41ca4b48-399f-581b-9642-4da77d42d778' and status = 'published'; -- practica-se-instalaron: Vivían en un conventillo.
update public.sentences set status = 'retired', updated_at = now() where id = '97ed8d19-3aa9-51e0-bfc6-676df7cc307c' and status = 'published'; -- me-emocione: Mi hermano está agradecido.
update public.sentences set status = 'retired', updated_at = now() where id = '472af1a9-ae36-5047-93bf-82343eaf9e71' and status = 'published'; -- me-emocione: Mi mamá está muy agradecida.
update public.sentences set status = 'retired', updated_at = now() where id = 'c8cf8f21-d9d8-5248-b1a2-179d13da9078' and status = 'published'; -- practica-se-emociono: ¿Por qué se picó Nico?
update public.sentences set status = 'retired', updated_at = now() where id = '5c385e08-c486-5607-9d28-0d5674adc005' and status = 'published'; -- practica-se-emociono: ¿Se picó tu hermana?
update public.sentences set status = 'retired', updated_at = now() where id = 'a68413d5-4a48-5284-95e3-bf2d0e09ee5b' and status = 'published'; -- practica-se-emociono: Era un chiste, pero se picó.
update public.sentences set status = 'retired', updated_at = now() where id = 'e32bee26-4d3a-547c-a80f-00105bad7951' and status = 'published'; -- practica-se-emociono: Juli se picó con el chiste.
update public.sentences set status = 'retired', updated_at = now() where id = 'c81341bd-e7a5-5735-b998-787add6e67c7' and status = 'published'; -- practica-se-emociono: Le dije que estaba exagerando y se picó.
update public.sentences set status = 'retired', updated_at = now() where id = 'fb18e279-54d7-52b1-8dcc-f0a067f6d17a' and status = 'published'; -- practica-se-emociono: Mi viejo se picó con el apodo.
update public.sentences set status = 'retired', updated_at = now() where id = '7d3e397e-6508-5b36-ac51-4a9b308d660e' and status = 'published'; -- practica-se-emociono: Gracias de corazón.
update public.sentences set status = 'retired', updated_at = now() where id = 'df6f8e13-2e46-5734-9de3-6862cf3199de' and status = 'published'; -- practica-se-emociono: Esa canción me llegó.
update public.sentences set status = 'retired', updated_at = now() where id = '3413dee3-1160-5c55-84a1-ff3eaea2147c' and status = 'published'; -- practica-se-emociono: Nos emocionamos un montón.
update public.sentences set status = 'retired', updated_at = now() where id = '68718cb4-2622-5c03-8555-a196fa708513' and status = 'published'; -- practica-se-emociono: Lo dijo con el corazón.
update public.sentences set status = 'retired', updated_at = now() where id = 'bd281f33-2f52-584a-9ed2-6eed3a44f575' and status = 'published'; -- gracias-por-todo shrink me despido: Me despido de mi abuela antes del viaje.
delete from public.lesson_slots where sentence_id in (select id from public.sentences where status = 'retired');
