-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '73fd97d5-bdd1-55a6-889b-4ba0e1f184ca', position = 7 where id = 'af6f77ff-77ce-5b54-8920-1c1cb01f8c58'; -- respuesta
update public.forms set unit_id = '22f748c4-e86a-57f2-8dfc-09a4885d1d24', position = 8 where id = 'b4abdc00-6d1e-5727-b25f-527536fb6772'; -- aguanto
update public.forms set unit_id = '22f748c4-e86a-57f2-8dfc-09a4885d1d24', position = 9 where id = '949f9d7b-b641-573a-99d9-755840daf3ae'; -- aguantar
