-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------






insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('032b1849-d8ad-582f-aead-e7fc1a5632d9', '28c63305-e8f7-5eef-9891-36b4bbbfbc75', 'me merezco', '{"person":1,"number":"sg","tense":"pres","mood":"ind","clitic":true,"irregular":true}'::jsonb, 'I deserve', null, '80d9fccd-c824-5946-8cce-04ecc42e570d', 4, false, null, null, 'draft'),
  ('bca267dd-fbe8-5f69-8e4c-e0bf3d8ea936', '28c63305-e8f7-5eef-9891-36b4bbbfbc75', 'te merecés', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true,"clitic":true}'::jsonb, 'you deserve', null, '80d9fccd-c824-5946-8cce-04ecc42e570d', 5, false, null, null, 'draft')
on conflict do nothing;




