-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------






insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('56d26b76-ae4a-559c-b68b-2c93fee5d665', '28c63305-e8f7-5eef-9891-36b4bbbfbc75', 'me lo merezco', '{"person":1,"number":"sg","tense":"pres","mood":"ind","clitic":true,"irregular":true}'::jsonb, 'I deserve it', null, '80d9fccd-c824-5946-8cce-04ecc42e570d', 6, false, null, null, 'draft'),
  ('5b06ceef-b8fb-55e0-8c36-282bdc40e15c', '28c63305-e8f7-5eef-9891-36b4bbbfbc75', 'te lo merecés', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true,"clitic":true}'::jsonb, 'you deserve it', null, '80d9fccd-c824-5946-8cce-04ecc42e570d', 7, false, null, null, 'draft')
on conflict do nothing;




