-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '24068540-4ffd-5c2c-86cb-1c89c0f669d6', position = 9 where id = 'ee55a180-7ef0-5961-8be5-e34d2d6ae462'; -- avisado
update public.forms set unit_id = '24068540-4ffd-5c2c-86cb-1c89c0f669d6', position = 8 where id = '0bd5304d-04af-5d19-a208-d381e0b0b333'; -- llamado
update public.forms set unit_id = '35957a48-3965-592b-a5e7-2adfd23edfc0', position = 1 where id = 'c66b6127-5e10-59aa-b56e-193a28260284'; -- opino
update public.forms set unit_id = '35957a48-3965-592b-a5e7-2adfd23edfc0', position = 2 where id = '5e5a4295-176f-563b-beb3-8c36f13a64d8'; -- opinás
update public.forms set unit_id = '36036d7c-a216-5b60-a76c-a59bf988487b', position = 5 where id = '7f99efe2-bc74-562a-89fa-42b98f437166'; -- vergüenza
update public.forms set unit_id = 'd7488f2f-ab30-530b-a0f2-9b26a8cb04ad', position = 3 where id = 'cc7d2d48-0a7f-5d06-8630-b8f0d00b3fcd'; -- funciona
update public.forms set unit_id = 'd7488f2f-ab30-530b-a0f2-9b26a8cb04ad', position = 4 where id = 'ceac34cb-1e45-57b8-8e4a-c84e6355722c'; -- funcionan
update public.forms set unit_id = 'd7488f2f-ab30-530b-a0f2-9b26a8cb04ad', position = 5 where id = '2d77ae2f-9393-5e07-8f16-506dd3edbf9c'; -- arreglar
update public.forms set unit_id = 'd7488f2f-ab30-530b-a0f2-9b26a8cb04ad', position = 6 where id = '78c639ba-5504-51dc-b59a-f8f9d41b8119'; -- arregló
update public.forms set unit_id = '4cba4d7d-a414-57c7-9ed9-cbf8046345e2', position = 8 where id = '0382c6fd-2b41-5bbe-8af0-4baff6fcba6c'; -- chorizo
