-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = 'e38a0b51-167e-583b-a179-5eafde3573f0', position = 10 where id = 'd11e1d02-d871-5bc2-b977-4eac127ad09b'; -- trucho
update public.forms set unit_id = 'e38a0b51-167e-583b-a179-5eafde3573f0', position = 11 where id = '57f19d73-eae4-5971-afb6-9e1079fe1410'; -- trucha
