-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------





insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('325dfadb-1986-540b-856b-4b3221d69787', 'eso', 'pron', 'that', null, 'neutral', false, null, 'draft'),
  ('72ab77ae-2c89-552e-b35d-ed2699d1852f', 'esto', 'pron', 'this', null, 'neutral', false, null, 'draft'),
  ('2a98cef9-ba3e-589e-bb20-830429411f70', 'perdón', 'interj', 'sorry', null, 'neutral', false, null, 'draft'),
  ('c9b8e671-60c4-55a8-9f9c-0f0593be7307', 'uy', 'interj', 'oh no, whoa', null, 'neutral', false, null, 'draft'),
  ('1d153b6a-dc80-5e40-aa78-8638f1d95bf8', 'quién', 'pron', 'who', null, 'neutral', false, null, 'draft')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('11366e70-c245-5324-93e0-bd0dcb8c1413', '325dfadb-1986-540b-856b-4b3221d69787', 'eso', '{}'::jsonb, null, null, '5fa3a1dc-bfbe-5b52-a8fb-880e0f0b7173', 7, false, null, null, 'draft'),
  ('6f728516-9c03-54d3-9d4a-651b4c5313fe', '72ab77ae-2c89-552e-b35d-ed2699d1852f', 'esto', '{}'::jsonb, null, null, '5fa3a1dc-bfbe-5b52-a8fb-880e0f0b7173', 8, false, null, null, 'draft'),
  ('1b349bc2-5895-5047-a40c-f0d4da1bd12c', 'b3a15f68-a07c-5f20-8b7a-ff5a502172c7', 'comprar', '{"verb_form":"inf"}'::jsonb, 'to buy', null, '577ff67b-76f7-513b-adca-5871bbb950dc', 9, false, null, null, 'draft'),
  ('ea877a4b-8d12-5412-bf29-ac16c36bf180', '2a98cef9-ba3e-589e-bb20-830429411f70', 'perdón', '{}'::jsonb, null, null, '20eecfc9-6b84-54ae-aedc-1c389863baf9', 10, false, null, null, 'draft'),
  ('1fa57de0-0baa-57b6-b0be-6a3405d9aed5', 'c9b8e671-60c4-55a8-9f9c-0f0593be7307', 'uy', '{}'::jsonb, null, null, '20eecfc9-6b84-54ae-aedc-1c389863baf9', 11, false, null, null, 'draft'),
  ('f96f0902-45fe-5673-8523-21679c090782', '1d153b6a-dc80-5e40-aa78-8638f1d95bf8', 'quién', '{}'::jsonb, null, null, '0b94d24b-0ce7-5a34-a580-2ef059801e5e', 4, false, null, null, 'draft')
on conflict do nothing;




