-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------



insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('6b7db714-a7d3-59d2-b464-6b3f32934f78', '5d9cbffe-c740-5cbb-b69d-8c5b6440d6c6', 'estar', '{"verb_form":"inf"}'::jsonb, 'to be (how, where)', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 28, false, null, null, 'draft'),
  ('e6900f56-2c63-5aed-a202-5bb09bf3761d', 'c82073fd-0c65-5d66-9bd2-81cef66b47e0', 'escribir', '{"verb_form":"inf"}'::jsonb, 'to write', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 29, false, null, null, 'draft'),
  ('efd8c9fd-836e-57f0-bb9c-f9f70d6e6570', 'a6a9f7ca-4b38-59ef-bb3a-6f5780e92de5', 'ver', '{"verb_form":"inf"}'::jsonb, 'to see', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 30, false, null, null, 'draft'),
  ('fb85e909-3c1b-544f-9bc6-e38dee3dfacc', '89e45286-d945-5f42-9a0b-beb8ead3fb9f', 'entender', '{"verb_form":"inf"}'::jsonb, 'to understand', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 31, false, null, null, 'draft'),
  ('2c3267b0-22ae-548d-ba38-647bd6de495c', 'f8570cab-35e9-52e7-bcd7-70aa3b0a7a15', 'abrir', '{"verb_form":"inf"}'::jsonb, 'to open', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 32, false, null, null, 'draft'),
  ('48ea8cd6-ac98-5724-bc7a-04e7a338cab9', 'a4f93c5c-f70d-5d66-a7f2-ab38c0e26c15', 'saber', '{"verb_form":"inf"}'::jsonb, 'to know', null, '740b6205-cb92-54dc-806f-96cc347f8ee0', 33, false, null, null, 'draft'),
  ('318beb64-4395-522a-97e6-ffc6cbe9d752', '1c74d674-430e-539b-b6b7-39c28bf4326a', 'volver', '{"verb_form":"inf"}'::jsonb, 'to come back, to go back', null, 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', 7, false, null, null, 'draft'),
  ('250a4c57-0ebb-5965-b85e-44f613945856', '5b62af3b-e8fc-5569-a120-eaefdc16eaef', 'venir', '{"verb_form":"inf"}'::jsonb, 'to come', null, '3376ea65-8afe-56be-bae8-b5d06b46c9cd', 3, false, null, null, 'draft'),
  ('49c6b8bc-0fd4-5f58-97bc-9672955fcda0', 'bbedb687-226b-51f0-82ab-0d245b73fe7c', 'decir', '{"verb_form":"inf"}'::jsonb, 'to say, to tell', null, '3376ea65-8afe-56be-bae8-b5d06b46c9cd', 7, false, null, null, 'draft'),
  ('1f9b2710-b71a-5e4e-b4a1-814a7d0a9d03', 'ddef54fa-fb1c-5679-afd1-d9db9c14272b', 'pasar', '{"verb_form":"inf"}'::jsonb, 'to pass, to come by', null, '3376ea65-8afe-56be-bae8-b5d06b46c9cd', 13, false, null, null, 'draft'),
  ('94332f93-1064-506e-a4bf-77b3e333d7d9', '1142f00c-d24d-59a2-926f-8f80c5a787b7', 'pagar', '{"verb_form":"inf"}'::jsonb, 'to pay', null, 'd8cb78a0-5a7d-5c09-9f7f-9e905e0d2e59', 7, false, null, null, 'draft'),
  ('24484073-86a1-5f8a-a7cd-ea0ccd8699bb', '2bc0b8a1-cdf5-5489-9f5f-ab9612dc0078', 'dar', '{"verb_form":"inf"}'::jsonb, 'to give', null, '9230420b-8a48-5c4b-b9d9-b7dc3c12bb5d', 18, false, null, null, 'draft'),
  ('212d2eca-ad54-5266-9e67-b15026e43133', 'eb9e7009-2c16-558f-ae6d-48e31488ba8a', 'gustarían', '{"person":3,"number":"pl","tense":"cond","mood":"ind"}'::jsonb, 'would like (them)', null, '41b8c894-067c-540c-88b8-1a334f63f9e2', 2, false, null, null, 'draft'),
  ('ee1abcb0-0035-57cc-95de-4b2ae3f35a1a', '254eb487-911c-5a17-8b85-08e30bff7755', 'encantarían', '{"person":3,"number":"pl","tense":"cond","mood":"ind"}'::jsonb, 'would love (them)', null, '41b8c894-067c-540c-88b8-1a334f63f9e2', 4, false, null, null, 'draft'),
  ('71201e37-2c4b-555d-8963-5a87735ca431', 'f141a675-dc2e-5e9a-835a-2a5e4d767902', 'interesaría', '{"person":3,"number":"sg","tense":"cond","mood":"ind"}'::jsonb, 'would interest', null, '41b8c894-067c-540c-88b8-1a334f63f9e2', 5, false, null, null, 'draft')
on conflict do nothing;




