-- Glosses: US English, and senses the gloss was missing (tocar is also "to touch" and "to play"). Senses are separated by "; ". Each update only applies if the gloss is still the old one.
update public.lemmas set gloss_en = 'to touch; to play (an instrument); to be someone''s turn' where lemma = 'tocar' and gloss_en = 'to be someone''s turn';
update public.lemmas set gloss_en = 'health; cheers; bless you' where lemma = 'salud' and gloss_en = 'cheers';
update public.lemmas set gloss_en = 'letter; menu' where lemma = 'carta' and gloss_en = 'menu';
update public.lemmas set gloss_en = 'small, little; kid, boy' where lemma = 'chico' and gloss_en = 'small';
update public.lemmas set gloss_en = 'to use; to wear' where lemma = 'usar' and gloss_en = 'to use';
update public.lemmas set gloss_en = 'delighted; nice to meet you' where lemma = 'encantado' and gloss_en = 'delighted';
update public.lemmas set gloss_en = 'to check, to go over' where lemma = 'revisar' and gloss_en = 'to go over, to review';
update public.lemmas set gloss_en = 'apparently, seemingly' where lemma = 'aparentemente' and gloss_en = 'seemingly';
update public.lemmas set gloss_en = 'teacher, educator' where lemma = 'docente' and gloss_en = 'educator, teaching staff';
update public.lemmas set gloss_en = 'to steal, to swipe' where lemma = 'afanar' and gloss_en = 'to nick, to swipe';
update public.lemmas set gloss_en = 'the check, the bill; account' where lemma = 'cuenta' and gloss_en = 'the bill';
update public.lemmas set gloss_en = 'doubt; question' where lemma = 'duda' and gloss_en = 'doubt, query';
update public.lemmas set gloss_en = 'question, inquiry' where lemma = 'consulta' and gloss_en = 'inquiry';
update public.lemmas set gloss_en = 'bill (money), banknote' where lemma = 'billete' and gloss_en = 'banknote';
update public.lemmas set gloss_en = 'teacher, schoolteacher' where lemma = 'maestro' and gloss_en = 'schoolteacher';
update public.lemmas set gloss_en = 'fine, (traffic) ticket' where lemma = 'multa' and gloss_en = 'traffic fine, penalty';
update public.lemmas set gloss_en = 'patio, backyard' where lemma = 'patio' and gloss_en = 'courtyard, patio';
update public.lemmas set gloss_en = 'shame, pity' where lemma = 'lástima' and gloss_en = 'pity';
update public.lemmas set gloss_en = 'store, shop' where lemma = 'local' and gloss_en = 'shopfront, premises';
update public.lemmas set gloss_en = 'final (of a tournament)' where lemma = 'final' and gloss_en = 'title match, last game of a cup';
update public.lemmas set gloss_en = 'apparently' where lemma = 'al parecer' and gloss_en = 'by all accounts';
update public.lemmas set gloss_en = 'great, awesome' where lemma = 'genial' and gloss_en = 'brilliant';
update public.lemmas set gloss_en = 'fall, autumn' where lemma = 'otoño' and gloss_en = 'autumn';
update public.lemmas set gloss_en = 'trash, garbage' where lemma = 'basura' and gloss_en = 'rubbish, trash';
update public.lemmas set gloss_en = 'data (on your phone)' where lemma = 'datos' and gloss_en = 'mobile data';
update public.lemmas set gloss_en = 'vaccine, shot' where lemma = 'vacuna' and gloss_en = 'vaccine, jab';
update public.lemmas set gloss_en = 'burned out, fried' where lemma = 'quemado' and gloss_en = 'burnt out, fried';
update public.lemmas set gloss_en = 'small savory cracker' where lemma = 'bizcochito' and gloss_en = 'small savory biscuit';
update public.lemmas set gloss_en = 'to burn, to get burned' where lemma = 'quemarse' and gloss_en = 'to burn, to get burnt';
update public.lemmas set gloss_en = 'to tie' where lemma = 'empatar' and gloss_en = 'to draw, to tie';
update public.lemmas set gloss_en = 'to get clogged, to get blocked' where lemma = 'taparse' and gloss_en = 'to get blocked';
update public.forms f set gloss_en = 'we tied' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'empatar' and f.form = 'empatamos' and f.gloss_en = 'we drew';
update public.forms f set gloss_en = 'they tied' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'empatar' and f.form = 'empataron' and f.gloss_en = 'they drew';
update public.forms f set gloss_en = 'they stole it (from me), I got robbed' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'afanar' and f.form = 'me afanaron' and f.gloss_en = 'they nicked it (from me)';
update public.forms f set gloss_en = 'bills (money), banknotes' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'billete' and f.form = 'billetes' and f.gloss_en = 'banknotes';
update public.forms f set gloss_en = 'got clogged, got blocked' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'taparse' and f.form = 'se tapó' and f.gloss_en = 'got blocked';
update public.forms f set gloss_en = 'I use; I wear' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'usar' and f.form = 'uso' and f.gloss_en = 'I use';
update public.forms f set gloss_en = 'you use; you wear' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'usar' and f.form = 'usás' and f.gloss_en = 'you use';
update public.forms f set gloss_en = 'uses, wears (he/she)' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'usar' and f.form = 'usa' and f.gloss_en = 'uses (he/she uses)';
update public.forms f set gloss_en = 'they use; they wear' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'usar' and f.form = 'usan' and f.gloss_en = 'they use';
update public.forms f set gloss_en = 'check, go over' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'revisar' and f.form = 'revisá' and f.gloss_en = 'go over, review';
update public.forms f set gloss_en = 'I checked, I went over' from public.lemmas l where l.id = f.lemma_id and l.lemma = 'revisar' and f.form = 'revisé' and f.gloss_en = 'I went over, I reviewed';
update public.forms set gloss_en = 'you give me a ride, you take me' where form = 'me llevás' and gloss_en = 'you give me a lift, you take me';
update public.forms set gloss_en = 'practicing' where form = 'practicando' and gloss_en = 'practising';
update public.forms set gloss_en = 'you traveled around' where form = 'recorriste' and gloss_en = 'you travelled around';
update public.forms set gloss_en = 'they traveled around' where form = 'recorrieron' and gloss_en = 'they travelled around';
update public.forms set gloss_en = 'candy, treats' where form = 'golosinas' and gloss_en = 'sweets, treats';
update public.forms set gloss_en = 'give a ride, take (that I, that he/she take)' where form = 'lleve' and gloss_en = 'give a lift, take (that I, that he/she take)';
update public.forms set gloss_en = 'I burned it (it got burned)' where form = 'se me quemó' and gloss_en = 'I burnt (it got burnt)';
update public.forms set gloss_en = 'I burned them' where form = 'se me quemaron' and gloss_en = 'I burnt (them)';
update public.forms set gloss_en = 'he canceled, she canceled' where form = 'canceló' and gloss_en = 'he cancelled, she cancelled';
