-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '7f39f4c5-591c-51f7-9f82-ca7f7a1cfb2b', position = 13 where id = '5d38009f-1b5c-504a-b2de-c4b067edd3cc'; -- me ayudás
