-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b', position = 21 where id = '8867761c-2969-52db-bb60-35561af06b39'; -- aviso
update public.forms set unit_id = '2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b', position = 22 where id = '37a4e68e-1bd4-5fea-9af2-5815243ca05f'; -- avisás
update public.forms set unit_id = '2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b', position = 23 where id = '8e8826c8-2c7a-5875-99c7-2fcdd0e35c5c'; -- avisame
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 23 where id = '466b1e3a-2a10-52b9-ab98-53ae81443c99'; -- pienso
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 24 where id = '4da25e42-244f-56a8-8415-3375dd44ff5c'; -- pensás
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 25 where id = '3d22ad09-201f-52a7-bef7-01bde1699a83'; -- piensa
update public.forms set unit_id = '7f39f4c5-591c-51f7-9f82-ca7f7a1cfb2b', position = 35 where id = '8ba32b18-afc3-5381-92a2-ce577c046b50'; -- extraño
update public.forms set unit_id = '7f39f4c5-591c-51f7-9f82-ca7f7a1cfb2b', position = 36 where id = 'bbe0213a-265d-57b4-840c-ee03254f22c1'; -- extrañás
update public.forms set unit_id = '7f39f4c5-591c-51f7-9f82-ca7f7a1cfb2b', position = 37 where id = 'c791a3c0-7194-5a6b-810d-22ac3b4f3ad4'; -- extraña
update public.forms set unit_id = '714e2bff-95e1-5d03-96ef-a779c76932b7', position = 14 where id = 'be3d3385-5e53-5f3b-af19-e31e8cdc3dea'; -- dejo
update public.forms set unit_id = '714e2bff-95e1-5d03-96ef-a779c76932b7', position = 15 where id = '476c1f5f-3b91-5e4b-9a4a-bdd4e2913adf'; -- dejás
update public.forms set unit_id = '714e2bff-95e1-5d03-96ef-a779c76932b7', position = 16 where id = '4ab3d9a6-e1d4-5d55-b264-528e7e1ce7b5'; -- dejame
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 26 where id = 'f44e7ae0-33fa-5921-b778-d474cfab120d'; -- creo
update public.forms set unit_id = 'ba4a74c0-9dbd-5b9f-9f9c-e2c7ec49c749', position = 27 where id = 'daaf7871-6257-5db1-b67b-56b78d71905f'; -- creés
