-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------





insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('1e585fa0-8607-5952-a71c-1829698583ad', 'por', 'prep', 'for, through, by', null, 'neutral', true, null, 'draft')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('22b3a537-7a0a-58d6-853b-c5c2cb857345', '1e585fa0-8607-5952-a71c-1829698583ad', 'por', '{}'::jsonb, null, null, 'b2e41f0e-04f0-5a3b-94eb-850cd2d57575', 8, false, null, null, 'draft')
on conflict do nothing;




