-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = 'ecf3c9a9-33e3-5e2e-b2b7-aa09f082c128', position = 15 where id = 'f674ed42-32b8-5724-a2f5-43e4f08bd5d5'; -- tostado
update public.forms set unit_id = '714e2bff-95e1-5d03-96ef-a779c76932b7', position = 17 where id = '4484c76d-4a3c-5ec9-b864-82b7f53ce234'; -- llego
update public.forms set unit_id = 'a47573dd-a997-5b77-acd6-3b206415f578', position = 29 where id = '59ae363e-dcbd-548b-9e36-8b645102593a'; -- pibes
update public.forms set unit_id = '3376ea65-8afe-56be-bae8-b5d06b46c9cd', position = 22 where id = '9490e655-1378-518e-8333-408949e792b7'; -- dame
update public.forms set unit_id = '14b391bd-5db8-50a4-a988-428361e7752a', position = 24 where id = 'eda809df-4d19-5259-a84a-7947923c94d1'; -- sacar
update public.forms set unit_id = 'fa694c27-06c1-5cf3-b5c7-d369f495abbf', position = 16 where id = '267d3881-4926-5c53-a830-99f97b308579'; -- Mendoza
update public.forms set unit_id = '9ed0dbbb-2500-5957-b946-27d34bce9614', position = 18 where id = 'a875b218-835c-57d2-a529-fbc1d78e0366'; -- cuarto
update public.forms set unit_id = '364e1a73-f26c-5d78-9757-4d096939ebda', position = 10 where id = '390e4170-6848-5b19-8e51-477ecbe3b5bb'; -- sidra
update public.forms set unit_id = '102a20da-507c-5cab-8d54-b9dc250aebb6', position = 19 where id = 'd8d95aa8-f7c8-54a2-ab57-0a6f34ddeb1c'; -- Mundial
update public.forms set unit_id = '2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b', position = 24 where id = '1ba61278-e551-5d45-97fb-191905f47cc8'; -- escucho
update public.forms set unit_id = '2d151075-cd8d-51b2-9e1c-bf5a34e4ef1b', position = 25 where id = 'ac4bb78e-536d-51ac-abd9-1c06e2ce3104'; -- escuchás
update public.forms set unit_id = '3376ea65-8afe-56be-bae8-b5d06b46c9cd', position = 24 where id = '00cad462-3f66-594e-9b12-bd593f3170f7'; -- poné
update public.forms set unit_id = '8a2211a4-bc2b-5df6-bfd3-ed761ce08c9a', position = 22 where id = 'bea271c6-3c07-5dea-a7dd-b46e0f137a46'; -- dolor
update public.forms set unit_id = '86e40753-5eaa-5ab6-b540-6a6f01c756b5', position = 34 where id = '6dbb5c51-14cb-524e-8b2d-0ba331755bb3'; -- merienda
update public.forms set unit_id = '28d6c921-dae2-50d2-b6a0-a5e2423428a6', position = 14 where id = 'e5b6285e-ae89-5f02-8788-5c223ba3e6e8'; -- recomendás
update public.forms set unit_id = '28d6c921-dae2-50d2-b6a0-a5e2423428a6', position = 13 where id = '9f248d38-a47a-5c47-8126-d04c16380ca9'; -- me recomendás
update public.forms set unit_id = 'b3f216c5-d105-552a-b3f1-254cee4747b1', position = 29 where id = 'a974d264-c100-59c2-8e38-dbabc8115210'; -- probar
update public.forms set unit_id = '8c4c452e-c6f6-5f26-a9a5-ded2342f7c9f', position = 10 where id = '9e65cc89-fa82-5a4e-be1d-d6fb74ccf98d'; -- ni idea
update public.forms set unit_id = '7799d9a3-02e3-5465-af9f-63e41620d4a7', position = 13 where id = 'aa41827a-f685-594d-a928-2ffd69190f04'; -- debés
update public.forms set unit_id = 'b3f216c5-d105-552a-b3f1-254cee4747b1', position = 27 where id = '6e887719-65ff-5fab-a30d-d51e19ed17f7'; -- me queda
update public.forms set unit_id = 'da8af0c4-83d8-570d-a76d-ba9f8a8d4161', position = 7 where id = 'e60ceacd-7981-5ed7-9c0e-8bc412f02280'; -- olvidó
update public.forms set unit_id = '08e5edec-37ff-59c8-942b-b0fcd4fe251b', position = 17 where id = '7961af4d-2fbd-58a3-845e-3f7716f10749'; -- se me hizo tarde
update public.forms set unit_id = '533e4252-0503-516b-9b3f-fcc7fad29ce1', position = 13 where id = '87d1fadf-25bc-5f17-bf18-af28374d3bb3'; -- anda
update public.forms set unit_id = 'e4a7439f-a626-5e82-abaf-06bc10e30be8', position = 16 where id = '3556dd85-57a1-57a4-abcb-136dfa366c8f'; -- expensas
update public.forms set unit_id = '8c4c452e-c6f6-5f26-a9a5-ded2342f7c9f', position = 9 where id = '3d905cae-da8e-5328-9f36-8a36273e5294'; -- para mí
update public.forms set unit_id = 'e27cb9dd-52ff-5eed-8b6b-7f5680e6ae7f', position = 15 where id = 'e6893f63-3a11-5379-a27e-471872a037f0'; -- clave
update public.forms set unit_id = 'a6c406c0-0103-5fcc-9871-5e1bc85a3833', position = 26 where id = '7f99efe2-bc74-562a-89fa-42b98f437166'; -- vergüenza
update public.forms set unit_id = '36b953db-b59d-5c37-8572-47afd0081c48', position = 12 where id = '2ae8f641-19a7-54f0-b017-e7ce09db4020'; -- creer
update public.forms set unit_id = 'dd303fe0-52c5-5e61-97ae-1903616e625c', position = 1 where id = '11b803d1-b113-5f22-bec8-cf6bb2138420'; -- hace cuánto
update public.forms set unit_id = 'b3f216c5-d105-552a-b3f1-254cee4747b1', position = 28 where id = 'efdb50f3-1c5f-5fc7-a6bb-a6f6402d7d48'; -- probador
update public.forms set unit_id = '7c33a900-8b22-5a9e-a34e-7c274e6a21b0', position = 17 where id = '382187de-0a0b-5800-95aa-69c0d95ed3b5'; -- vuelo
update public.forms set unit_id = '35957a48-3965-592b-a5e7-2adfd23edfc0', position = 15 where id = '9c2f280d-0ec2-55b6-b47e-758615428636'; -- nada que ver
update public.forms set unit_id = 'd7a7375d-a258-5d7a-ae1c-44811ac8b58d', position = 13 where id = '8f22168b-7217-510f-a7ff-7b0c2871a120'; -- ojo
update public.forms set unit_id = 'e4a7439f-a626-5e82-abaf-06bc10e30be8', position = 21 where id = '06df6c1e-d1b8-5ebd-91a4-b7886a691035'; -- contrato
update public.forms set unit_id = 'e4a7439f-a626-5e82-abaf-06bc10e30be8', position = 20 where id = '3d96b8a6-9f74-59f4-ae38-c17efe4e7e94'; -- garantía
update public.forms set unit_id = 'd7488f2f-ab30-530b-a0f2-9b26a8cb04ad', position = 18 where id = '06adf4bb-5b6d-51cc-a8b3-0ddf8adb4541'; -- electricista
update public.forms set unit_id = 'a6c406c0-0103-5fcc-9871-5e1bc85a3833', position = 24 where id = '866c0258-c5f9-5a62-b904-40afd23a0aab'; -- bronca
update public.forms set unit_id = 'a6c406c0-0103-5fcc-9871-5e1bc85a3833', position = 25 where id = '0235d3cb-bca8-5c87-8ddb-a73224ece2aa'; -- lástima
update public.forms set unit_id = '98bdf26a-6fb0-57ec-80b0-092e57969285', position = 9 where id = 'd5c961c9-04c7-5bd4-a4cb-1ee28db0ffbb'; -- cobraron
update public.forms set unit_id = '35957a48-3965-592b-a5e7-2adfd23edfc0', position = 14 where id = '45a9a830-af06-5812-8757-524a4de74bfd'; -- tal cual
update public.forms set unit_id = 'b2e41f0e-04f0-5a3b-94eb-850cd2d57575', position = 9 where id = 'a349c9bc-e64e-5bc8-8f19-a4f6df0da523'; -- acordate
update public.forms set unit_id = 'd585de30-5927-5cbf-a88a-fc998547f793', position = 12 where id = 'f60b0a3f-6c6e-56ac-95b1-247479702311'; -- en blanco
update public.forms set unit_id = 'd585de30-5927-5cbf-a88a-fc998547f793', position = 13 where id = '71a76ae2-2978-573e-a034-958d515a055d'; -- en negro
update public.forms set unit_id = '4093ca08-4709-5a01-b09b-4fd1624d96cf', position = 14 where id = '6c4cd5f0-0570-57b2-862c-cd15d146689a'; -- me enteré
update public.forms set unit_id = '4093ca08-4709-5a01-b09b-4fd1624d96cf', position = 15 where id = 'f55227bf-b104-5805-9406-6113854d4253'; -- te enteraste
update public.forms set unit_id = '4093ca08-4709-5a01-b09b-4fd1624d96cf', position = 16 where id = 'c4772488-f64f-5b67-bba6-29435554adf0'; -- enteré
update public.forms set unit_id = '4093ca08-4709-5a01-b09b-4fd1624d96cf', position = 17 where id = 'f8f8839d-bb42-57ab-ab9d-f3f6a045aeb2'; -- enteraste
update public.forms set unit_id = 'c18ed3f6-ae4d-50fd-b360-6d7e7d73144c', position = 12 where id = 'e428f360-21f1-532f-92a3-607cc76118f7'; -- lo que más
update public.forms set unit_id = '28506229-594f-503e-80d4-5a3a1085320a', position = 12 where id = '8f666427-4fa4-5166-b6af-1e4a79537f75'; -- me expresé mal
update public.forms set unit_id = '28506229-594f-503e-80d4-5a3a1085320a', position = 11 where id = 'e881de35-209d-59db-9d17-4a0f57da588e'; -- quise decir
update public.forms set unit_id = 'b900b7fe-a570-5688-8aa9-d35d025c5c42', position = 21 where id = '8266edb9-10e5-5d5f-92d8-aa64e0966438'; -- Italia
update public.forms set unit_id = 'b900b7fe-a570-5688-8aa9-d35d025c5c42', position = 20 where id = '722a48e9-f4ce-5d2a-a5af-e34b2da5c1a9'; -- España
update public.forms set unit_id = '36b953db-b59d-5c37-8572-47afd0081c48', position = 11 where id = '2b1bde3e-6545-5cde-b46e-f3809f5a320f'; -- felicitaciones
