-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '7713400b-1007-558d-b717-ac7b02078eed', position = 8 where id = 'fbc5d133-8d7d-5e32-869d-a1f28a78962b'; -- esperar
update public.forms set unit_id = 'a56af3ac-cade-5ff7-bdce-38285c0c74e8', position = 16 where id = '60601bce-38fd-55fe-94f0-b749264a0602'; -- distraído
update public.forms set unit_id = 'a56af3ac-cade-5ff7-bdce-38285c0c74e8', position = 17 where id = '31f01d5b-4980-5c07-9057-bc29743c852d'; -- distraída
update public.forms set unit_id = 'a56af3ac-cade-5ff7-bdce-38285c0c74e8', position = 14 where id = 'd0d9e60d-42eb-5468-9ba3-5f3a8d6e9809'; -- tonto
update public.forms set unit_id = 'a56af3ac-cade-5ff7-bdce-38285c0c74e8', position = 15 where id = '111c5995-7211-5042-bca8-45dfb003c5fb'; -- tonta
update public.forms set unit_id = 'ed66a36e-5a88-56f2-a2c7-3fdf72291b4e', position = 4 where id = 'a2b3077c-2ebf-518a-8900-a947ee7c9c75'; -- ruta
