-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------



-- No new lessons: the unit was seeded already; it carries the extra words in the lessons it has.


insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('5ed960fa-e2e5-5a98-b714-3ebb5d03f5ba', 'cuándo', 'adv', 'when (asking)', null, 'neutral', false, null, 'draft')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('3464794d-283a-5c1f-8570-8a20a6a437fe', '5ed960fa-e2e5-5a98-b714-3ebb5d03f5ba', 'cuándo', '{}'::jsonb, null, null, '5f6c9abe-859a-5d19-853a-7dc6bcce9c99', 12, false, null, null, 'draft'),
  ('5f2d3d50-f501-5bee-b087-813a410afe63', '2bc0b8a1-cdf5-5489-9f5f-ab9612dc0078', 'di', '{"person":1,"number":"sg","tense":"pret","mood":"ind","irregular":true}'::jsonb, 'I gave', null, '5f6c9abe-859a-5d19-853a-7dc6bcce9c99', 13, false, null, null, 'draft'),
  ('2d770600-67ac-5e24-b79f-f8313631959b', '2bc0b8a1-cdf5-5489-9f5f-ab9612dc0078', 'diste', '{"person":2,"number":"sg","tense":"pret","mood":"ind","voseo":true,"irregular":true}'::jsonb, 'you gave', null, '5f6c9abe-859a-5d19-853a-7dc6bcce9c99', 14, false, null, null, 'draft'),
  ('fa465a67-fe08-5d4b-b994-13821123be48', '2bc0b8a1-cdf5-5489-9f5f-ab9612dc0078', 'dio', '{"person":3,"number":"sg","tense":"pret","mood":"ind","irregular":true}'::jsonb, 'gave (he/she gave)', null, '5f6c9abe-859a-5d19-853a-7dc6bcce9c99', 15, false, null, null, 'draft'),
  ('ceaf8a79-54ae-5bce-a931-8adc9076b91a', '4e59fa59-5397-5639-a425-56db2db702d5', 'presto', '{"person":1,"number":"sg","tense":"pres","mood":"ind"}'::jsonb, 'I lend', null, '5f6c9abe-859a-5d19-853a-7dc6bcce9c99', 16, false, null, null, 'draft')
on conflict do nothing;




