-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------



-- No new lessons: these units were seeded already, and a longer lesson list
-- would leave their old unit check stranded mid-unit. They carry the extra
-- words in the lessons they have.


insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('a61b7a37-ebe2-5528-adc6-82251b1e63f0', 'claro', 'adv', 'sure, of course', null, 'neutral', false, null, 'draft'),
  ('782ac2b5-8b7f-52ef-ab02-345795d5e180', 'cosa', 'noun', 'thing', null, 'neutral', false, null, 'draft'),
  ('e6e545ba-5fcf-5f6f-89e3-af9efebbd1e9', 'hasta', 'prep', 'until, up to', null, 'neutral', true, null, 'draft'),
  ('8a28841b-0da4-5c5e-a6c2-45c3d02e952e', 'desde', 'prep', 'since, from', null, 'neutral', true, null, 'draft'),
  ('515699e5-7961-5e08-9283-4dfe73790873', 'fácil', 'adj', 'easy', null, 'neutral', false, null, 'draft'),
  ('f3e56f83-fe9c-5ef1-b5f5-15b8872ddb8f', 'difícil', 'adj', 'hard, difficult', null, 'neutral', false, null, 'draft'),
  ('60df0773-fc18-5cf6-b26d-4da5c0057259', 'importante', 'adj', 'important', null, 'neutral', false, null, 'draft'),
  ('3bccdcc3-c8ca-51cc-b395-ce05efa2a030', 'perder', 'verb', 'to lose, to miss', null, 'neutral', false, null, 'draft'),
  ('453aac22-007c-5a7e-a38a-7c678487f00d', 'poner', 'verb', 'to put', null, 'neutral', false, null, 'draft'),
  ('f8570cab-35e9-52e7-bcd7-70aa3b0a7a15', 'abrir', 'verb', 'to open', null, 'neutral', false, null, 'draft'),
  ('cf89a85b-0b32-5e39-a7d9-b7d98c03d822', 'cerrar', 'verb', 'to close', null, 'neutral', false, null, 'draft'),
  ('1879c60b-964a-5104-8d9c-3bfdf5137111', 'empezar', 'verb', 'to start', null, 'neutral', false, null, 'draft'),
  ('1c74d674-430e-539b-b6b7-39c28bf4326a', 'volver', 'verb', 'to come back, to go back', null, 'neutral', false, null, 'draft'),
  ('930632fc-23e5-56ed-8720-e596b2565c51', 'malo', 'adj', 'bad', null, 'neutral', false, null, 'draft'),
  ('d16a8b9b-d04a-5865-8bec-f2a2665cb9df', 'mismo', 'adj', 'same', null, 'neutral', false, null, 'draft'),
  ('a72ffe32-9177-5008-a0ba-e09718e4b437', 'dormir', 'verb', 'to sleep', null, 'neutral', false, null, 'draft'),
  ('3fa4da1b-288c-571e-9613-79f5fe42efab', 'otra vez', 'phrase', 'again', null, 'neutral', false, null, 'draft')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('c771d6c2-ff28-59a2-835a-6401aa611826', 'a61b7a37-ebe2-5528-adc6-82251b1e63f0', 'claro', '{}'::jsonb, null, null, 'dc485e04-124e-516d-9061-98a2d00f4d57', 14, false, null, null, 'draft'),
  ('2ae9f8ea-1866-5e2d-8571-a5381eac1daf', '782ac2b5-8b7f-52ef-ab02-345795d5e180', 'cosa', '{"gender":"f","number":"sg"}'::jsonb, null, null, 'dc485e04-124e-516d-9061-98a2d00f4d57', 15, false, null, null, 'draft'),
  ('319c56ba-1a4e-5b73-a657-ccd1aac4c464', '782ac2b5-8b7f-52ef-ab02-345795d5e180', 'cosas', '{"gender":"f","number":"pl"}'::jsonb, 'things', null, 'dc485e04-124e-516d-9061-98a2d00f4d57', 16, false, null, null, 'draft'),
  ('678b1951-f087-5dd2-a9c4-e1714af9d01d', 'e6e545ba-5fcf-5f6f-89e3-af9efebbd1e9', 'hasta', '{}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 11, false, null, null, 'draft'),
  ('9502388c-4b01-59ce-90e9-5654952cdeb9', '8a28841b-0da4-5c5e-a6c2-45c3d02e952e', 'desde', '{}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 12, false, null, null, 'draft'),
  ('220148a0-67d5-5a3c-8665-aed303b655c6', '515699e5-7961-5e08-9283-4dfe73790873', 'fácil', '{}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 13, false, null, null, 'draft'),
  ('eafdf634-e3bf-538f-85b7-535e2ac581b2', 'f3e56f83-fe9c-5ef1-b5f5-15b8872ddb8f', 'difícil', '{}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 14, false, null, null, 'draft'),
  ('0f52184d-c100-5f70-bf5f-fd7253c31aef', '60df0773-fc18-5cf6-b26d-4da5c0057259', 'importante', '{}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 15, false, null, null, 'draft'),
  ('bb58191b-40ee-5dc8-87ae-3319ef2d3d57', '641f1589-1d62-5296-b620-ef338064e7e2', 'hablar', '{"verb_form":"inf"}'::jsonb, null, null, 'afdaff40-37c8-56af-ae39-78f1ed48e97e', 16, false, null, null, 'draft'),
  ('7d6427d9-131c-598b-a023-792d3342d2df', 'a6a9f7ca-4b38-59ef-bb3a-6f5780e92de5', 'veo', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I see', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 18, false, null, null, 'draft'),
  ('26180d44-16d5-5dc6-93d7-31f3fce9a812', 'a6a9f7ca-4b38-59ef-bb3a-6f5780e92de5', 'ves', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true}'::jsonb, 'you see', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 19, false, null, null, 'draft'),
  ('1ba61278-e551-5d45-97fb-191905f47cc8', '26012c0b-feb3-5194-aef0-83e4f75a3885', 'escucho', '{"person":1,"number":"sg","tense":"pres","mood":"ind"}'::jsonb, 'I hear, I listen', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 20, false, null, null, 'draft'),
  ('ac4bb78e-536d-51ac-abd9-1c06e2ce3104', '26012c0b-feb3-5194-aef0-83e4f75a3885', 'escuchás', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true}'::jsonb, 'you hear, you listen', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 21, false, null, null, 'draft'),
  ('8ea4f486-c2c1-579e-8a4d-f37ddb04330d', '3bccdcc3-c8ca-51cc-b395-ce05efa2a030', 'perdí', '{"person":1,"number":"sg","tense":"pret","mood":"ind"}'::jsonb, 'I lost', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 22, false, null, null, 'draft'),
  ('d8e690ec-3422-5f14-86a1-55d28ccd0a7a', '3bccdcc3-c8ca-51cc-b395-ce05efa2a030', 'perdiste', '{"person":2,"number":"sg","tense":"pret","mood":"ind","voseo":true}'::jsonb, 'you lost', null, 'a921ed27-35b4-5222-9699-d8dd343c1f79', 23, false, null, null, 'draft'),
  ('98569b5d-9eaa-5cb6-82de-6d5289a4247c', '453aac22-007c-5a7e-a38a-7c678487f00d', 'pongo', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I put', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 12, false, null, null, 'draft'),
  ('00cad462-3f66-594e-9b12-bd593f3170f7', '453aac22-007c-5a7e-a38a-7c678487f00d', 'poné', '{"person":2,"number":"sg","mood":"imp","voseo":true}'::jsonb, 'put', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 13, false, null, null, 'draft'),
  ('5fd3bfcc-0ea9-5217-851c-dfbf5294830e', 'f8570cab-35e9-52e7-bcd7-70aa3b0a7a15', 'abrí', '{"person":2,"number":"sg","mood":"imp","voseo":true}'::jsonb, 'open', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 14, false, null, null, 'draft'),
  ('582e4187-4136-5645-9a13-c15247b949e6', 'f8570cab-35e9-52e7-bcd7-70aa3b0a7a15', 'abro', '{"person":1,"number":"sg","tense":"pres","mood":"ind"}'::jsonb, 'I open', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 15, false, null, null, 'draft'),
  ('c7c43171-002f-5cf3-9dcf-6d8d19f3461c', 'cf89a85b-0b32-5e39-a7d9-b7d98c03d822', 'cerrá', '{"person":2,"number":"sg","mood":"imp","voseo":true}'::jsonb, 'close', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 16, false, null, null, 'draft'),
  ('ad520ed4-fd62-5f31-80ba-78905cf5f75c', 'cf89a85b-0b32-5e39-a7d9-b7d98c03d822', 'cierro', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I close', null, '776b15fe-c6a5-5aae-8876-404d392e0546', 17, false, null, null, 'draft'),
  ('7851009d-6999-5910-832c-0304a40bb079', '1879c60b-964a-5104-8d9c-3bfdf5137111', 'empiezo', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I start', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 11, false, null, null, 'draft'),
  ('7505dd35-d79c-5111-8045-3c76b5093a38', '1879c60b-964a-5104-8d9c-3bfdf5137111', 'empezás', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true}'::jsonb, 'you start', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 12, false, null, null, 'draft'),
  ('e9c67e9c-c9aa-5334-8916-ff108b2719b9', '1879c60b-964a-5104-8d9c-3bfdf5137111', 'empecé', '{"person":1,"number":"sg","tense":"pret","mood":"ind"}'::jsonb, 'I started', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 13, false, null, null, 'draft'),
  ('0985d8bd-3748-5a75-a0ad-f39ec14dc8cf', '1c74d674-430e-539b-b6b7-39c28bf4326a', 'vuelvo', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I come back', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 14, false, null, null, 'draft'),
  ('560dee08-6e15-530d-b57b-4d80de14374f', '1c74d674-430e-539b-b6b7-39c28bf4326a', 'volvés', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true}'::jsonb, 'you come back', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 15, false, null, null, 'draft'),
  ('72673162-f903-5d16-a535-80b2469aa7ad', '1c74d674-430e-539b-b6b7-39c28bf4326a', 'volví', '{"person":1,"number":"sg","tense":"pret","mood":"ind"}'::jsonb, 'I came back', null, 'd585de30-5927-5cbf-a88a-fc998547f793', 16, false, null, null, 'draft'),
  ('84e01c84-d379-5aa4-b892-d09f0101d1a0', '930632fc-23e5-56ed-8720-e596b2565c51', 'malo', '{"gender":"m","number":"sg"}'::jsonb, null, null, 'd585de30-5927-5cbf-a88a-fc998547f793', 17, false, null, null, 'draft'),
  ('1af9aebe-bae2-5b69-b3e7-6ecb7a49d64b', '930632fc-23e5-56ed-8720-e596b2565c51', 'mala', '{"gender":"f","number":"sg"}'::jsonb, null, null, 'd585de30-5927-5cbf-a88a-fc998547f793', 18, false, null, null, 'draft'),
  ('b6575a32-3e11-58ff-aad6-780267f89165', 'd16a8b9b-d04a-5865-8bec-f2a2665cb9df', 'mismo', '{"gender":"m","number":"sg"}'::jsonb, null, null, '770b6d5f-bd8c-5c17-a05f-4721faaa1706', 13, false, null, null, 'draft'),
  ('4d0f6199-c1f1-5b62-9583-ab179db63600', 'd16a8b9b-d04a-5865-8bec-f2a2665cb9df', 'misma', '{"gender":"f","number":"sg"}'::jsonb, null, null, '770b6d5f-bd8c-5c17-a05f-4721faaa1706', 14, false, null, null, 'draft'),
  ('10397a81-0a56-567e-9ff0-d67a97c34e0f', 'a72ffe32-9177-5008-a0ba-e09718e4b437', 'duermo', '{"person":1,"number":"sg","tense":"pres","mood":"ind","irregular":true}'::jsonb, 'I sleep', null, '5ec6a727-4a91-5545-9e35-7f858d66ced1', 12, false, null, null, 'draft'),
  ('94996d66-4344-5d0c-843f-a7db5efbd4cf', 'a72ffe32-9177-5008-a0ba-e09718e4b437', 'dormís', '{"person":2,"number":"sg","tense":"pres","mood":"ind","voseo":true}'::jsonb, 'you sleep', null, '5ec6a727-4a91-5545-9e35-7f858d66ced1', 13, false, null, null, 'draft'),
  ('2ca2225a-d184-5c3b-86b5-7be9c8ad20c1', 'a72ffe32-9177-5008-a0ba-e09718e4b437', 'dormí', '{"person":1,"number":"sg","tense":"pret","mood":"ind"}'::jsonb, 'I slept', null, '5ec6a727-4a91-5545-9e35-7f858d66ced1', 14, false, null, null, 'draft'),
  ('d1e638fb-ddd5-5b09-a8c5-474488ed5615', 'a72ffe32-9177-5008-a0ba-e09718e4b437', 'dormir', '{"verb_form":"inf"}'::jsonb, null, null, '5ec6a727-4a91-5545-9e35-7f858d66ced1', 15, false, null, null, 'draft'),
  ('f7c1db2c-dafd-51e2-9b70-b54f30cc1d7e', '3fa4da1b-288c-571e-9613-79f5fe42efab', 'otra vez', '{}'::jsonb, null, null, '6ec21cf5-83ce-55f4-a07c-355a8fb995bb', 7, false, null, null, 'draft')
on conflict do nothing;




