-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

create temporary table reorder_units (id uuid, section_id smallint, ordinal smallint, course_order smallint, old_order smallint) on commit drop;
insert into reorder_units values
  ('80d9fccd-c824-5946-8cce-04ecc42e570d'::uuid, 15, 3, 358, 357),
  ('f1fe8414-a662-5131-9e76-a258572724ea'::uuid, 15, 5, 360, 358),
  ('908f70c9-72c3-5244-b3c8-db86021008ed'::uuid, 15, 7, 362, 359),
  ('6d5e1fa5-986d-5b45-a406-035e7c99c15c'::uuid, 15, 9, 364, 360),
  ('5572cf90-36cf-55e2-824b-80f995d2d968'::uuid, 15, 11, 366, 361),
  ('cf4d6a07-a4c5-5761-9bad-5a84df508105'::uuid, 15, 13, 368, 362),
  ('a5e76c4c-fdd3-5652-89d4-4d7a8341eae7'::uuid, 15, 15, 370, 363),
  ('cc075128-b483-5ba0-a24a-485bd1dc71fa'::uuid, 15, 17, 372, 364),
  ('35da2974-7119-59d7-bdf3-d14bdf042064'::uuid, 15, 19, 374, 365),
  ('a25229c0-af37-50d8-86db-83c809276632'::uuid, 15, 21, 376, 366),
  ('f6864f2a-0faf-53cf-a8b4-9e35f6661b10'::uuid, 15, 23, 378, 367),
  ('c1be6404-2a36-51f7-8d0f-43b1a6d26250'::uuid, 15, 26, 381, 368);

-- Through a free range first: ordinals and course places are unique.
update public.units u set ordinal = 20000 + r.ordinal, course_order = 20000 + r.course_order from reorder_units r where u.id = r.id;
update public.units u set section_id = r.section_id, ordinal = r.ordinal, course_order = r.course_order from reorder_units r where u.id = r.id;

-- A placement or jump test is remembered as a course place.
update public.profiles p set placed_through = r.course_order from reorder_units r where p.placed_through = r.old_order;

