-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------


insert into public.units (id, section_id, ordinal, course_order, slug, title_en, summary_en, grammar_focus, register_max, review_form_ids, status) values
  ('9f62a065-778e-5620-b8e5-de9e6f8c2907', 1, 9, 9, 'no-entiendo', 'Say you don''t understand', 'No entiendo. ¿Hablás inglés?', array['pres.1sg-2sg.vos', 'frases.supervivencia']::text[], 'informal', '{}'::uuid[], 'published'),
  ('5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 1, 21, 21, 'treinta-y-cuatro', 'Count to a hundred and say your real age', 'Tengo treinta y cuatro años', array['numeros.21-100', 'tener.pres.1sg-3sg']::text[], 'informal', '{}'::uuid[], 'published'),
  ('3bfdac76-f836-5268-91f3-0dbfa1c26018', 1, 26, 26, 'cuanto-cuesta', 'Ask what it costs', '¿Cuánto sale?', array['cuanto-sale', 'costar.pres.3', 'numeros.miles']::text[], 'informal', '{}'::uuid[], 'published'),
  ('bde97495-163d-56bd-a579-b524910edfcc', 2, 7, 34, 'adonde-vas', 'Say where you''re going', '¿Adónde vas? Voy a la plaza', array['ir.pres', 'ir-a.lugar', 'contraccion.del-al']::text[], 'informal', '{}'::uuid[], 'published'),
  ('525526ce-1e8d-5672-88f4-02259c8e4533', 2, 13, 40, 'hoy-y-manana', 'Say when: today, tomorrow, now', 'Hoy laburo, mañana no', array['tiempo.hoy-manana-ahora', 'a-la-noche']::text[], 'informal', '{}'::uuid[], 'published'),
  ('26b3f81c-f349-5b38-817b-731bbac652cf', 3, 12, 66, 'este-y-ese', 'Point at things: this one, that one', 'Esa mochila es re linda', array['demostrativos.este-ese', 'demostrativos.neutro', 're.intensificador']::text[], 'informal', '{}'::uuid[], 'published'),
  ('70cf9841-8e17-590c-9fd0-503d47b7b3e1', 3, 13, 67, 'la-campera-nueva', 'Talk about your clothes', 'Esta campera es nueva', array['adj.concordancia', 'ser.descripcion']::text[], 'informal', '{}'::uuid[], 'published'),
  ('694523fc-5d19-5d81-8e08-6083c35d7d25', 4, 2, 82, 'estoy-llegando', 'Say what you''re doing right now', 'Ya estoy llegando', array['estar.gerundio', 'ya-todavia']::text[], 'informal', '{}'::uuid[], 'published'),
  ('59190ff0-c3f5-5d61-bd69-5db02edca9fd', 4, 4, 84, 'que-decis', 'Say, see and put: three everyday verbs', '¿Qué decís? No veo nada', array['decir.pres', 'ver.pres', 'poner.pres']::text[], 'informal', '{}'::uuid[], 'published')
on conflict do nothing;

insert into public.lessons (id, unit_id, ordinal, title_en, kind, status) values
  ('dfe8ce5c-d433-55ae-a703-dccd69c092bc', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 1, 'Lesson 1', 'lesson', 'published'),
  ('5bfbcf98-4a2f-5a03-940d-7c85e1c400b7', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 2, 'Lesson 2', 'lesson', 'published'),
  ('326789ae-f7c6-5378-876c-c9734eeb3570', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 3, 'Lesson 3', 'lesson', 'published'),
  ('e2158ee3-e6db-52ff-ae10-7616528d6d00', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 4, 'Lesson 4', 'lesson', 'published'),
  ('5933285a-98e4-521a-a91e-c31c9ef5fa1f', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 5, 'Lesson 5', 'lesson', 'published'),
  ('2feae90f-7bc5-5c4c-be50-bca592e2f857', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 6, 'Unit check', 'review', 'published'),
  ('f5c42e78-6a59-5a82-a1c4-970f111775ed', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 1, 'Lesson 1', 'lesson', 'published'),
  ('29fdedc6-c22a-55ae-b7f3-34ebaf8eaeff', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 2, 'Lesson 2', 'lesson', 'published'),
  ('fccd4d0d-e13e-5b45-8060-7c08aab98104', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 3, 'Lesson 3', 'lesson', 'published'),
  ('199e6162-fb6a-5458-b380-0175ef6d71bb', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 4, 'Lesson 4', 'lesson', 'published'),
  ('6e0f613e-65f3-5789-ac22-05493032ccf1', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 5, 'Lesson 5', 'lesson', 'published'),
  ('45201055-f0f9-5b39-9a72-196e9f6368ad', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 6, 'Lesson 6', 'lesson', 'published'),
  ('58ec55fe-5ad9-5889-b186-2122f5bb121a', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 7, 'Unit check', 'review', 'published'),
  ('ee9eb4cc-1230-5f0e-aa12-c504b4b541e9', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 1, 'Lesson 1', 'lesson', 'published'),
  ('64804435-f069-5fb0-8cf6-ece5603ab313', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 2, 'Lesson 2', 'lesson', 'published'),
  ('af9cf9da-044d-5e8a-8ba0-dfc784e9b7ad', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 3, 'Lesson 3', 'lesson', 'published'),
  ('8bff26fa-4f53-551d-9dae-ba08c4c15ad4', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 4, 'Lesson 4', 'lesson', 'published'),
  ('94b22a29-e728-54be-b654-995b02331518', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 5, 'Lesson 5', 'lesson', 'published'),
  ('1e61a4de-1ab4-5813-adb3-06d6a4151712', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 6, 'Unit check', 'review', 'published'),
  ('1862cc8f-0382-5326-b9fd-1da9262bac06', 'bde97495-163d-56bd-a579-b524910edfcc', 1, 'Lesson 1', 'lesson', 'published'),
  ('0f4c10b8-8809-5133-82e5-b3e90228476e', 'bde97495-163d-56bd-a579-b524910edfcc', 2, 'Lesson 2', 'lesson', 'published'),
  ('513d2e05-6e6c-51b5-95db-9ec4a8fb7bce', 'bde97495-163d-56bd-a579-b524910edfcc', 3, 'Lesson 3', 'lesson', 'published'),
  ('da03e0b4-85b4-52f5-814a-300e535fcdca', 'bde97495-163d-56bd-a579-b524910edfcc', 4, 'Unit check', 'review', 'published'),
  ('90913516-2853-597a-9514-fd1d4173c93b', '525526ce-1e8d-5672-88f4-02259c8e4533', 1, 'Lesson 1', 'lesson', 'published'),
  ('dd6bd4b5-b5c7-5cd0-80cb-589fb96500d2', '525526ce-1e8d-5672-88f4-02259c8e4533', 2, 'Lesson 2', 'lesson', 'published'),
  ('dfd18695-0b3b-585b-9937-d17eb296c741', '525526ce-1e8d-5672-88f4-02259c8e4533', 3, 'Lesson 3', 'lesson', 'published'),
  ('110a5f17-0002-5c87-b944-a8f5e2d55ef3', '525526ce-1e8d-5672-88f4-02259c8e4533', 4, 'Unit check', 'review', 'published'),
  ('c94e51bf-52ec-5d35-b998-8d2fe16977af', '26b3f81c-f349-5b38-817b-731bbac652cf', 1, 'Lesson 1', 'lesson', 'published'),
  ('f3f87034-5981-5bed-9aa8-660e9fc3803a', '26b3f81c-f349-5b38-817b-731bbac652cf', 2, 'Lesson 2', 'lesson', 'published'),
  ('5c69f67b-ba47-5618-9bdf-ba1d419db705', '26b3f81c-f349-5b38-817b-731bbac652cf', 3, 'Lesson 3', 'lesson', 'published'),
  ('70020723-a231-555c-8e29-640ee235cffe', '26b3f81c-f349-5b38-817b-731bbac652cf', 4, 'Lesson 4', 'lesson', 'published'),
  ('e44b82d1-5744-5d0e-b3e7-1bbe054fdcd3', '26b3f81c-f349-5b38-817b-731bbac652cf', 5, 'Unit check', 'review', 'published'),
  ('5785fb64-6f23-5970-9d6c-cc1b1038f0f4', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 1, 'Lesson 1', 'lesson', 'published'),
  ('b822e7f7-26da-5493-be80-7f9ff0021d58', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 2, 'Lesson 2', 'lesson', 'published'),
  ('bedf661d-9e92-566e-baf4-966a41d95278', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 3, 'Lesson 3', 'lesson', 'published'),
  ('410bd095-292b-54ce-9373-0e3c56e6451e', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 4, 'Lesson 4', 'lesson', 'published'),
  ('48ef4ef2-af53-58a6-aa8f-e0931c21d45f', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 5, 'Lesson 5', 'lesson', 'published'),
  ('546662bc-5881-57e5-bf5d-c054c810ac3b', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 6, 'Lesson 6', 'lesson', 'published'),
  ('c537d7f4-ad38-5392-99de-36fda4947b7b', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 7, 'Unit check', 'review', 'published'),
  ('61a33fe0-12f4-5acc-8a68-106d6f7c7795', '694523fc-5d19-5d81-8e08-6083c35d7d25', 1, 'Lesson 1', 'lesson', 'published'),
  ('e305a349-bed2-598f-b8ad-a6a925678bc6', '694523fc-5d19-5d81-8e08-6083c35d7d25', 2, 'Lesson 2', 'lesson', 'published'),
  ('f6dce1d2-0b22-5ee5-b22d-e98e2800dfdb', '694523fc-5d19-5d81-8e08-6083c35d7d25', 3, 'Lesson 3', 'lesson', 'published'),
  ('a98a3387-3d2f-56ec-9da6-b0fc63129f3c', '694523fc-5d19-5d81-8e08-6083c35d7d25', 4, 'Lesson 4', 'lesson', 'published'),
  ('3df07da7-53e7-5513-b398-96fb563441b8', '694523fc-5d19-5d81-8e08-6083c35d7d25', 5, 'Lesson 5', 'lesson', 'published'),
  ('36040bfe-9f73-503d-947d-a910c0a71db0', '694523fc-5d19-5d81-8e08-6083c35d7d25', 6, 'Practice', 'practice', 'published'),
  ('95a823be-41c1-5a5a-85a6-657715a6407f', '694523fc-5d19-5d81-8e08-6083c35d7d25', 7, 'Practice', 'practice', 'published'),
  ('3d7e0e38-aa61-54f9-9116-bb14cc01f728', '694523fc-5d19-5d81-8e08-6083c35d7d25', 8, 'Unit check', 'review', 'published'),
  ('fff5a666-c238-5f95-8382-9902844f57f5', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 1, 'Lesson 1', 'lesson', 'published'),
  ('44672817-d2ec-5e8a-9f87-2a9bb5056fbd', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 2, 'Lesson 2', 'lesson', 'published'),
  ('7ba9194a-5a52-50b9-9382-08b776e38179', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 3, 'Lesson 3', 'lesson', 'published'),
  ('d89594af-68b9-5bf2-956e-58e7e037739b', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 4, 'Lesson 4', 'lesson', 'published'),
  ('c7d68139-9c77-54f4-8fbb-4f2d0914ada8', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 5, 'Practice', 'practice', 'published'),
  ('f1044c6f-58ac-5e3c-95e4-a642afc3b84e', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 6, 'Practice', 'practice', 'published'),
  ('3d07c900-9f25-5ae3-b4ec-575f9674bcb1', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 7, 'Unit check', 'review', 'published')
on conflict do nothing;

insert into public.tips (id, unit_id, title_en, body_md, status) values
  ('3ddb4cb9-dbfd-5829-b717-aec8064fbb90', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 'Hablo, hablás', 'The *I* form ends in **-o**: **hablo**, **entiendo**. The vos form is stressed on the end: **hablás**, **entendés**, **repetís**. One verb is different: *I know* is just **sé**, and the vos form is **sabés**. *No entiendo. ¿Hablás inglés?* — *No sé.*', 'published'),
  ('1f4b9651-418e-5f8c-a3bf-03626d36a760', '9f62a065-778e-5620-b8e5-de9e6f8c2907', 'Ask for help', 'Stuck on a word: **¿cómo se dice…?** — *how do you say…?* — and **¿qué significa?** — *what does it mean?* Too fast: **más despacio, por favor**. And the line that buys you patience: **hablo un poco** — *I speak a little*. Argentines call the language **castellano**.', 'published'),
  ('0a165b34-8a68-50c2-973b-ae40dc128454', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 'Veinticinco, treinta y cuatro', 'From 21 to 29 the number is one word: **veintiuno**, **veintidós**, **veinticinco**. From **treinta** on it is three words joined by **y**: *Tengo treinta y cuatro años.* The same pattern works for **cuarenta**, **cincuenta** and all the way up to **noventa**.', 'published'),
  ('ae4f4e8b-34af-508d-8cc2-5d3e4564bb87', '5bf591c3-3ee8-5b3a-a7b6-4b774ad64dc0', 'Sesenta or setenta?', '**Sesenta** (60) and **setenta** (70) are the pair everyone mixes up: **sesenta** has the **s** of *six*, **setenta** has the **t** of *seven*. And a round hundred is just **cien** — never *un cien*.', 'published'),
  ('2b07464d-38f9-507b-bfa2-be0acb5aa850', '3bfdac76-f836-5268-91f3-0dbfa1c26018', '¿Cuánto sale?', '**¿Cuánto sale?** is the everyday Argentine way to ask a price — **¿cuánto cuesta?** works too and means the same. For more than one thing the verb changes: **¿cuánto salen?**, **¿cuánto cuestan?**', 'published'),
  ('b29680d4-b383-5aa7-a81f-ac7b3e1b8450', '3bfdac76-f836-5268-91f3-0dbfa1c26018', 'Mil, never un mil', 'Argentine prices run into the thousands, so you will say **mil** all day. One thousand is just **mil** — never *un mil* — and the word does not change: *Sale mil pesos.* *¿Mil pesos? Es caro.*', 'published'),
  ('6e364ee3-389f-55b3-a895-bd88f35dc318', 'bde97495-163d-56bd-a579-b524910edfcc', 'Voy, vas, va', '**Ir** — *to go* — looks nothing like its forms: **voy**, **vas**, **va**, **vamos**, **van**. Spanish uses one form for *I go* and *I''m going*: *Voy a la plaza* is both. And **vamos** on its own also means *let''s go*.', 'published'),
  ('29afb672-4c8b-59dd-85ee-eef456a2127a', 'bde97495-163d-56bd-a579-b524910edfcc', 'Always with a', 'Going somewhere takes **a** — *to* — every time: *Voy a la plaza.* The question word has that **a** built in: **¿adónde vas?** is *where are you going to?* English often drops the *to*; Spanish never drops the **a**.', 'published'),
  ('11dfb570-d80f-5e13-a3ef-5cfff6079ac5', '525526ce-1e8d-5672-88f4-02259c8e4533', 'Two mañanas', '**Mañana** on its own is *tomorrow*: *Hoy laburo, mañana no.* With **la** it is *the morning*, and porteños say **a la mañana** for *in the morning*. So *tomorrow morning* is **mañana a la mañana**.', 'published'),
  ('5d601854-1cc7-5d99-961d-5454185bfc90', '525526ce-1e8d-5672-88f4-02259c8e4533', 'Tarde: afternoon or late', '**Tarde** works the same way. **A la tarde** is *in the afternoon*; on its own **tarde** means *late*: *Es tarde.* Its opposite is **temprano** — *early*: *Es temprano.*', 'published'),
  ('ccecffed-c0a3-59ba-b6b7-db2c4a7c140d', '26b3f81c-f349-5b38-817b-731bbac652cf', 'Este here, ese there', '**Este** is *this*, near you; **ese** is *that*, further away. Both match the noun: **este** café, **esa** mochila, and **estos**, **estas**, **esos**, **esas** for more than one. *Esa mochila es re linda* — **re** before an adjective is the porteño *really*.', 'published'),
  ('c2b30f52-c7e5-5023-9df0-92d83a8d3c18', '26b3f81c-f349-5b38-817b-731bbac652cf', 'Esto and eso', 'When you don''t know the word — or don''t need it — use **esto** (this thing here) and **eso** (that thing there). They never change and no noun comes after them: *Quiero eso, por favor.*', 'published'),
  ('3780b464-8070-51f5-84a8-d6507d0dfa2e', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 'Un pantalón, un jean', 'One pair of pants is **un pantalón** — singular: *Mi pantalón es nuevo.* *Los pantalones* works too. The same goes for **un jean**. And **ropa** — *clothes* — is always singular: *Mi ropa es nueva.*', 'published'),
  ('5f0726c3-0c2e-524a-b89f-9832deab7142', '70cf9841-8e17-590c-9fd0-503d47b7b3e1', 'Nuevo, nueva', 'The adjective copies its noun: *una campera nueva*, *un jean nuevo*, *los pantalones chicos*. **Grande** has one form for both: *una remera grande*, *las zapatillas grandes*. And it comes after the noun, not before as in English.', 'published'),
  ('f81f6472-4ab5-5b1d-97bd-3ad25b1a3ad1', '694523fc-5d19-5d81-8e08-6083c35d7d25', '-ando, -iendo', 'Verbs in *-ar* take **-ando**: **laburando**, **esperando**, **tomando**. Verbs in *-er* and *-ir* take **-iendo**: **comiendo**, **haciendo**. That ending never changes — only *estar* does: *Estoy comiendo.* *Está tomando un café.*', 'published'),
  ('ffce8d24-cbec-5893-93f5-546baf4d2390', '694523fc-5d19-5d81-8e08-6083c35d7d25', 'Ya, todavía, casi', '**Ya** is *already* or *right now*; **todavía** is *still*: *Todavía estoy laburando.* *Todavía no* is *not yet*. **Casi** is *almost*. One warning: in Buenos Aires **ya estoy llegando** can mean you are still ten minutes away.', 'published'),
  ('ba82ffe4-0152-5484-bf4b-85a5828f972a', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 'Digo, pongo, veo', 'Like *vengo* and *traigo*, these verbs have an odd *I* form: **digo**, **pongo** and **veo**. With vos they are regular: **decís**, **ponés**, **ves**. *Decir* also changes **e** to **i** in **dice** and **dicen**. *¿Qué decís? — Yo no digo nada.*', 'published'),
  ('a2908aec-4964-564b-be6f-345aab4ac907', '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 'No veo nada', 'English says *I can''t see anything*; Spanish just says **no veo nada** — no word for *can*. The same with **ves**: *¿Ves?* is *can you see?* And the double negative is correct Spanish: *no* before the verb, *nada* after it.', 'published')
on conflict do nothing;

insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('57dda3fd-0f69-5755-bad0-9878f85781df', 'mío', 'adj', 'mine', null, 'neutral', false, null, 'published'),
  ('f18877cd-de0c-57c8-bac6-8233375d1043', 'tuyo', 'adj', 'yours', null, 'neutral', false, null, 'published'),
  ('bafc1c3e-7654-5436-bd64-1a7e124c8280', 'a mí también', 'phrase', 'me too', null, 'neutral', false, null, 'published'),
  ('803ed0c6-80e4-583f-92e4-e82eb50e5b4c', 'a mí tampoco', 'phrase', 'me neither', null, 'neutral', false, null, 'published'),
  ('077b5246-d66d-5a90-b556-3ed6c913bfcc', 'lo llevo', 'phrase', 'I''ll take it', null, 'neutral', false, null, 'published'),
  ('d0eaf9bb-e57c-5628-94db-bd2c1ddad17d', 'solo estoy mirando', 'phrase', 'I''m just looking', null, 'neutral', false, null, 'published'),
  ('e2879d9f-e13a-5b2c-9a28-e0e107db57e4', 'arroba', 'noun', 'at sign', null, 'neutral', false, null, 'published'),
  ('9ed64401-6645-50a7-920f-18fdb029712c', 'punto com', 'phrase', 'dot com', null, 'neutral', false, null, 'published'),
  ('f90a3c7a-1b66-5e80-9d0e-40fb312997c9', 'cómo se escribe', 'phrase', 'how do you spell it', null, 'neutral', false, null, 'published'),
  ('42a59196-26a0-564d-949a-e34012889138', 'para llevar', 'phrase', 'to take away', null, 'neutral', false, null, 'published'),
  ('06e4208c-ef33-5e95-b19e-4fe2effeb5bc', 'delivery', 'noun', 'home delivery', null, 'neutral', false, null, 'published')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('a80694bf-f2e2-5e70-93f5-5419cf4df11e', '57dda3fd-0f69-5755-bad0-9878f85781df', 'mío', '{}'::jsonb, 'mine', null, '9c3ea7c9-a129-5157-b092-804da692c36c', 16, false, null, null, 'published'),
  ('6a79cbd9-4c4a-5d60-a404-03b1d76a3f9b', '57dda3fd-0f69-5755-bad0-9878f85781df', 'mía', '{}'::jsonb, 'mine', null, '9c3ea7c9-a129-5157-b092-804da692c36c', 17, false, null, null, 'published'),
  ('a9135a3d-e641-5c55-ae7b-9f9a48421f93', 'f18877cd-de0c-57c8-bac6-8233375d1043', 'tuyo', '{}'::jsonb, 'yours', null, '9c3ea7c9-a129-5157-b092-804da692c36c', 18, false, null, null, 'published'),
  ('f0ae10a7-1a92-5b1f-9ae4-05ece9d0adb0', 'f18877cd-de0c-57c8-bac6-8233375d1043', 'tuya', '{}'::jsonb, 'yours', null, '9c3ea7c9-a129-5157-b092-804da692c36c', 19, false, null, null, 'published'),
  ('9b34b74f-9415-5c26-a0d9-14505256a7a2', 'bafc1c3e-7654-5436-bd64-1a7e124c8280', 'a mí también', '{}'::jsonb, null, null, 'b95d926c-3168-53bd-88bd-c02c868d1119', 16, false, null, null, 'published'),
  ('abc811ca-6ee9-5a35-acf5-b4d9fc487e14', '803ed0c6-80e4-583f-92e4-e82eb50e5b4c', 'a mí tampoco', '{}'::jsonb, null, null, 'b95d926c-3168-53bd-88bd-c02c868d1119', 17, false, null, null, 'published'),
  ('51303a34-8b2d-563f-ac4c-bd6fb8040485', '077b5246-d66d-5a90-b556-3ed6c913bfcc', 'lo llevo', '{}'::jsonb, 'I''ll take it', null, 'b3f216c5-d105-552a-b3f1-254cee4747b1', 28, false, null, null, 'published'),
  ('912bde55-6645-5bf5-b3e5-e9fce2a3a8b4', '077b5246-d66d-5a90-b556-3ed6c913bfcc', 'la llevo', '{}'::jsonb, 'I''ll take it', null, 'b3f216c5-d105-552a-b3f1-254cee4747b1', 29, false, null, null, 'published'),
  ('799912da-ff03-589f-bcef-09ad76f8f410', 'd0eaf9bb-e57c-5628-94db-bd2c1ddad17d', 'solo estoy mirando', '{}'::jsonb, null, null, 'b3f216c5-d105-552a-b3f1-254cee4747b1', 30, false, null, null, 'published'),
  ('25bb0f25-2a37-5054-a6fb-d2da5547cf9c', 'e2879d9f-e13a-5b2c-9a28-e0e107db57e4', 'arroba', '{}'::jsonb, null, null, 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', 15, false, null, null, 'published'),
  ('7008d87b-5201-5577-84a3-e2f47dcbbf09', '9ed64401-6645-50a7-920f-18fdb029712c', 'punto com', '{}'::jsonb, null, null, 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', 16, false, null, null, 'published'),
  ('0b9616c7-43e0-5f79-aeec-3d2680df49bd', 'f90a3c7a-1b66-5e80-9d0e-40fb312997c9', 'cómo se escribe', '{}'::jsonb, null, null, 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', 17, false, null, null, 'published'),
  ('3e566134-0cba-5fd8-ab90-48ac54849685', '453aac22-007c-5a7e-a38a-7c678487f00d', 'ponés', '{}'::jsonb, 'to put', null, '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 9, false, null, null, 'published'),
  ('43f53ba0-9b94-59ff-9c6b-c63c7c87dc3f', '453aac22-007c-5a7e-a38a-7c678487f00d', 'poner', '{}'::jsonb, 'to put', null, '59190ff0-c3f5-5d61-bd69-5db02edca9fd', 10, false, null, null, 'published'),
  ('e36b5332-1dd9-590a-abb9-2917b3f8c561', '42a59196-26a0-564d-949a-e34012889138', 'para llevar', '{}'::jsonb, null, null, '42aaa1de-ab7b-5276-9032-91bff95ed818', 18, false, null, null, 'published'),
  ('f1c44de4-6bc4-5161-b350-c3d44e4f3447', '06e4208c-ef33-5e95-b19e-4fe2effeb5bc', 'delivery', '{}'::jsonb, null, null, '42aaa1de-ab7b-5276-9032-91bff95ed818', 19, false, null, null, 'published')
on conflict do nothing;




