-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------



-- No new lessons: these units were seeded already.



insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('920f2c31-663c-55d7-97c8-6179d9ca62c7', 'ebbd1e1f-1610-5693-bcb6-fb0128dbc509', 'harías', '{"person":2,"number":"sg","tense":"cond","mood":"ind","voseo":true,"irregular":true}'::jsonb, 'you would do', null, 'ce343377-a0c2-5201-9ff4-824789e73e89', 10, false, null, null, 'draft')
on conflict do nothing;




