-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 11 where id = 'f601496a-6296-5611-8059-199201609e35'; -- vuelto
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 13 where id = '37a4e68e-1bd4-5fea-9af2-5815243ca05f'; -- avisás
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 9 where id = '3b4c3055-69ff-51a4-9024-e829341c46c2'; -- próxima
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 10 where id = '2a7ccce2-ca16-5891-a21b-683d94ed3c8c'; -- llamame
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 8 where id = 'abb68c55-6a9d-5aca-86ed-9dd24b3387a3'; -- mando
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 9 where id = '6d1af423-7b0b-5380-8075-ac90f85c6e9b'; -- mandame
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 8 where id = '775f20f9-4d91-5e07-bddf-950380046ad9'; -- viaje
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 7 where id = '3ddfebfa-8c88-56e4-a261-7899919d82ef'; -- aeropuerto
update public.forms set unit_id = 'bf7b8307-3d3a-57b2-9e3b-06bca38b4ef1', position = 3 where id = 'ec226da1-d457-59fb-a91e-4687419f02a2'; -- hotel
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 3 where id = '46d5be7a-7fee-5b97-a1e7-9d0d398e3a48'; -- pido
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 4 where id = '2f891751-9844-589e-a351-fadb49973a26'; -- pedir
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 3 where id = 'bb45d94f-7884-5876-9979-f766b512ea18'; -- me pasás
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 4 where id = '01fe91be-d363-5c3c-b996-2496f52169dd'; -- pasás
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 5 where id = '39b8dd84-2283-5bb7-8ce0-c745445832dc'; -- pasame
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 6 where id = 'b0ea5e5b-11a2-5f3e-a726-074af4b41794'; -- me llevás
update public.forms set unit_id = '72bb9993-19e7-5dad-bdc7-78b4161e7045', position = 12 where id = '890e666e-ffa2-56d8-a52f-ad18e186f9c2'; -- urgente
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 2 where id = '0c36052e-5fd6-5fc1-8c18-8e0904d6b425'; -- cargo
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 3 where id = '8174c46b-5d5f-5306-9fa6-0922f1a72ada'; -- cargás
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 4 where id = 'c9cbc3ba-7859-5fcb-ab53-ca176bb3f5b5'; -- cargar
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 1 where id = '52158ace-66c2-577e-8c05-4e9711433976'; -- SUBE
update public.forms set unit_id = 'bf7b8307-3d3a-57b2-9e3b-06bca38b4ef1', position = 15 where id = '7c579b4d-3aec-55df-bb52-58ad9496eb94'; -- wifi
update public.forms set unit_id = 'fa7ef0ed-4de1-5b37-9c23-1d5747ae531d', position = 14 where id = '144ba7ad-2e7f-5556-8d7d-80383161ac32'; -- datos
update public.forms set unit_id = 'd9917aa3-1a7b-5287-9437-9c652db27797', position = 5 where id = '726a2d4a-5f97-5a5b-8eba-ff2d0d9b054e'; -- app
update public.forms set unit_id = '72bb9993-19e7-5dad-bdc7-78b4161e7045', position = 8 where id = '5b251024-4865-5000-b6d4-c9caaf4a5bc6'; -- me robaron
update public.forms set unit_id = '72bb9993-19e7-5dad-bdc7-78b4161e7045', position = 9 where id = '3d250ad9-2d1c-55bf-8e7a-a7ee4daa238d'; -- robaron
update public.forms set unit_id = '72bb9993-19e7-5dad-bdc7-78b4161e7045', position = 1 where id = '3bbf044d-4605-5a17-927e-20d1c1bb9add'; -- ayuda
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 3 where id = '15893c23-be58-5e82-92c0-9527a1304c6a'; -- cuota
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 4 where id = 'c62861c1-c2f5-53da-a288-9c2005494626'; -- cuotas
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 11 where id = 'ab6770d4-6df5-5d25-afd1-a4234c6bb2da'; -- dólar
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 12 where id = '7bc02aba-8f97-5fda-aaba-a4f33d23da66'; -- dólares
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 1 where id = '8e696712-e76c-53da-8e3d-c2581b7d079d'; -- débito
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 2 where id = '3ecf739e-b29f-5137-9b03-1493aa7bbbfd'; -- crédito
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 5 where id = '89590665-2e8c-5fb3-aece-7bc2cb8dd03f'; -- sin interés
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 16 where id = '754027d6-8f1e-515c-84ae-45396a0d662f'; -- Palermo
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 6 where id = '80984f56-9cb4-5a21-88ec-0fc5130c7316'; -- transfiero
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 7 where id = 'acabc425-80fd-5882-b1c8-426304e0d34e'; -- transferencia
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 5 where id = '1835cbaa-7c75-5704-a48f-03288bd9aa17'; -- saldo
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 8 where id = '62d4e0e6-5f0a-511f-a181-bebe11f1533f'; -- alias
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 9 where id = 'ac0b5740-aabd-5caf-a4c6-e9af052bece5'; -- QR
update public.forms set unit_id = 'bf7b8307-3d3a-57b2-9e3b-06bca38b4ef1', position = 8 where id = '0bdc496e-8570-5682-a537-54cf6e9a2f5b'; -- pasaporte
update public.forms set unit_id = 'c15b7bfe-bc72-5bf8-a990-5ba1799a2d79', position = 13 where id = 'aeca9ddb-0da5-5323-a00c-071ec8be3b34'; -- cambiar
update public.forms set unit_id = '4db2a92e-ad85-5b0f-88e2-71629dbf00d2', position = 6 where id = 'cf9e58d6-a2de-5840-8f5e-2ab0ac6e4d18'; -- boleto
update public.forms set unit_id = '72bb9993-19e7-5dad-bdc7-78b4161e7045', position = 11 where id = 'd07fc46a-7e94-54f9-888f-848939694189'; -- accidente
