-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

-- Words taught earlier now.
update public.forms set unit_id = '558006ff-a18d-5fc9-ae98-edf66c5a28dc', position = 4 where id = '10eb66d3-7b9b-5926-917c-6d0187cbd79e'; -- aprendiendo
update public.forms set unit_id = 'de1cac02-1435-56ef-9682-17ea2bc59bc4', position = 5 where id = '9c5919ab-1aec-50c9-bc2d-19061b38e040'; -- consulta
update public.forms set unit_id = 'eedc812b-9def-5602-bd94-b8fc7ba8e7b6', position = 7 where id = '8c22d099-c928-5eed-aa93-7a01604e2a95'; -- la verdad
update public.forms set unit_id = '558006ff-a18d-5fc9-ae98-edf66c5a28dc', position = 14 where id = '707d1312-772e-5026-9249-df86c9f78c60'; -- volví a
update public.forms set unit_id = '558006ff-a18d-5fc9-ae98-edf66c5a28dc', position = 15 where id = 'b6dd15f8-3f1d-54da-9530-f0ac8d07bfda'; -- vuelvo a
update public.forms set unit_id = 'd2d1e75f-f8c3-5507-9e3a-6019ac0c40a0', position = 1 where id = 'a07db38c-410b-54ab-9d0f-26e3a158594f'; -- hubiéramos
