-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

create temporary table reorder_units (id uuid, section_id smallint, ordinal smallint, course_order smallint, old_order smallint) on commit drop;
insert into reorder_units values
  ('d1ef9d43-816d-571d-a8ba-4ba76a09ba2d'::uuid, 14, 3, 332, 331),
  ('f925644a-c585-5773-8af3-f9a36c4cd2b0'::uuid, 14, 5, 334, 332),
  ('8391605b-e3f5-521c-811d-c849d7eef95f'::uuid, 14, 7, 336, 333),
  ('35edaab3-b8c0-58db-8415-f52edb278a7e'::uuid, 14, 9, 338, 334),
  ('1a2a791f-b759-5930-8cdd-2829e879ce31'::uuid, 14, 11, 340, 335),
  ('4023fc2a-56e8-5980-bada-adc3306da091'::uuid, 14, 13, 342, 336),
  ('5ee78c4c-97f9-5e3c-a458-2aff27520c2e'::uuid, 14, 15, 344, 337),
  ('e0efacaf-93a3-521c-850d-fda4909c6796'::uuid, 14, 17, 346, 338),
  ('24efab50-024b-519e-9029-d2d7f4a05a09'::uuid, 14, 19, 348, 339),
  ('1c04f11a-4feb-5b1d-956b-3661bab59c15'::uuid, 14, 21, 350, 340),
  ('544808fd-b59f-580e-b0be-6f789ba2a11c'::uuid, 14, 23, 352, 341),
  ('58c98ce0-5227-5f11-bf08-49d656a7808b'::uuid, 14, 26, 355, 342),
  ('e3884c35-d0b6-5d6d-9e7f-b4b1308c5981'::uuid, 15, 1, 356, 343),
  ('80d9fccd-c824-5946-8cce-04ecc42e570d'::uuid, 15, 2, 357, 344),
  ('f1fe8414-a662-5131-9e76-a258572724ea'::uuid, 15, 3, 358, 345),
  ('908f70c9-72c3-5244-b3c8-db86021008ed'::uuid, 15, 4, 359, 346),
  ('6d5e1fa5-986d-5b45-a406-035e7c99c15c'::uuid, 15, 5, 360, 347),
  ('5572cf90-36cf-55e2-824b-80f995d2d968'::uuid, 15, 6, 361, 348),
  ('cf4d6a07-a4c5-5761-9bad-5a84df508105'::uuid, 15, 7, 362, 349),
  ('a5e76c4c-fdd3-5652-89d4-4d7a8341eae7'::uuid, 15, 8, 363, 350),
  ('cc075128-b483-5ba0-a24a-485bd1dc71fa'::uuid, 15, 9, 364, 351),
  ('35da2974-7119-59d7-bdf3-d14bdf042064'::uuid, 15, 10, 365, 352),
  ('a25229c0-af37-50d8-86db-83c809276632'::uuid, 15, 11, 366, 353),
  ('f6864f2a-0faf-53cf-a8b4-9e35f6661b10'::uuid, 15, 12, 367, 354),
  ('c1be6404-2a36-51f7-8d0f-43b1a6d26250'::uuid, 15, 13, 368, 355);

-- Through a free range first: ordinals and course places are unique.
update public.units u set ordinal = 20000 + r.ordinal, course_order = 20000 + r.course_order from reorder_units r where u.id = r.id;
update public.units u set section_id = r.section_id, ordinal = r.ordinal, course_order = r.course_order from reorder_units r where u.id = r.id;

-- A placement or jump test is remembered as a course place.
update public.profiles p set placed_through = r.course_order from reorder_units r where p.placed_through = r.old_order;

