-- ---------------------------------------------------------------------------
-- Telemetry — docs/learning-engine-spec.md §1, §2.
--
-- A round is one played lesson, practice round, story or placement test. Every
-- exercise log now says which round it belongs to and what exactly happened,
-- and every SM-2 decision is written down with the state before and after — so
-- a scheduler, a difficulty model or a constant can be judged against what
-- learners actually did, instead of guessed.
--
-- Additive: `review_logs.rating` stays for anything that reads it today.
-- ---------------------------------------------------------------------------

create table public.rounds (
  -- Generated by the client, so the logs of the round can name it before the
  -- insert has landed.
  id              uuid primary key,
  user_id         uuid not null references auth.users on delete cascade,
  kind            text not null
                  check (kind in ('lesson', 'practice', 'free', 'mistakes', 'story', 'placement', 'unit_check')),
  lesson_id       uuid references public.lessons on delete set null,
  local_date      date not null,
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  planned_items   smallint not null default 0,
  answered        smallint not null default 0,
  first_try_wrong smallint not null default 0,
  retries         smallint not null default 0,
  score           smallint check (score between 0 and 100),
  ladder_offset   smallint not null default 0 check (ladder_offset between -1 and 1),
  promoted        smallint not null default 0,
  app_version     text
);
create index rounds_user_idx on public.rounds (user_id, started_at desc);

comment on table public.rounds is
  'One played round. finished_at null means abandoned. score = first-try % correct.';

alter table public.review_logs
  add column round_id    uuid references public.rounds on delete cascade,
  add column item_index  smallint,
  add column sentence_id uuid references public.sentences on delete set null,
  add column direction   text check (direction in ('es_to_en', 'en_to_es')),
  add column correct     boolean,
  add column is_retry    boolean not null default false,
  add column promoted    boolean not null default false,
  add column hinted      boolean not null default false,
  add column note        text check (note in ('accent', 'typo', 'enye')),
  add column latency_ms  integer check (latency_ms >= 0),
  add column answer      text;
create index review_logs_round_idx on public.review_logs (round_id);
create index review_logs_sentence_idx on public.review_logs (sentence_id) where sentence_id is not null;

-- What the scheduler decided, once per form per round.
create table public.srs_commits (
  id            bigint generated always as identity primary key,
  user_id       uuid not null references auth.users on delete cascade,
  form_id       uuid not null references public.forms on delete cascade,
  round_id      uuid references public.rounds on delete set null,
  seen          smallint not null,
  wrong         smallint not null,
  rating        smallint not null check (rating between 0 and 3),
  -- false: filler, a word SM-2 did not ask for. Its state only moves on a lapse.
  scheduled     boolean not null,
  elapsed_days  real,
  prev_interval real,
  prev_ease     real,
  prev_due_at   timestamptz,
  prev_state    text,
  next_interval real,
  next_ease     real,
  next_due_at   timestamptz,
  next_state    text,
  created_at    timestamptz not null default now()
);
create index srs_commits_user_form_idx on public.srs_commits (user_id, form_id, created_at);

alter table public.rounds      enable row level security;
alter table public.srs_commits enable row level security;

do $$
declare t text;
begin
  foreach t in array array['rounds', 'srs_commits'] loop
    execute format(
      'create policy "%1$s: owner read" on public.%1$I for select to authenticated
         using (user_id = auth.uid())', t);
    execute format(
      'create policy "%1$s: owner insert" on public.%1$I for insert to authenticated
         with check (user_id = auth.uid())', t);
  end loop;
end $$;

create policy "rounds: owner update" on public.rounds for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

------------------------------------------------------------
-- Staff reports. Functions rather than views, so nothing learner-level is
-- reachable through the API without the staff check, and no user id leaves.
------------------------------------------------------------
create or replace function public.staff_round_stats(p_since timestamptz default now() - interval '8 weeks')
returns table (week date, kind text, finished bigint, abandoned bigint, avg_score numeric, median_score double precision, out_of_band bigint)
language sql
stable
security definer
set search_path = public
as $$
  select date_trunc('week', r.started_at)::date,
         r.kind,
         count(*) filter (where r.finished_at is not null),
         count(*) filter (where r.finished_at is null),
         round(avg(r.score) filter (where r.finished_at is not null), 1),
         percentile_cont(0.5) within group (order by r.score),
         count(*) filter (where r.finished_at is not null and (r.score < 85 or r.score > 92))
  from public.rounds r
  where public.is_staff() and r.started_at >= p_since
  group by 1, 2
  order by 1 desc, 2;
$$;

create or replace function public.staff_mode_stats(p_since timestamptz default now() - interval '8 weeks')
returns table (week date, mode text, promoted boolean, first_tries bigint, fail_rate numeric, median_ms double precision)
language sql
stable
security definer
set search_path = public
as $$
  select date_trunc('week', l.reviewed_at)::date,
         l.mode,
         l.promoted,
         count(*) filter (where not l.is_retry),
         round(avg((not l.correct)::int) filter (where not l.is_retry), 3),
         percentile_cont(0.5) within group (order by l.latency_ms)
  from public.review_logs l
  where public.is_staff() and l.correct is not null and l.reviewed_at >= p_since
  group by 1, 2, 3
  order by 1 desc, 2, 3;
$$;

revoke all on function public.staff_round_stats(timestamptz) from public;
revoke all on function public.staff_mode_stats(timestamptz) from public;
grant execute on function public.staff_round_stats(timestamptz) to authenticated;
grant execute on function public.staff_mode_stats(timestamptz) to authenticated;
