-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------



-- No new lessons: these units were seeded already; they carry the extra words in the lessons they have.



insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('976750b9-651d-588a-a81a-fa8fc5f3b60b', 'a93634b7-5b70-5ddb-851d-34115955647b', 'comer', '{"verb_form":"inf"}'::jsonb, null, null, '063d369c-847e-57b8-8451-b9c4049a1d9e', 11, false, null, null, 'draft'),
  ('e6dfd5d8-6467-5d5a-87cf-888a9a2abb8c', 'b3a15f68-a07c-5f20-8b7a-ff5a502172c7', 'comprá', '{"person":2,"number":"sg","mood":"imp","voseo":true}'::jsonb, 'buy', null, '063d369c-847e-57b8-8451-b9c4049a1d9e', 12, false, null, null, 'draft'),
  ('6fd84a36-7322-5dd3-865c-93ff892d7328', 'a72ffe32-9177-5008-a0ba-e09718e4b437', 'dormiste', '{"person":2,"number":"sg","tense":"pret","mood":"ind","voseo":true}'::jsonb, 'you slept', null, '20b6357e-6e5d-58e3-814d-c7acd27bedc2', 6, false, null, null, 'draft')
on conflict do nothing;




