-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------





insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('1a2ebe62-a148-5b40-8a52-589657524b8a', 'cuál', 'pron', 'which, what', null, 'neutral', false, null, 'draft'),
  ('5e327ce4-1a78-5852-b47c-ce2aa4d3c38c', 'verdad', 'noun', 'truth, true', null, 'neutral', false, null, 'draft')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('fbc5d133-8d7d-5e32-869d-a1f28a78962b', 'd5b724c8-81ca-5c57-8bee-20b935f1949c', 'esperar', '{"verb_form":"inf"}'::jsonb, 'to wait', null, '577ff67b-76f7-513b-adca-5871bbb950dc', 8, false, null, null, 'draft'),
  ('d2d26d26-92a8-56c1-a429-39fc102f6803', '1a2ebe62-a148-5b40-8a52-589657524b8a', 'cuál', '{}'::jsonb, null, null, '0b94d24b-0ce7-5a34-a580-2ef059801e5e', 5, false, null, null, 'draft'),
  ('7ec41db4-f03c-5b2a-be38-a858966e7c23', '5e327ce4-1a78-5852-b47c-ce2aa4d3c38c', 'verdad', '{}'::jsonb, null, null, '0b94d24b-0ce7-5a34-a580-2ef059801e5e', 6, false, null, null, 'draft')
on conflict do nothing;




