-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------







insert into public.lemmas (id, lemma, pos, gloss_en, gloss_note_en, register, is_glue, notes_en, status) values
  ('2c521e99-9066-534c-9f86-d481275bd4a7', 'José', 'propn', 'José', null, 'neutral', false, null, 'published'),
  ('0b04ec31-0c27-5ebd-ae2f-b3aada4a0ce1', 'Carlos', 'propn', 'Carlos', null, 'neutral', false, null, 'published'),
  ('4e2fb9f2-cb1c-5908-9ebe-2cdf07aba57e', 'Raúl', 'propn', 'Raúl', null, 'neutral', false, null, 'published'),
  ('09737845-05cc-5ba5-9bf9-0054418a8853', 'Marta', 'propn', 'Marta', null, 'neutral', false, null, 'published'),
  ('07f168e2-b47f-5dee-8787-e20289a6a170', 'Elena', 'propn', 'Elena', null, 'neutral', false, null, 'published'),
  ('92d980d9-0cec-5ab4-adcc-ae931fb1c4e2', 'Susana', 'propn', 'Susana', null, 'neutral', false, null, 'published')
on conflict do nothing;

insert into public.forms (id, lemma_id, form, features, gloss_en, gloss_note_en, unit_id, position, bound, audio_path, voice_id, status) values
  ('21a66bc7-8334-5cc4-8446-eeb2a1e6fd6a', '2c521e99-9066-534c-9f86-d481275bd4a7', 'José', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 30, false, null, null, 'published'),
  ('ddcbdcfd-00c9-5ff6-afa3-524fcef95a0e', '0b04ec31-0c27-5ebd-ae2f-b3aada4a0ce1', 'Carlos', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 31, false, null, null, 'published'),
  ('fdb364f3-9ed7-5436-b7df-fb287737ab74', '4e2fb9f2-cb1c-5908-9ebe-2cdf07aba57e', 'Raúl', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 32, false, null, null, 'published'),
  ('e333e319-afd1-5bb6-ac90-37d85b8eaa79', '09737845-05cc-5ba5-9bf9-0054418a8853', 'Marta', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 33, false, null, null, 'published'),
  ('b404a223-22d3-5263-85e1-dc82faf9b75c', '07f168e2-b47f-5dee-8787-e20289a6a170', 'Elena', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 34, false, null, null, 'published'),
  ('b16a02a5-eef7-58d1-b7d7-c04228cd0f0b', '92d980d9-0cec-5ab4-adcc-ae931fb1c4e2', 'Susana', '{}'::jsonb, null, null, 'cc27542c-c983-52aa-88c4-8fe075eb0a0f', 35, false, null, null, 'published')
on conflict do nothing;




