-- ---------------------------------------------------------------------------
-- Course doubling: the database's units take their place in the YAML's order,
-- and words the YAML teaches earlier move there. Generated by
-- scripts/course/reorder.mjs. Do not edit by hand; regenerate.
-- ---------------------------------------------------------------------------

create temporary table reorder_units (id uuid, section_id smallint, ordinal smallint, course_order smallint, old_order smallint) on commit drop;
insert into reorder_units values
  ('f46f9df0-afdf-5c8c-95be-a4b002904a9d'::uuid, 13, 3, 306, 305),
  ('38d68ef5-9223-5ff2-8954-88f3a9cc0ef3'::uuid, 13, 5, 308, 306),
  ('7743587b-284d-5f25-8f96-38e8f9443429'::uuid, 13, 7, 310, 307),
  ('d7836b8d-78b8-51ae-8e41-57e6f2d5de34'::uuid, 13, 9, 312, 308),
  ('7768d3dd-52a9-55e1-be73-c2b2153fdb64'::uuid, 13, 11, 314, 309),
  ('0549fd4c-6be5-5e51-a1f6-4520eabebe83'::uuid, 13, 13, 316, 310),
  ('b11e93f9-0410-5c63-9d47-ce8b7e4ebfb9'::uuid, 13, 15, 318, 311),
  ('78c71bbd-ead2-54c0-8b92-98f45101f849'::uuid, 13, 17, 320, 312),
  ('b612f887-6567-5b36-b3d8-71b680908d0e'::uuid, 13, 19, 322, 313),
  ('ccf7b1e1-a499-5013-99b2-4830d04fca71'::uuid, 13, 21, 324, 314),
  ('edefc2b5-24ef-5037-9435-816e34d18aaa'::uuid, 13, 23, 326, 315),
  ('e5014ed4-167a-55b0-8e66-43bd2ee4e434'::uuid, 13, 26, 329, 316),
  ('74a94584-d79a-55af-920c-e6fa1c59b5ad'::uuid, 14, 1, 330, 317),
  ('d1ef9d43-816d-571d-a8ba-4ba76a09ba2d'::uuid, 14, 2, 331, 318),
  ('f925644a-c585-5773-8af3-f9a36c4cd2b0'::uuid, 14, 3, 332, 319),
  ('8391605b-e3f5-521c-811d-c849d7eef95f'::uuid, 14, 4, 333, 320),
  ('35edaab3-b8c0-58db-8415-f52edb278a7e'::uuid, 14, 5, 334, 321),
  ('1a2a791f-b759-5930-8cdd-2829e879ce31'::uuid, 14, 6, 335, 322),
  ('4023fc2a-56e8-5980-bada-adc3306da091'::uuid, 14, 7, 336, 323),
  ('5ee78c4c-97f9-5e3c-a458-2aff27520c2e'::uuid, 14, 8, 337, 324),
  ('e0efacaf-93a3-521c-850d-fda4909c6796'::uuid, 14, 9, 338, 325),
  ('24efab50-024b-519e-9029-d2d7f4a05a09'::uuid, 14, 10, 339, 326),
  ('1c04f11a-4feb-5b1d-956b-3661bab59c15'::uuid, 14, 11, 340, 327),
  ('544808fd-b59f-580e-b0be-6f789ba2a11c'::uuid, 14, 12, 341, 328),
  ('58c98ce0-5227-5f11-bf08-49d656a7808b'::uuid, 14, 13, 342, 329),
  ('e3884c35-d0b6-5d6d-9e7f-b4b1308c5981'::uuid, 15, 1, 343, 330),
  ('80d9fccd-c824-5946-8cce-04ecc42e570d'::uuid, 15, 2, 344, 331),
  ('f1fe8414-a662-5131-9e76-a258572724ea'::uuid, 15, 3, 345, 332),
  ('908f70c9-72c3-5244-b3c8-db86021008ed'::uuid, 15, 4, 346, 333),
  ('6d5e1fa5-986d-5b45-a406-035e7c99c15c'::uuid, 15, 5, 347, 334),
  ('5572cf90-36cf-55e2-824b-80f995d2d968'::uuid, 15, 6, 348, 335),
  ('cf4d6a07-a4c5-5761-9bad-5a84df508105'::uuid, 15, 7, 349, 336),
  ('a5e76c4c-fdd3-5652-89d4-4d7a8341eae7'::uuid, 15, 8, 350, 337),
  ('cc075128-b483-5ba0-a24a-485bd1dc71fa'::uuid, 15, 9, 351, 338),
  ('35da2974-7119-59d7-bdf3-d14bdf042064'::uuid, 15, 10, 352, 339),
  ('a25229c0-af37-50d8-86db-83c809276632'::uuid, 15, 11, 353, 340),
  ('f6864f2a-0faf-53cf-a8b4-9e35f6661b10'::uuid, 15, 12, 354, 341),
  ('c1be6404-2a36-51f7-8d0f-43b1a6d26250'::uuid, 15, 13, 355, 342);

-- Through a free range first: ordinals and course places are unique.
update public.units u set ordinal = 20000 + r.ordinal, course_order = 20000 + r.course_order from reorder_units r where u.id = r.id;
update public.units u set section_id = r.section_id, ordinal = r.ordinal, course_order = r.course_order from reorder_units r where u.id = r.id;

-- A placement or jump test is remembered as a course place.
update public.profiles p set placed_through = r.course_order from reorder_units r where p.placed_through = r.old_order;

