#!/usr/bin/env node
// Loads new content from the YAML outline into a migration. The database is the
// source of truth (docs/superplan-admin-palabras.md §7.2): what already exists
// is edited in the admin, and this only ADDS — a new section file, a new unit,
// a new word. Nothing existing is changed or retired.
//
//   npm run course:seed -- supabase/migrations/<timestamp>_seed_<what>.sql
//   npm run course:seed -- --dry-run
//
// It reads the linked database to know what is already there, and prints what
// it adds, what it skips and where the YAML and the database differ. Differences
// are a warning, not an error: after any edit in the admin they are expected.
import { writeFileSync } from 'node:fs';

import { queryLinked } from './lib/db.mjs';
import { buildRows } from './lib/rows.mjs';
import { describeDiff, planSeed } from './lib/seed.mjs';
import { insertNew, jsonb, textArray } from './lib/sql.mjs';
import { loadCourseRows } from './lib/vocabulary.mjs';

const args = process.argv.slice(2);
const out = args.find((a) => !a.startsWith('--'));
const dryRun = args.includes('--dry-run');
if (!out && !dryRun) {
  console.error('usage: npm run course:seed -- <output.sql> | --dry-run');
  process.exit(1);
}
/** Units up to here were published when the course first went in. */
const PUBLISH_THROUGH = 2;

let built;
try {
  built = buildRows({ publishThrough: PUBLISH_THROUGH });
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
for (const w of built.warnings) console.warn(`warn  ${w}`);

const [keys] = queryLinked(`
  select json_build_object(
    'sentences',    (select coalesce(json_agg(json_build_object('id', id)), '[]') from public.sentences),
    'lesson_slots', (select coalesce(json_agg(json_build_object('lesson_id', lesson_id, 'ordinal', ordinal)), '[]') from public.lesson_slots),
    'story_lines',  (select coalesce(json_agg(json_build_object('lesson_id', lesson_id, 'ordinal', ordinal)), '[]') from public.story_lines),
    'unit_phrases', (select coalesce(json_agg(json_build_object('unit_id', unit_id, 'ordinal', ordinal)), '[]') from public.unit_phrases)
  ) as keys`);
const parse = (v) => (typeof v === 'string' ? JSON.parse(v) : v);
const db = { ...loadCourseRows(), ...parse(keys.keys) };

const { insert, skipped, diff } = planSeed(built, db);

const count = Object.entries(insert).filter(([, rows]) => rows.length);
console.log(count.length ? `\nAdds: ${count.map(([t, rows]) => `${rows.length} ${t}`).join(', ')}` : '\nNothing new to add.');
for (const u of insert.units) console.log(`  + unit ${u.slug}`);
for (const f of insert.forms.slice(0, 40)) console.log(`  + ${f.form}`);
if (insert.forms.length > 40) console.log(`  + … ${insert.forms.length - 40} more words`);
if (skipped.length) console.log(`\nSkipped:\n${skipped.map((s) => `  ${s}`).join('\n')}`);
const differences = describeDiff(diff);
if (differences.length) {
  console.log(`\nThe YAML differs from the database in ${differences.length} place(s). The database wins; edit these in /admin/words:`);
  for (const d of differences) console.log(`  ${d}`);
}
if (diff.missing.length) console.log(`\n${diff.missing.length} row(s) exist only in the database (added in the admin).`);

if (dryRun) {
  console.log('\n--dry-run: nothing written.');
  process.exit(0);
}
if (!count.length) {
  console.log('\nNo migration written.');
  process.exit(0);
}

const sql = [
  `-- ---------------------------------------------------------------------------
-- Seed: new content from docs/course/section-*.yaml (and the demo fixture),
-- generated by scripts/course/build-seed.mjs. Do not edit by hand; regenerate.
--
-- Adds only. Every insert leaves an existing row as it is: the database is the
-- source of truth, and what exists is edited in the admin.
-- ---------------------------------------------------------------------------
`,
  insertNew('sections', insert.sections, ['id', 'ordinal', 'slug', 'title_en', 'cefr', 'status']),
  insertNew(
    'units',
    insert.units,
    ['id', 'section_id', 'ordinal', 'course_order', 'slug', 'title_en', 'summary_en', 'grammar_focus', 'register_max', 'status'],
    { grammar_focus: textArray },
  ),
  insertNew('lessons', insert.lessons, ['id', 'unit_id', 'ordinal', 'title_en', 'kind', 'status']),
  insertNew('tips', insert.tips, ['id', 'unit_id', 'title_en', 'body_md', 'status']),
  insertNew('lemmas', insert.lemmas, ['id', 'lemma', 'pos', 'gloss_en', 'gloss_note_en', 'register', 'is_glue', 'notes_en', 'status']),
  insertNew('forms', insert.forms, ['id', 'lemma_id', 'form', 'features', 'gloss_en', 'gloss_note_en', 'unit_id', 'position', 'bound', 'audio_path', 'voice_id', 'status'], {
    features: jsonb,
  }),
  // sentence_forms follows by trigger.
  insertNew(
    'sentences',
    insert.sentences,
    ['id', 'unit_id', 'es', 'en', 'en_alt', 'es_alt', 'tokens', 'target_form_id', 'kind', 'difficulty', 'source', 'attribution', 'audio_path', 'voice_id', 'status'],
    { en_alt: textArray, es_alt: textArray, tokens: jsonb },
  ),
  insertNew('lesson_slots', insert.lesson_slots, ['id', 'lesson_id', 'ordinal', 'kind', 'form_id', 'sentence_id', 'tip_id', 'mode', 'review_count', 'scope']),
  insertNew('story_lines', insert.story_lines, ['id', 'lesson_id', 'ordinal', 'speaker', 'sentence_id', 'question'], {
    question: (v) => (v == null ? 'null' : jsonb(v)),
  }),
  insertNew('unit_phrases', insert.unit_phrases, ['unit_id', 'ordinal', 'sentence_id']),
].join('\n');

writeFileSync(out, sql);
console.log(`\nwrote ${out}. Apply it with npm run db:push.`);
