#!/usr/bin/env node
// Writes the course into a migration: the section-1 outline, with units 1–2
// (the ones that have lessons written) published and units 3–20 as drafts.
//
//   npm run course:seed -- supabase/migrations/<timestamp>_seed_section_1.sql
//
// Every statement is an upsert on the content's deterministic id, so applying
// it twice changes nothing. It is how the course first gets into the database;
// after that the database is the source of truth and edits go through the
// dashboard, not through this file.

import { writeFileSync } from 'node:fs';

import { buildRows } from './lib/rows.mjs';

const out = process.argv[2];
if (!out) {
  console.error('usage: node scripts/course/build-seed.mjs <output.sql>');
  process.exit(1);
}
const PUBLISH_THROUGH = 2;

const q = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const jsonb = (v) => `${q(JSON.stringify(v))}::jsonb`;
const textArray = (a) => (a.length ? `array[${a.map(q).join(', ')}]::text[]` : `'{}'::text[]`);

/** One multi-row upsert. `cast` maps a column to its SQL literal writer. */
function upsert(table, rows, columns, cast = {}, conflict = 'id') {
  if (rows.length === 0) return '';
  const values = rows
    .map((r) => `  (${columns.map((c) => (cast[c] ? cast[c](r[c]) : q(r[c]))).join(', ')})`)
    .join(',\n');
  const updates = columns
    .filter((c) => c !== conflict)
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  return `insert into public.${table} (${columns.join(', ')}) values\n${values}\non conflict (${conflict}) do update set ${updates};\n`;
}

let built;
try {
  built = buildRows({ publishThrough: PUBLISH_THROUGH });
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
const { rows, warnings } = built;
for (const w of warnings) console.warn(`warn  ${w}`);

const sql = [
  `-- ---------------------------------------------------------------------------
-- Seed: section 1 of the course — generated by scripts/course/build-seed.mjs
-- from docs/course/section-1.yaml and scripts/course/fixtures/demo.yaml.
-- Do not edit by hand; regenerate.
--
-- Units 1–${PUBLISH_THROUGH} are published: they have lessons written. Their sentences are
-- hand-written and NOT yet reviewed by a native speaker. Units ${PUBLISH_THROUGH + 1}–20 go in as
-- drafts — outline, words and tips — for the pipeline to fill.
--
-- Idempotent: every row is an upsert on its deterministic id.
-- ---------------------------------------------------------------------------
`,
  upsert('sections', rows.sections, ['id', 'ordinal', 'slug', 'title_en', 'cefr', 'status']),
  upsert(
    'units',
    rows.units,
    ['id', 'section_id', 'ordinal', 'slug', 'title_en', 'summary_en', 'grammar_focus', 'register_max', 'status'],
    { grammar_focus: textArray },
  ),
  upsert('lessons', rows.lessons, ['id', 'unit_id', 'ordinal', 'title_en', 'kind', 'status']),
  upsert('tips', rows.tips, ['id', 'unit_id', 'title_en', 'body_md', 'status']),
  upsert('lemmas', rows.lemmas, ['id', 'lemma', 'pos', 'gloss_en', 'register', 'is_glue', 'notes_en', 'status']),
  upsert('forms', rows.forms, ['id', 'lemma_id', 'form', 'features', 'gloss_en', 'unit_id', 'audio_path', 'status'], {
    features: jsonb,
  }),
  // sentence_forms follows by trigger.
  upsert(
    'sentences',
    rows.sentences,
    ['id', 'unit_id', 'es', 'en', 'en_alt', 'es_alt', 'tokens', 'target_form_id', 'kind', 'difficulty', 'source', 'attribution', 'audio_path', 'status'],
    { en_alt: textArray, es_alt: textArray, tokens: jsonb },
  ),
  upsert('lesson_slots', rows.lesson_slots, ['id', 'lesson_id', 'ordinal', 'kind', 'form_id', 'sentence_id', 'tip_id', 'mode', 'review_count']),
].join('\n');

writeFileSync(out, sql);
const published = (list) => list.filter((r) => r.status === 'published').length;
console.log(
  `wrote ${out}: ${rows.units.length} units (${published(rows.units)} published), ` +
    `${rows.lessons.length} lessons (${published(rows.lessons)}), ${rows.forms.length} forms (${published(rows.forms)}), ` +
    `${rows.sentences.length} sentences, ${rows.lesson_slots.length} slots`,
);
